# ELT Pipeline: Hotel Bookings CSV + Hotel Reviews NDJSON

## **Extract**

### Import Libraries

In [ ]:
!pip -q install gdown sqlalchemy psycopg2-binary altair vegafusion

import os
import re
import json
import time
import math
import hashlib
import warnings
from datetime import datetime
from urllib.parse import quote_plus

import gdown
import numpy as np
import pandas as pd
import altair as alt

from IPython.display import display, Markdown
from sqlalchemy import create_engine, text
from sqlalchemy.types import BigInteger, Integer, Float, String, Text, DateTime, Date

warnings.filterwarnings("ignore")

pd.set_option("display.max_rows", 120)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", 180)

ALT_WIDTH = 720
ALT_HEIGHT = 320
try:
    alt.data_transformers.enable("vegafusion")
except Exception:
    alt.data_transformers.disable_max_rows()

PIPELINE_START_TIME = time.time()
process_log = []

UNUSUAL_VALUES = [
    "", " ", "NULL", "null", "None", "none", "NA", "N/A", "nan", "NaN",
    "Not Available", "No Negative", "No Positive", "unknown", "Unknown"
]

DATE_FILL_VALUE = pd.Timestamp("1900-01-01")


def log_step(step, detail="", start_time=None, rows=None, columns=None, status="SUCCESS"):
    elapsed = None if start_time is None else round(time.time() - start_time, 4)
    process_log.append({
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "step": step,
        "status": status,
        "detail": detail,
        "rows": rows,
        "columns": columns,
        "execution_seconds": elapsed,
    })


def show_process_log():
    display(pd.DataFrame(process_log))


def is_placeholder(value):
    value = "" if value is None else str(value).strip()
    return value == "" or value.startswith("PASTE_") or value.startswith("YOUR_")


def standardize_column_names(df):
    clean = df.copy()
    clean.columns = (
        clean.columns.astype(str)
        .str.strip()
        .str.replace(r"[^A-Za-z0-9]+", "_", regex=True)
        .str.replace(r"_+", "_", regex=True)
        .str.strip("_")
        .str.lower()
    )
    return clean


def clean_string_series(series, fill_value="Unknown"):
    out = series.astype("string").str.strip()
    out = out.replace(UNUSUAL_VALUES, pd.NA)
    return out.fillna(fill_value).astype(str)


def safe_numeric(series, fill_value=0):
    return pd.to_numeric(series, errors="coerce").replace([np.inf, -np.inf], np.nan).fillna(fill_value)


def safe_datetime(series, fill_value=DATE_FILL_VALUE):
    return pd.to_datetime(series, errors="coerce").fillna(fill_value)


def minmax_normalize(series):
    numeric = safe_numeric(series, fill_value=0).astype(float)
    min_value = numeric.min()
    max_value = numeric.max()
    if pd.isna(min_value) or pd.isna(max_value) or max_value == min_value:
        return pd.Series(0.0, index=series.index)
    return ((numeric - min_value) / (max_value - min_value)).round(6)


def frequency_encode(series):
    cleaned = clean_string_series(series)
    freq = cleaned.value_counts(normalize=True, dropna=False)
    return cleaned.map(freq).fillna(0).round(6)


def safe_for_sql(df):
    """Remove NaN/NaT/infinity before warehouse loading, while preserving usable dtypes."""
    out = df.copy()
    out = out.replace([np.inf, -np.inf], np.nan)
    for col in out.columns:
        if pd.api.types.is_datetime64_any_dtype(out[col]):
            out[col] = pd.to_datetime(out[col], errors="coerce").fillna(DATE_FILL_VALUE)
        elif pd.api.types.is_numeric_dtype(out[col]):
            out[col] = pd.to_numeric(out[col], errors="coerce").fillna(0)
        else:
            out[col] = out[col].astype("string").fillna("Unknown").replace({"<NA>": "Unknown"}).astype(str)
    return out


def read_dataset_flexible(file_path, nrows=None):
    file_path = str(file_path)
    lower = file_path.lower()
    if lower.endswith(".csv"):
        return pd.read_csv(file_path, nrows=nrows)
    if lower.endswith((".jsonl", ".ndjson")):
        return pd.read_json(file_path, lines=True, nrows=nrows)
    if lower.endswith(".json"):
        try:
            return pd.read_json(file_path, lines=True, nrows=nrows)
        except ValueError:
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, dict):
                list_values = [v for v in data.values() if isinstance(v, list)]
                data = list_values[0] if list_values else [data]
            return pd.json_normalize(data)
    raise ValueError(f"Unsupported file format: {file_path}")


def download_with_gdown(source, output_filename, data_dir="/content/hotel_pipeline_data"):
    os.makedirs(data_dir, exist_ok=True)
    output_path = os.path.join(data_dir, output_filename)
    if os.path.exists(output_path):
        print(f"Already available: {output_path}")
        return output_path

    if is_placeholder(source):
        local_candidates = [
            output_filename,
            os.path.join("/content", output_filename),
            os.path.join(data_dir, output_filename),
            os.path.join("/content/drive/MyDrive", output_filename),
        ]
        for candidate in local_candidates:
            if os.path.exists(candidate):
                print(f"Using existing local file: {candidate}")
                return candidate
        raise ValueError(
            f"Google Drive source for {output_filename} is still a placeholder. "
            "Paste a Google Drive share URL/file ID or upload the file to Colab first."
        )

    source = str(source).strip()
    if source.startswith("http"):
        # Support both older and newer gdown versions.
        try:
            gdown.download(source, output_path, quiet=False, fuzzy=True)
        except TypeError:
            match = re.search(r"/d/([^/]+)|[?&]id=([^&]+)", source)
            file_id = next((group for group in match.groups() if group), None) if match else None
            if not file_id:
                raise ValueError(f"Could not extract a Google Drive file ID from: {source}")
            gdown.download(id=file_id, output=output_path, quiet=False)
    else:
        gdown.download(id=source, output=output_path, quiet=False)

    if not os.path.exists(output_path):
        raise FileNotFoundError(f"Download failed or output file was not created: {output_path}")
    print(f"Downloaded: {output_path}")
    return output_path


def extract_source(file_path, dataset_name, nrows=None):
    start = time.time()
    df = read_dataset_flexible(file_path, nrows=nrows)
    df.attrs["source_file"] = file_path
    df.attrs["dataset_name"] = dataset_name
    log_step("Extract", f"{dataset_name} loaded from {file_path}", start, df.shape[0], df.shape[1])
    return df

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 28.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 42.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 46.5 MB/s eta 0:00:00

### Extract Datasets

In [ ]:
HOTEL_BOOKINGS_GDRIVE = "https://drive.google.com/file/d/1gsx12q_7A5eO6RtspD1vGUvZJONulyNT/view?usp=drive_link"
HOTEL_REVIEWS_GDRIVE = "https://drive.google.com/file/d/19iBzMY5IqpXMJyOuYZ9Fa-J-65CHfDo9/view?usp=drive_link"

BOOKINGS_FILE = "hotel_bookings.csv"
REVIEWS_FILE = "hotel_reviews.ndjson"
DATA_DIR = "/content/hotel_pipeline_data"

# Keep None for full dataset. Set a number such as 50000 only if Colab memory is limited.
BOOKINGS_NROWS = None
REVIEWS_NROWS = None

bookings_path = download_with_gdown(HOTEL_BOOKINGS_GDRIVE, BOOKINGS_FILE, DATA_DIR)
reviews_path = download_with_gdown(HOTEL_REVIEWS_GDRIVE, REVIEWS_FILE, DATA_DIR)

source1_raw = extract_source(bookings_path, "Source 1 - Hotel Bookings Raw", nrows=BOOKINGS_NROWS)
source2_raw = extract_source(reviews_path, "Source 2 - Hotel Reviews Raw", nrows=REVIEWS_NROWS)

print("Source 1 shape:", source1_raw.shape)
print("Source 2 shape:", source2_raw.shape)
display(source1_raw.head())
display(source2_raw.head())

Downloading...
From: https://drive.google.com/uc?id=1gsx12q_7A5eO6RtspD1vGUvZJONulyNT
To: /content/hotel_pipeline_data/hotel_bookings.csv
100%|██████████| 16.9M/16.9M [00:00<00:00, 84.4MB/s]

Downloaded: /content/hotel_pipeline_data/hotel_bookings.csv

Downloading...
From (original): https://drive.google.com/uc?id=19iBzMY5IqpXMJyOuYZ9Fa-J-65CHfDo9
From (redirected): https://drive.google.com/uc?id=19iBzMY5IqpXMJyOuYZ9Fa-J-65CHfDo9&confirm=t&uuid=7a88dd66-b5ea-464c-812f-39e398dbfbd8
To: /content/hotel_pipeline_data/hotel_reviews.ndjson
100%|██████████| 443M/443M [00:05<00:00, 81.5MB/s]

Downloaded: /content/hotel_pipeline_data/hotel_reviews.ndjson
Source 1 shape: (119390, 32)
Source 2 shape: (515738, 17)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

,Hotel_Address,Additional_Number_of_Scoring,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,lat,lng
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available via all possible sites i use when planing my trips so no one will make the mistake of booking this place I made my booking via bo...,397,1403,Only the park outside of the hotel was beautiful,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double Room ', ' Stayed 6 nights ']",0 days,52.360576,4.915968
1,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great location surroundings rooms amenities and service Two recommendations however firstly the staff upon check in are very confusing r...,105,7,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double Room ', ' Stayed 4 nights ']",0 days,52.360576,4.915968
2,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficult as most rooms are two story with narrow steps So ask for single level Inside the rooms are very very basic just tea coffee and b...,42,1403,Location was good and staff were ok It is cute hotel the breakfast range is nice Will go back,21,9,7.1,"[' Leisure trip ', ' Family with young children ', ' Duplex Double Room ', ' Stayed 3 nights ', ' Submitted from a mobile device ']",3 days,52.360576,4.915968
3,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194,7/31/2017,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk barefoot on the floor which looked as if it was not cleaned in weeks White furniture which looked nice in pictures was dirty too and...,210,1403,Great location in nice surroundings the bar and restaurant are nice and have a lovely outdoor area The building also has quite some character,26,1,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex Double Room ', ' Stayed 3 nights ']",3 days,52.360576,4.915968
4,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194,7/24/2017,7.7,Hotel Arena,New Zealand,You When I booked with your company on line you showed me pictures of a room I thought I was getting and paying for and then when we arrived that s room was booked and the sta...,140,1403,Amazing location and building Romantic setting,8,3,6.7,"[' Leisure trip ', ' Couple ', ' Suite ', ' Stayed 2 nights ', ' Submitted from a mobile device ']",10 days,52.360576,4.915968

### Overview Reports and Frequency Displays

In [ ]:
def memory_usage_report(df, dataset_name):
    start = time.time()
    mem = df.memory_usage(deep=True).sort_values(ascending=False).reset_index()
    mem.columns = ["column", "memory_bytes"]
    mem["memory_mb"] = (mem["memory_bytes"] / (1024 ** 2)).round(4)
    mem.insert(0, "dataset", dataset_name)
    print(f"Memory usage report - {dataset_name}")
    display(mem)
    log_step("Memory Report", dataset_name, start, df.shape[0], df.shape[1])
    return mem


def overview_report(df, dataset_name):
    start = time.time()
    total_cells = int(df.shape[0] * df.shape[1])
    missing_cells = int(df.isna().sum().sum())
    duplicated_rows = int(df.duplicated().sum())
    unusual_cells = 0
    for col in df.columns:
        if df[col].dtype == "object" or str(df[col].dtype).startswith("string"):
            unusual_cells += int(df[col].astype(str).str.strip().isin(UNUSUAL_VALUES).sum())

    dataset_summary = pd.DataFrame([{
        "dataset": dataset_name,
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "cells": total_cells,
        "duplicated_rows": duplicated_rows,
        "missing_cells": missing_cells,
        "missing_cell_pct": round(missing_cells / max(total_cells, 1) * 100, 4),
        "unusual_value_cells": unusual_cells,
        "memory_mb": round(df.memory_usage(deep=True).sum() / (1024 ** 2), 4),
        "numeric_columns": int(len(df.select_dtypes(include=["number"]).columns)),
        "categorical_columns": int(len(df.select_dtypes(include=["object", "category", "string", "bool"]).columns)),
        "datetime_columns": int(len(df.select_dtypes(include=["datetime", "datetimetz"]).columns)),
        "execution_seconds": round(time.time() - start, 4),
    }])

    column_report = pd.DataFrame({
        "dataset": dataset_name,
        "column": df.columns,
        "dtype": [str(dtype) for dtype in df.dtypes],
        "non_null_count": df.notna().sum().values,
        "null_count": df.isna().sum().values,
        "null_pct": (df.isna().sum().values / max(len(df), 1) * 100).round(4),
        "unique_count": df.nunique(dropna=True).values,
        "unique_pct": (df.nunique(dropna=True).values / max(len(df), 1) * 100).round(4),
        "sample_values": [", ".join(map(str, df[col].dropna().astype(str).unique()[:3])) for col in df.columns],
        "memory_mb": (df.memory_usage(deep=True).reindex(df.columns).fillna(0).values / (1024 ** 2)).round(4),
    })

    print(f"Overview report - {dataset_name}")
    display(dataset_summary)
    display(column_report)
    log_step("Overview Report", dataset_name, start, df.shape[0], df.shape[1])
    return dataset_summary, column_report


def frequency_display(df, dataset_name, max_columns=12, top_n=12):
    start = time.time()
    categorical_cols = df.select_dtypes(include=["object", "category", "string", "bool"]).columns.tolist()[:max_columns]
    result = {}
    for col in categorical_cols:
        freq = (
            df[col]
            .astype("string")
            .fillna("<NULL>")
            .value_counts(dropna=False)
            .head(top_n)
            .reset_index()
        )
        freq.columns = ["value", "frequency"]
        freq.insert(0, "column", col)
        freq.insert(0, "dataset", dataset_name)
        freq["percentage"] = (freq["frequency"] / max(len(df), 1) * 100).round(4)
        result[col] = freq
        print(f"Frequency display - {dataset_name} - {col}")
        display(freq)
    log_step("Frequency Display", f"{dataset_name}: {len(categorical_cols)} categorical columns shown", start, df.shape[0], df.shape[1])
    return result


def unusual_values_report(df, dataset_name):
    start = time.time()
    rows = []
    for col in df.columns:
        series = df[col]
        missing_count = int(series.isna().sum())
        unusual_count = 0
        examples = []
        if series.dtype == "object" or str(series.dtype).startswith("string"):
            stripped = series.astype("string").str.strip()
            unusual_mask = stripped.isin(UNUSUAL_VALUES)
            unusual_count = int(unusual_mask.sum())
            examples = stripped[unusual_mask].dropna().unique()[:5].tolist()
        if missing_count > 0 or unusual_count > 0:
            rows.append({
                "dataset": dataset_name,
                "column": col,
                "missing_count": missing_count,
                "unusual_value_count": unusual_count,
                "unusual_examples": ", ".join(map(str, examples)),
            })
    report = pd.DataFrame(rows)
    print(f"Unusual/missing values report - {dataset_name}")
    display(report)
    log_step("Unusual Values Report", dataset_name, start, df.shape[0], df.shape[1])
    return report


def outlier_report_iqr(df, dataset_name, exclude_cols=None):
    start = time.time()
    exclude_cols = set(exclude_cols or [])
    rows = []
    masks = []
    for col in df.select_dtypes(include=["number"]).columns:
        if col in exclude_cols or col.endswith("_id"):
            continue
        values = pd.to_numeric(df[col], errors="coerce").dropna()
        if values.empty:
            continue
        q1 = values.quantile(0.25)
        q3 = values.quantile(0.75)
        iqr = q3 - q1
        if pd.isna(iqr) or iqr == 0:
            continue
        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr
        mask = ((pd.to_numeric(df[col], errors="coerce") < lower) | (pd.to_numeric(df[col], errors="coerce") > upper)).fillna(False)
        masks.append(mask.rename(col))
        rows.append({
            "dataset": dataset_name,
            "column": col,
            "q1": round(q1, 4),
            "q3": round(q3, 4),
            "iqr": round(iqr, 4),
            "lower_bound": round(lower, 4),
            "upper_bound": round(upper, 4),
            "outlier_count": int(mask.sum()),
            "outlier_pct": round(mask.mean() * 100, 4),
        })
    report = pd.DataFrame(rows)
    mask_df = pd.concat(masks, axis=1) if masks else pd.DataFrame(index=df.index)
    print(f"IQR outlier report - {dataset_name}")
    display(report)
    log_step("Outlier Report", dataset_name, start, df.shape[0], df.shape[1])
    return report, mask_df


def data_distribution_report(df, dataset_name, numeric_top=12):
    start = time.time()
    numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()[:numeric_top]
    if numeric_cols:
        report = df[numeric_cols].describe().T.reset_index().rename(columns={"index": "column"})
        report.insert(0, "dataset", dataset_name)
    else:
        report = pd.DataFrame(columns=["dataset", "column"])
    print(f"Distribution report - {dataset_name}")
    display(report)
    log_step("Distribution Report", dataset_name, start, df.shape[0], df.shape[1])
    return report


def datatype_consistency_report(df, dataset_name):
    start = time.time()
    rows = []
    for col in df.columns:
        sample = df[col].dropna().head(200)
        parse_numeric_pct = None
        parse_datetime_pct = None
        if df[col].dtype == "object" or str(df[col].dtype).startswith("string"):
            parse_numeric_pct = round(pd.to_numeric(sample, errors="coerce").notna().mean() * 100, 2) if len(sample) else 0
            parse_datetime_pct = round(pd.to_datetime(sample, errors="coerce").notna().mean() * 100, 2) if len(sample) else 0
        rows.append({
            "dataset": dataset_name,
            "column": col,
            "dtype": str(df[col].dtype),
            "numeric_parse_pct_if_object": parse_numeric_pct,
            "datetime_parse_pct_if_object": parse_datetime_pct,
            "recommendation": "review type conversion" if (parse_numeric_pct and parse_numeric_pct > 90) or (parse_datetime_pct and parse_datetime_pct > 90) else "ok"
        })
    report = pd.DataFrame(rows)
    print(f"Datatype consistency report - {dataset_name}")
    display(report)
    log_step("Datatype Consistency Report", dataset_name, start, df.shape[0], df.shape[1])
    return report


def range_check_report(df, dataset_name, rules):
    start = time.time()
    rows = []
    for col, rule in rules.items():
        if col not in df.columns:
            rows.append({"dataset": dataset_name, "column": col, "rule": str(rule), "status": "MISSING_COLUMN", "invalid_count": None})
            continue
        series = pd.to_numeric(df[col], errors="coerce")
        invalid = pd.Series(False, index=df.index)
        if "min" in rule:
            invalid = invalid | (series < rule["min"])
        if "max" in rule:
            invalid = invalid | (series > rule["max"])
        invalid_count = int(invalid.fillna(False).sum())
        rows.append({
            "dataset": dataset_name,
            "column": col,
            "rule": str(rule),
            "status": "PASS" if invalid_count == 0 else "FAIL",
            "invalid_count": invalid_count,
        })
    report = pd.DataFrame(rows)
    print(f"Range check report - {dataset_name}")
    display(report)
    log_step("Range Check Report", dataset_name, start, df.shape[0], df.shape[1])
    return report


def quality_assessment_plan(df, dataset_name, transform_method):
    start = time.time()
    categorical_cols = df.select_dtypes(include=["object", "category", "string", "bool"]).columns.tolist()
    numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
    rows = [
        {"stage": "column standardization", "method": "lowercase snake_case columns", "target_columns": "all", "priority": "high", "status": "planned"},
        {"stage": "missing value handling", "method": "fill categorical with Unknown, numeric with 0/median, dates with 1900-01-01", "target_columns": "all nullable columns", "priority": "high", "status": "planned"},
        {"stage": "unusual value handling", "method": "replace placeholders such as No Negative, No Positive, NULL, N/A", "target_columns": "categorical/text", "priority": "high", "status": "planned"},
        {"stage": "datatype conversion", "method": "convert date and numeric columns into consistent types", "target_columns": "date/numeric fields", "priority": "high", "status": "planned"},
        {"stage": "range validation", "method": "validate impossible values such as negative guests, scores outside 0-10, invalid lat/lng", "target_columns": "numeric business fields", "priority": "high", "status": "planned"},
        {"stage": "outlier detection", "method": "IQR tagging for ETL/Pandas and SQL aggregate/range checks for ELT", "target_columns": ", ".join(numeric_cols[:12]), "priority": "medium", "status": "planned"},
        {"stage": "categorical encoding", "method": "frequency encoding for selected categorical columns", "target_columns": ", ".join(categorical_cols[:10]), "priority": "new addition", "status": "planned"},
        {"stage": "numerical normalization", "method": "min-max normalization for selected numeric columns", "target_columns": ", ".join(numeric_cols[:10]), "priority": "new addition", "status": "planned"},
        {"stage": "primary key preparation", "method": "create deterministic integer surrogate keys before warehouse load", "target_columns": "booking_id, review_id, dimension ids", "priority": "high", "status": "planned"},
        {"stage": "foreign key preparation", "method": "map facts into dimension surrogate keys before loading constraints", "target_columns": "*_id fields", "priority": "high", "status": "planned"},
        {"stage": "distribution validation", "method": "describe numeric distribution and categorical frequency before/after cleaning", "target_columns": "all analytical fields", "priority": "high", "status": "planned"},
    ]
    report = pd.DataFrame(rows)
    report.insert(0, "dataset", dataset_name)
    report.insert(1, "transform_method", transform_method)
    print(f"Quality assessment plan - {dataset_name}")
    display(report)
    log_step("Quality Assessment Plan", f"{dataset_name} using {transform_method}", start, df.shape[0], df.shape[1])
    return report

In [ ]:
source1_overview_summary, source1_column_overview = overview_report(source1_raw, "Source 1 - Hotel Bookings Raw")
source2_overview_summary, source2_column_overview = overview_report(source2_raw, "Source 2 - Hotel Reviews Raw")

source1_memory_report = memory_usage_report(source1_raw, "Source 1 - Hotel Bookings Raw")
source2_memory_report = memory_usage_report(source2_raw, "Source 2 - Hotel Reviews Raw")

source1_frequency = frequency_display(source1_raw, "Source 1 - Hotel Bookings Raw")
source2_frequency = frequency_display(source2_raw, "Source 2 - Hotel Reviews Raw")

source1_unusual_report = unusual_values_report(source1_raw, "Source 1 - Hotel Bookings Raw")
source2_unusual_report = unusual_values_report(source2_raw, "Source 2 - Hotel Reviews Raw")

source1_datatype_report = datatype_consistency_report(source1_raw, "Source 1 - Hotel Bookings Raw")
source2_datatype_report = datatype_consistency_report(source2_raw, "Source 2 - Hotel Reviews Raw")

source1_distribution_report = data_distribution_report(source1_raw, "Source 1 - Hotel Bookings Raw")
source2_distribution_report = data_distribution_report(source2_raw, "Source 2 - Hotel Reviews Raw")

Overview report - Source 1 - Hotel Bookings Raw

,dataset,rows,columns,cells,duplicated_rows,missing_cells,missing_cell_pct,unusual_value_cells,memory_mb,numeric_columns,categorical_columns,datetime_columns,execution_seconds
0,Source 1 - Hotel Bookings Raw,119390,32,3820480,31994,129425,3.3877,488,93.9046,20,12,0,2.2876

,dataset,column,dtype,non_null_count,null_count,null_pct,unique_count,unique_pct,sample_values,memory_mb
0,Source 1 - Hotel Bookings Raw,hotel,object,119390,0,0.0000,2,0.0017,"Resort Hotel, City Hotel",6.7941
1,Source 1 - Hotel Bookings Raw,is_canceled,int64,119390,0,0.0000,2,0.0017,"0, 1",0.9109
2,Source 1 - Hotel Bookings Raw,lead_time,int64,119390,0,0.0000,479,0.4012,"342, 737, 7",0.9109
3,Source 1 - Hotel Bookings Raw,arrival_date_year,int64,119390,0,0.0000,3,0.0025,"2015, 2016, 2017",0.9109
4,Source 1 - Hotel Bookings Raw,arrival_date_month,object,119390,0,0.0000,12,0.0101,"July, August, September",6.2512
5,Source 1 - Hotel Bookings Raw,arrival_date_week_number,int64,119390,0,0.0000,53,0.0444,"27, 28, 29",0.9109
6,Source 1 - Hotel Bookings Raw,arrival_date_day_of_month,int64,119390,0,0.0000,31,0.0260,"1, 2, 3",0.9109
7,Source 1 - Hotel Bookings Raw,stays_in_weekend_nights,int64,119390,0,0.0000,17,0.0142,"0, 1, 2",0.9109
8,Source 1 - Hotel Bookings Raw,stays_in_week_nights,int64,119390,0,0.0000,35,0.0293,"0, 1, 2",0.9109
9,Source 1 - Hotel Bookings Raw,adults,int64,119390,0,0.0000,14,0.0117,"2, 1, 3",0.9109
10,Source 1 - Hotel Bookings Raw,children,float64,119386,4,0.0034,5,0.0042,"0.0, 1.0, 2.0",0.9109
11,Source 1 - Hotel Bookings Raw,babies,int64,119390,0,0.0000,5,0.0042,"0, 1, 2",0.9109
12,Source 1 - Hotel Bookings Raw,meal,object,119390,0,0.0000,5,0.0042,"BB, FB, HB",5.8146
13,Source 1 - Hotel Bookings Raw,country,object,118902,488,0.4087,177,0.1483,"PRT, GBR, USA",5.9101
14,Source 1 - Hotel Bookings Raw,market_segment,object,119390,0,0.0000,8,0.0067,"Direct, Corporate, Online TA",6.6061
15,Source 1 - Hotel Bookings Raw,distribution_channel,object,119390,0,0.0000,5,0.0042,"Direct, Corporate, TA/TO",6.1875
16,Source 1 - Hotel Bookings Raw,is_repeated_guest,int64,119390,0,0.0000,2,0.0017,"0, 1",0.9109
17,Source 1 - Hotel Bookings Raw,previous_cancellations,int64,119390,0,0.0000,15,0.0126,"0, 1, 2",0.9109
18,Source 1 - Hotel Bookings Raw,previous_bookings_not_canceled,int64,119390,0,0.0000,73,0.0611,"0, 1, 2",0.9109
19,Source 1 - Hotel Bookings Raw,reserved_room_type,object,119390,0,0.0000,10,0.0084,"C, A, D",5.6930
20,Source 1 - Hotel Bookings Raw,assigned_room_type,object,119390,0,0.0000,12,0.0101,"C, A, D",5.6930
21,Source 1 - Hotel Bookings Raw,booking_changes,int64,119390,0,0.0000,21,0.0176,"3, 4, 0",0.9109
22,Source 1 - Hotel Bookings Raw,deposit_type,object,119390,0,0.0000,3,0.0025,"No Deposit, Refundable, Non Refund",6.7177
23,Source 1 - Hotel Bookings Raw,agent,float64,103050,16340,13.6862,333,0.2789,"304.0, 240.0, 303.0",0.9109
24,Source 1 - Hotel Bookings Raw,company,float64,6797,112593,94.3069,352,0.2948,"110.0, 113.0, 270.0",0.9109
25,Source 1 - Hotel Bookings Raw,days_in_waiting_list,int64,119390,0,0.0000,128,0.1072,"0, 50, 47",0.9109
26,Source 1 - Hotel Bookings Raw,customer_type,object,119390,0,0.0000,4,0.0034,"Transient, Contract, Transient-Party",6.7415
27,Source 1 - Hotel Bookings Raw,adr,float64,119390,0,0.0000,8879,7.4370,"0.0, 75.0, 98.0",0.9109
28,Source 1 - Hotel Bookings Raw,required_car_parking_spaces,int64,119390,0,0.0000,5,0.0042,"0, 1, 2",0.9109
29,Source 1 - Hotel Bookings Raw,total_of_special_requests,int64,119390,0,0.0000,6,0.0050,"0, 1, 3",0.9109
30,Source 1 - Hotel Bookings Raw,reservation_status,object,119390,0,0.0000,3,0.0025,"Check-Out, Canceled, No-Show",6.5605
31,Source 1 - Hotel Bookings Raw,reservation_status_date,object,119390,0,0.0000,926,0.7756,"2015-07-01, 2015-07-02, 2015-07-03",6.7177

Overview report - Source 2 - Hotel Reviews Raw

,dataset,rows,columns,cells,duplicated_rows,missing_cells,missing_cell_pct,unusual_value_cells,memory_mb,numeric_columns,categorical_columns,datetime_columns,execution_seconds
0,Source 2 - Hotel Reviews Raw,515738,17,8767546,526,6536,0.0745,167082,427.8938,9,8,0,14.8042

,dataset,column,dtype,non_null_count,null_count,null_pct,unique_count,unique_pct,sample_values,memory_mb
0,Source 2 - Hotel Reviews Raw,Hotel_Address,object,515738,0,0.0000,1493,0.2895,"s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands, 1 15 Templeton Place Earl s Court Kensington and Chelsea London SW5 9NB United Kingdom, 1 2 Serjeant s Inn Fleet Stre...",53.5519
1,Source 2 - Hotel Reviews Raw,Additional_Number_of_Scoring,int64,515738,0,0.0000,480,0.0931,"194, 244, 639",3.9348
2,Source 2 - Hotel Reviews Raw,Review_Date,object,515738,0,0.0000,731,0.1417,"8/3/2017, 7/31/2017, 7/24/2017",28.4932
3,Source 2 - Hotel Reviews Raw,Average_Score,float64,515738,0,0.0000,34,0.0066,"7.7, 8.5, 9.2",3.9348
4,Source 2 - Hotel Reviews Raw,Hotel_Name,object,515738,0,0.0000,1492,0.2893,"Hotel Arena, K K Hotel George, Apex Temple Court Hotel",36.5476
5,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,object,515738,0,0.0000,227,0.0440,"Russia , Ireland , Australia",31.0041
6,Source 2 - Hotel Reviews Raw,Negative_Review,object,515738,0,0.0000,330011,63.9881,I am so angry that i made this post available via all possible sites i use when planing my trips so no one will make the mistake of booking this place I made my booking via bo...,70.2347
7,Source 2 - Hotel Reviews Raw,Review_Total_Negative_Word_Counts,int64,515738,0,0.0000,402,0.0779,"397, 0, 42",3.9348
8,Source 2 - Hotel Reviews Raw,Total_Number_of_Reviews,int64,515738,0,0.0000,1142,0.2214,"1403, 1831, 2619",3.9348
9,Source 2 - Hotel Reviews Raw,Positive_Review,object,515738,0,0.0000,412601,80.0021,"Only the park outside of the hotel was beautiful , No real complaints the hotel was great great location surroundings rooms amenities and service Two recommendations however ...",70.6395
10,Source 2 - Hotel Reviews Raw,Review_Total_Positive_Word_Counts,int64,515738,0,0.0000,365,0.0708,"11, 105, 21",3.9348
11,Source 2 - Hotel Reviews Raw,Total_Number_of_Reviews_Reviewer_Has_Given,int64,515738,0,0.0000,198,0.0384,"7, 9, 1",3.9348
12,Source 2 - Hotel Reviews Raw,Reviewer_Score,float64,515738,0,0.0000,37,0.0072,"2.9, 7.5, 7.1",3.9348
13,Source 2 - Hotel Reviews Raw,Tags,object,515738,0,0.0000,55242,10.7113,"[' Leisure trip ', ' Couple ', ' Duplex Double Room ', ' Stayed 6 nights '], [' Leisure trip ', ' Couple ', ' Duplex Double Room ', ' Stayed 4 nights '], [' Leisure trip ', ' F...",74.4743
14,Source 2 - Hotel Reviews Raw,days_since_review,object,515738,0,0.0000,731,0.1417,"0 days, 3 days, 10 days",27.5355
15,Source 2 - Hotel Reviews Raw,lat,float64,512470,3268,0.6337,1472,0.2854,"52.3605759, 51.4918878, 51.5137335",3.9348
16,Source 2 - Hotel Reviews Raw,lng,float64,512470,3268,0.6337,1472,0.2854,"4.9159683, -0.1949706, -0.10875119999999999",3.9348

Memory usage report - Source 1 - Hotel Bookings Raw

,dataset,column,memory_bytes,memory_mb
0,Source 1 - Hotel Bookings Raw,hotel,7124130,6.7941
1,Source 1 - Hotel Bookings Raw,customer_type,7068980,6.7415
2,Source 1 - Hotel Bookings Raw,deposit_type,7044010,6.7177
3,Source 1 - Hotel Bookings Raw,reservation_status_date,7044010,6.7177
4,Source 1 - Hotel Bookings Raw,market_segment,6926980,6.6061
5,Source 1 - Hotel Bookings Raw,reservation_status,6879189,6.5605
6,Source 1 - Hotel Bookings Raw,arrival_date_month,6554891,6.2512
7,Source 1 - Hotel Bookings Raw,distribution_channel,6488047,6.1875
8,Source 1 - Hotel Bookings Raw,country,6197241,5.9101
9,Source 1 - Hotel Bookings Raw,meal,6097073,5.8146
10,Source 1 - Hotel Bookings Raw,reserved_room_type,5969500,5.6930
11,Source 1 - Hotel Bookings Raw,assigned_room_type,5969500,5.6930
12,Source 1 - Hotel Bookings Raw,stays_in_week_nights,955120,0.9109
13,Source 1 - Hotel Bookings Raw,stays_in_weekend_nights,955120,0.9109
14,Source 1 - Hotel Bookings Raw,arrival_date_day_of_month,955120,0.9109
15,Source 1 - Hotel Bookings Raw,lead_time,955120,0.9109
16,Source 1 - Hotel Bookings Raw,is_canceled,955120,0.9109
17,Source 1 - Hotel Bookings Raw,agent,955120,0.9109
18,Source 1 - Hotel Bookings Raw,adults,955120,0.9109
19,Source 1 - Hotel Bookings Raw,children,955120,0.9109
20,Source 1 - Hotel Bookings Raw,babies,955120,0.9109
21,Source 1 - Hotel Bookings Raw,arrival_date_year,955120,0.9109
22,Source 1 - Hotel Bookings Raw,arrival_date_week_number,955120,0.9109
23,Source 1 - Hotel Bookings Raw,previous_bookings_not_canceled,955120,0.9109
24,Source 1 - Hotel Bookings Raw,is_repeated_guest,955120,0.9109
25,Source 1 - Hotel Bookings Raw,adr,955120,0.9109
26,Source 1 - Hotel Bookings Raw,booking_changes,955120,0.9109
27,Source 1 - Hotel Bookings Raw,previous_cancellations,955120,0.9109
28,Source 1 - Hotel Bookings Raw,company,955120,0.9109
29,Source 1 - Hotel Bookings Raw,total_of_special_requests,955120,0.9109
30,Source 1 - Hotel Bookings Raw,days_in_waiting_list,955120,0.9109
31,Source 1 - Hotel Bookings Raw,required_car_parking_spaces,955120,0.9109
32,Source 1 - Hotel Bookings Raw,Index,132,0.0001

Memory usage report - Source 2 - Hotel Reviews Raw

,dataset,column,memory_bytes,memory_mb
0,Source 2 - Hotel Reviews Raw,Tags,78091984,74.4743
1,Source 2 - Hotel Reviews Raw,Positive_Review,74070843,70.6395
2,Source 2 - Hotel Reviews Raw,Negative_Review,73646441,70.2347
3,Source 2 - Hotel Reviews Raw,Hotel_Address,56153222,53.5519
4,Source 2 - Hotel Reviews Raw,Hotel_Name,38322923,36.5476
5,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,32510201,31.0041
6,Source 2 - Hotel Reviews Raw,Review_Date,29877262,28.4932
7,Source 2 - Hotel Reviews Raw,days_since_review,28873055,27.5355
8,Source 2 - Hotel Reviews Raw,Total_Number_of_Reviews,4125904,3.9348
9,Source 2 - Hotel Reviews Raw,Average_Score,4125904,3.9348
10,Source 2 - Hotel Reviews Raw,Reviewer_Score,4125904,3.9348
11,Source 2 - Hotel Reviews Raw,Review_Total_Negative_Word_Counts,4125904,3.9348
12,Source 2 - Hotel Reviews Raw,Additional_Number_of_Scoring,4125904,3.9348
13,Source 2 - Hotel Reviews Raw,Review_Total_Positive_Word_Counts,4125904,3.9348
14,Source 2 - Hotel Reviews Raw,lat,4125904,3.9348
15,Source 2 - Hotel Reviews Raw,Total_Number_of_Reviews_Reviewer_Has_Given,4125904,3.9348
16,Source 2 - Hotel Reviews Raw,lng,4125904,3.9348
17,Source 2 - Hotel Reviews Raw,Index,132,0.0001

Frequency display - Source 1 - Hotel Bookings Raw - hotel

                         dataset column         value  frequency  percentage
0  Source 1 - Hotel Bookings Raw  hotel    City Hotel      79330     66.4461
1  Source 1 - Hotel Bookings Raw  hotel  Resort Hotel      40060     33.5539

Frequency display - Source 1 - Hotel Bookings Raw - arrival_date_month

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings Raw,arrival_date_month,August,13877,11.6233
1,Source 1 - Hotel Bookings Raw,arrival_date_month,July,12661,10.6047
2,Source 1 - Hotel Bookings Raw,arrival_date_month,May,11791,9.876
3,Source 1 - Hotel Bookings Raw,arrival_date_month,October,11160,9.3475
4,Source 1 - Hotel Bookings Raw,arrival_date_month,April,11089,9.288
5,Source 1 - Hotel Bookings Raw,arrival_date_month,June,10939,9.1624
6,Source 1 - Hotel Bookings Raw,arrival_date_month,September,10508,8.8014
7,Source 1 - Hotel Bookings Raw,arrival_date_month,March,9794,8.2034
8,Source 1 - Hotel Bookings Raw,arrival_date_month,February,8068,6.7577
9,Source 1 - Hotel Bookings Raw,arrival_date_month,November,6794,5.6906
10,Source 1 - Hotel Bookings Raw,arrival_date_month,December,6780,5.6789
11,Source 1 - Hotel Bookings Raw,arrival_date_month,January,5929,4.9661

Frequency display - Source 1 - Hotel Bookings Raw - meal

                         dataset column      value  frequency  percentage
0  Source 1 - Hotel Bookings Raw   meal         BB      92310      77.318
1  Source 1 - Hotel Bookings Raw   meal         HB      14463     12.1141
2  Source 1 - Hotel Bookings Raw   meal         SC      10650      8.9203
3  Source 1 - Hotel Bookings Raw   meal  Undefined       1169      0.9791
4  Source 1 - Hotel Bookings Raw   meal         FB        798      0.6684

Frequency display - Source 1 - Hotel Bookings Raw - country

                          dataset   column value  frequency  percentage
0   Source 1 - Hotel Bookings Raw  country   PRT      48590     40.6986
1   Source 1 - Hotel Bookings Raw  country   GBR      12129     10.1591
2   Source 1 - Hotel Bookings Raw  country   FRA      10415      8.7235
3   Source 1 - Hotel Bookings Raw  country   ESP       8568      7.1765
4   Source 1 - Hotel Bookings Raw  country   DEU       7287      6.1035
5   Source 1 - Hotel Bookings Raw  country   ITA       3766      3.1544
6   Source 1 - Hotel Bookings Raw  country   IRL       3375      2.8269
7   Source 1 - Hotel Bookings Raw  country   BEL       2342      1.9616
8   Source 1 - Hotel Bookings Raw  country   BRA       2224      1.8628
9   Source 1 - Hotel Bookings Raw  country   NLD       2104      1.7623
10  Source 1 - Hotel Bookings Raw  country   USA       2097      1.7564
11  Source 1 - Hotel Bookings Raw  country   CHE       1730       1.449

Frequency display - Source 1 - Hotel Bookings Raw - market_segment

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings Raw,market_segment,Online TA,56477,47.3046
1,Source 1 - Hotel Bookings Raw,market_segment,Offline TA/TO,24219,20.2856
2,Source 1 - Hotel Bookings Raw,market_segment,Groups,19811,16.5935
3,Source 1 - Hotel Bookings Raw,market_segment,Direct,12606,10.5587
4,Source 1 - Hotel Bookings Raw,market_segment,Corporate,5295,4.435
5,Source 1 - Hotel Bookings Raw,market_segment,Complementary,743,0.6223
6,Source 1 - Hotel Bookings Raw,market_segment,Aviation,237,0.1985
7,Source 1 - Hotel Bookings Raw,market_segment,Undefined,2,0.0017

Frequency display - Source 1 - Hotel Bookings Raw - distribution_channel

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings Raw,distribution_channel,TA/TO,97870,81.975
1,Source 1 - Hotel Bookings Raw,distribution_channel,Direct,14645,12.2665
2,Source 1 - Hotel Bookings Raw,distribution_channel,Corporate,6677,5.5926
3,Source 1 - Hotel Bookings Raw,distribution_channel,GDS,193,0.1617
4,Source 1 - Hotel Bookings Raw,distribution_channel,Undefined,5,0.0042

Frequency display - Source 1 - Hotel Bookings Raw - reserved_room_type

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings Raw,reserved_room_type,A,85994,72.0278
1,Source 1 - Hotel Bookings Raw,reserved_room_type,D,19201,16.0826
2,Source 1 - Hotel Bookings Raw,reserved_room_type,E,6535,5.4737
3,Source 1 - Hotel Bookings Raw,reserved_room_type,F,2897,2.4265
4,Source 1 - Hotel Bookings Raw,reserved_room_type,G,2094,1.7539
5,Source 1 - Hotel Bookings Raw,reserved_room_type,B,1118,0.9364
6,Source 1 - Hotel Bookings Raw,reserved_room_type,C,932,0.7806
7,Source 1 - Hotel Bookings Raw,reserved_room_type,H,601,0.5034
8,Source 1 - Hotel Bookings Raw,reserved_room_type,P,12,0.0101
9,Source 1 - Hotel Bookings Raw,reserved_room_type,L,6,0.005

Frequency display - Source 1 - Hotel Bookings Raw - assigned_room_type

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings Raw,assigned_room_type,A,74053,62.0261
1,Source 1 - Hotel Bookings Raw,assigned_room_type,D,25322,21.2095
2,Source 1 - Hotel Bookings Raw,assigned_room_type,E,7806,6.5382
3,Source 1 - Hotel Bookings Raw,assigned_room_type,F,3751,3.1418
4,Source 1 - Hotel Bookings Raw,assigned_room_type,G,2553,2.1384
5,Source 1 - Hotel Bookings Raw,assigned_room_type,C,2375,1.9893
6,Source 1 - Hotel Bookings Raw,assigned_room_type,B,2163,1.8117
7,Source 1 - Hotel Bookings Raw,assigned_room_type,H,712,0.5964
8,Source 1 - Hotel Bookings Raw,assigned_room_type,I,363,0.304
9,Source 1 - Hotel Bookings Raw,assigned_room_type,K,279,0.2337
10,Source 1 - Hotel Bookings Raw,assigned_room_type,P,12,0.0101
11,Source 1 - Hotel Bookings Raw,assigned_room_type,L,1,0.0008

Frequency display - Source 1 - Hotel Bookings Raw - deposit_type

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings Raw,deposit_type,No Deposit,104641,87.6464
1,Source 1 - Hotel Bookings Raw,deposit_type,Non Refund,14587,12.2179
2,Source 1 - Hotel Bookings Raw,deposit_type,Refundable,162,0.1357

Frequency display - Source 1 - Hotel Bookings Raw - customer_type

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings Raw,customer_type,Transient,89613,75.0591
1,Source 1 - Hotel Bookings Raw,customer_type,Transient-Party,25124,21.0436
2,Source 1 - Hotel Bookings Raw,customer_type,Contract,4076,3.414
3,Source 1 - Hotel Bookings Raw,customer_type,Group,577,0.4833

Frequency display - Source 1 - Hotel Bookings Raw - reservation_status

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings Raw,reservation_status,Check-Out,75166,62.9584
1,Source 1 - Hotel Bookings Raw,reservation_status,Canceled,43017,36.0307
2,Source 1 - Hotel Bookings Raw,reservation_status,No-Show,1207,1.011

Frequency display - Source 1 - Hotel Bookings Raw - reservation_status_date

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings Raw,reservation_status_date,2015-10-21,1461,1.2237
1,Source 1 - Hotel Bookings Raw,reservation_status_date,2015-07-06,805,0.6743
2,Source 1 - Hotel Bookings Raw,reservation_status_date,2016-11-25,790,0.6617
3,Source 1 - Hotel Bookings Raw,reservation_status_date,2015-01-01,763,0.6391
4,Source 1 - Hotel Bookings Raw,reservation_status_date,2016-01-18,625,0.5235
5,Source 1 - Hotel Bookings Raw,reservation_status_date,2015-07-02,469,0.3928
6,Source 1 - Hotel Bookings Raw,reservation_status_date,2016-12-07,450,0.3769
7,Source 1 - Hotel Bookings Raw,reservation_status_date,2015-12-18,423,0.3543
8,Source 1 - Hotel Bookings Raw,reservation_status_date,2016-02-09,412,0.3451
9,Source 1 - Hotel Bookings Raw,reservation_status_date,2016-04-04,382,0.32
10,Source 1 - Hotel Bookings Raw,reservation_status_date,2017-01-24,343,0.2873
11,Source 1 - Hotel Bookings Raw,reservation_status_date,2016-11-21,340,0.2848

Frequency display - Source 2 - Hotel Reviews Raw - Hotel_Address

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews Raw,Hotel_Address,163 Marsh Wall Docklands Tower Hamlets London E14 9SJ United Kingdom,4789,0.9286
1,Source 2 - Hotel Reviews Raw,Hotel_Address,372 Strand Westminster Borough London WC2R 0JJ United Kingdom,4256,0.8252
2,Source 2 - Hotel Reviews Raw,Hotel_Address,Westminster Bridge Road Lambeth London SE1 7UT United Kingdom,4169,0.8084
3,Source 2 - Hotel Reviews Raw,Hotel_Address,Scarsdale Place Kensington Kensington and Chelsea London W8 5SY United Kingdom,3578,0.6938
4,Source 2 - Hotel Reviews Raw,Hotel_Address,7 Pepys Street City of London London EC3N 4AF United Kingdom,3212,0.6228
5,Source 2 - Hotel Reviews Raw,Hotel_Address,1 Inverness Terrace Westminster Borough London W2 3JP United Kingdom,2958,0.5735
6,Source 2 - Hotel Reviews Raw,Hotel_Address,Wrights Lane Kensington and Chelsea London W8 5SP United Kingdom,2768,0.5367
7,Source 2 - Hotel Reviews Raw,Hotel_Address,225 Edgware Road Westminster Borough London W2 1JU United Kingdom,2628,0.5096
8,Source 2 - Hotel Reviews Raw,Hotel_Address,4 18 Harrington Gardens Kensington and Chelsea London SW7 4LH United Kingdom,2565,0.4973
9,Source 2 - Hotel Reviews Raw,Hotel_Address,1 Waterview Drive Greenwich London SE10 0TW United Kingdom,2551,0.4946
10,Source 2 - Hotel Reviews Raw,Hotel_Address,27 Devonshire Terrace Westminster Borough London W2 3DP United Kingdom,2288,0.4436
11,Source 2 - Hotel Reviews Raw,Hotel_Address,Lakeside Way Brent London HA9 0BU United Kingdom,2227,0.4318

Frequency display - Source 2 - Hotel Reviews Raw - Review_Date

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews Raw,Review_Date,8/2/2017,2585,0.5012
1,Source 2 - Hotel Reviews Raw,Review_Date,9/15/2016,2308,0.4475
2,Source 2 - Hotel Reviews Raw,Review_Date,4/5/2017,2284,0.4429
3,Source 2 - Hotel Reviews Raw,Review_Date,8/30/2016,1963,0.3806
4,Source 2 - Hotel Reviews Raw,Review_Date,2/16/2016,1940,0.3762
5,Source 2 - Hotel Reviews Raw,Review_Date,7/5/2016,1904,0.3692
6,Source 2 - Hotel Reviews Raw,Review_Date,5/31/2016,1860,0.3606
7,Source 2 - Hotel Reviews Raw,Review_Date,12/5/2016,1803,0.3496
8,Source 2 - Hotel Reviews Raw,Review_Date,7/12/2016,1801,0.3492
9,Source 2 - Hotel Reviews Raw,Review_Date,8/2/2016,1783,0.3457
10,Source 2 - Hotel Reviews Raw,Review_Date,6/21/2016,1750,0.3393
11,Source 2 - Hotel Reviews Raw,Review_Date,5/3/2016,1732,0.3358

Frequency display - Source 2 - Hotel Reviews Raw - Hotel_Name

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews Raw,Hotel_Name,Britannia International Hotel Canary Wharf,4789,0.9286
1,Source 2 - Hotel Reviews Raw,Hotel_Name,Strand Palace Hotel,4256,0.8252
2,Source 2 - Hotel Reviews Raw,Hotel_Name,Park Plaza Westminster Bridge London,4169,0.8084
3,Source 2 - Hotel Reviews Raw,Hotel_Name,Copthorne Tara Hotel London Kensington,3578,0.6938
4,Source 2 - Hotel Reviews Raw,Hotel_Name,DoubleTree by Hilton Hotel London Tower of London,3212,0.6228
5,Source 2 - Hotel Reviews Raw,Hotel_Name,Grand Royale London Hyde Park,2958,0.5735
6,Source 2 - Hotel Reviews Raw,Hotel_Name,Holiday Inn London Kensington,2768,0.5367
7,Source 2 - Hotel Reviews Raw,Hotel_Name,Hilton London Metropole,2628,0.5096
8,Source 2 - Hotel Reviews Raw,Hotel_Name,Millennium Gloucester Hotel London,2565,0.4973
9,Source 2 - Hotel Reviews Raw,Hotel_Name,Intercontinental London The O2,2551,0.4946
10,Source 2 - Hotel Reviews Raw,Hotel_Name,Park Grand Paddington Court,2288,0.4436
11,Source 2 - Hotel Reviews Raw,Hotel_Name,Hilton London Wembley,2227,0.4318

Frequency display - Source 2 - Hotel Reviews Raw - Reviewer_Nationality

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,United Kingdom,245246,47.5524
1,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,United States of America,35437,6.8711
2,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,Australia,21686,4.2048
3,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,Ireland,14827,2.8749
4,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,United Arab Emirates,10235,1.9845
5,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,Saudi Arabia,8951,1.7356
6,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,Netherlands,8772,1.7009
7,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,Switzerland,8678,1.6826
8,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,Germany,7941,1.5397
9,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,Canada,7894,1.5306
10,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,France,7296,1.4147
11,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,Israel,6610,1.2817

Frequency display - Source 2 - Hotel Reviews Raw - Negative_Review

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews Raw,Negative_Review,No Negative,127890,24.7975
1,Source 2 - Hotel Reviews Raw,Negative_Review,Nothing,14295,2.7718
2,Source 2 - Hotel Reviews Raw,Negative_Review,Nothing,4236,0.8213
3,Source 2 - Hotel Reviews Raw,Negative_Review,nothing,2225,0.4314
4,Source 2 - Hotel Reviews Raw,Negative_Review,N A,1037,0.2011
5,Source 2 - Hotel Reviews Raw,Negative_Review,None,984,0.1908
6,Source 2 - Hotel Reviews Raw,Negative_Review,,849,0.1646
7,Source 2 - Hotel Reviews Raw,Negative_Review,N a,509,0.0987
8,Source 2 - Hotel Reviews Raw,Negative_Review,Breakfast,407,0.0789
9,Source 2 - Hotel Reviews Raw,Negative_Review,Small room,373,0.0723
10,Source 2 - Hotel Reviews Raw,Negative_Review,Location,368,0.0714
11,Source 2 - Hotel Reviews Raw,Negative_Review,Everything,326,0.0632

Frequency display - Source 2 - Hotel Reviews Raw - Positive_Review

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews Raw,Positive_Review,No Positive,35946,6.9698
1,Source 2 - Hotel Reviews Raw,Positive_Review,Location,9222,1.7881
2,Source 2 - Hotel Reviews Raw,Positive_Review,Everything,2284,0.4429
3,Source 2 - Hotel Reviews Raw,Positive_Review,location,1677,0.3252
4,Source 2 - Hotel Reviews Raw,Positive_Review,Nothing,1243,0.241
5,Source 2 - Hotel Reviews Raw,Positive_Review,The location,1126,0.2183
6,Source 2 - Hotel Reviews Raw,Positive_Review,Great location,1047,0.203
7,Source 2 - Hotel Reviews Raw,Positive_Review,Good location,927,0.1797
8,Source 2 - Hotel Reviews Raw,Positive_Review,Location,915,0.1774
9,Source 2 - Hotel Reviews Raw,Positive_Review,Everything,613,0.1189
10,Source 2 - Hotel Reviews Raw,Positive_Review,Breakfast,608,0.1179
11,Source 2 - Hotel Reviews Raw,Positive_Review,Friendly staff,515,0.0999

Frequency display - Source 2 - Hotel Reviews Raw - Tags

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Double Room ', ' Stayed 1 night ', ' Submitted from a mobile device ']",5101,0.9891
1,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Standard Double Room ', ' Stayed 1 night ', ' Submitted from a mobile device ']",4931,0.9561
2,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Superior Double Room ', ' Stayed 1 night ', ' Submitted from a mobile device ']",4366,0.8466
3,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Deluxe Double Room ', ' Stayed 1 night ', ' Submitted from a mobile device ']",3991,0.7738
4,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Double Room ', ' Stayed 2 nights ', ' Submitted from a mobile device ']",3291,0.6381
5,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Superior Double Room ', ' Stayed 2 nights ', ' Submitted from a mobile device ']",3102,0.6015
6,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Standard Double Room ', ' Stayed 2 nights ', ' Submitted from a mobile device ']",2947,0.5714
7,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Double Room ', ' Stayed 1 night ']",2906,0.5635
8,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Standard Double Room ', ' Stayed 1 night ']",2620,0.508
9,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Deluxe Double Room ', ' Stayed 2 nights ', ' Submitted from a mobile device ']",2362,0.458
10,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Superior Double Room ', ' Stayed 1 night ']",2215,0.4295
11,Source 2 - Hotel Reviews Raw,Tags,"[' Leisure trip ', ' Couple ', ' Double Room ', ' Stayed 2 nights ']",2175,0.4217

Frequency display - Source 2 - Hotel Reviews Raw - days_since_review

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews Raw,days_since_review,1 days,2585,0.5012
1,Source 2 - Hotel Reviews Raw,days_since_review,322 day,2308,0.4475
2,Source 2 - Hotel Reviews Raw,days_since_review,120 day,2284,0.4429
3,Source 2 - Hotel Reviews Raw,days_since_review,338 day,1963,0.3806
4,Source 2 - Hotel Reviews Raw,days_since_review,534 day,1940,0.3762
5,Source 2 - Hotel Reviews Raw,days_since_review,394 day,1904,0.3692
6,Source 2 - Hotel Reviews Raw,days_since_review,429 day,1860,0.3606
7,Source 2 - Hotel Reviews Raw,days_since_review,241 day,1803,0.3496
8,Source 2 - Hotel Reviews Raw,days_since_review,387 day,1801,0.3492
9,Source 2 - Hotel Reviews Raw,days_since_review,366 day,1783,0.3457
10,Source 2 - Hotel Reviews Raw,days_since_review,408 day,1750,0.3393
11,Source 2 - Hotel Reviews Raw,days_since_review,457 day,1732,0.3358

Unusual/missing values report - Source 1 - Hotel Bookings Raw

,dataset,column,missing_count,unusual_value_count,unusual_examples
0,Source 1 - Hotel Bookings Raw,children,4,0,
1,Source 1 - Hotel Bookings Raw,country,488,0,
2,Source 1 - Hotel Bookings Raw,agent,16340,0,
3,Source 1 - Hotel Bookings Raw,company,112593,0,

Unusual/missing values report - Source 2 - Hotel Reviews Raw

,dataset,column,missing_count,unusual_value_count,unusual_examples
0,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,0,523,
1,Source 2 - Hotel Reviews Raw,Negative_Review,0,130380,"No Negative, , None, none, NA"
2,Source 2 - Hotel Reviews Raw,Positive_Review,0,36179,"No Positive, None, , NA, none"
3,Source 2 - Hotel Reviews Raw,lat,3268,0,
4,Source 2 - Hotel Reviews Raw,lng,3268,0,

Datatype consistency report - Source 1 - Hotel Bookings Raw

,dataset,column,dtype,numeric_parse_pct_if_object,datetime_parse_pct_if_object,recommendation
0,Source 1 - Hotel Bookings Raw,hotel,object,0.0,0.0,ok
1,Source 1 - Hotel Bookings Raw,is_canceled,int64,NaN,NaN,ok
2,Source 1 - Hotel Bookings Raw,lead_time,int64,NaN,NaN,ok
3,Source 1 - Hotel Bookings Raw,arrival_date_year,int64,NaN,NaN,ok
4,Source 1 - Hotel Bookings Raw,arrival_date_month,object,0.0,0.0,ok
5,Source 1 - Hotel Bookings Raw,arrival_date_week_number,int64,NaN,NaN,ok
6,Source 1 - Hotel Bookings Raw,arrival_date_day_of_month,int64,NaN,NaN,ok
7,Source 1 - Hotel Bookings Raw,stays_in_weekend_nights,int64,NaN,NaN,ok
8,Source 1 - Hotel Bookings Raw,stays_in_week_nights,int64,NaN,NaN,ok
9,Source 1 - Hotel Bookings Raw,adults,int64,NaN,NaN,ok
10,Source 1 - Hotel Bookings Raw,children,float64,NaN,NaN,ok
11,Source 1 - Hotel Bookings Raw,babies,int64,NaN,NaN,ok
12,Source 1 - Hotel Bookings Raw,meal,object,0.0,0.0,ok
13,Source 1 - Hotel Bookings Raw,country,object,0.0,0.0,ok
14,Source 1 - Hotel Bookings Raw,market_segment,object,0.0,0.0,ok
15,Source 1 - Hotel Bookings Raw,distribution_channel,object,0.0,0.0,ok
16,Source 1 - Hotel Bookings Raw,is_repeated_guest,int64,NaN,NaN,ok
17,Source 1 - Hotel Bookings Raw,previous_cancellations,int64,NaN,NaN,ok
18,Source 1 - Hotel Bookings Raw,previous_bookings_not_canceled,int64,NaN,NaN,ok
19,Source 1 - Hotel Bookings Raw,reserved_room_type,object,0.0,0.0,ok
20,Source 1 - Hotel Bookings Raw,assigned_room_type,object,0.0,0.0,ok
21,Source 1 - Hotel Bookings Raw,booking_changes,int64,NaN,NaN,ok
22,Source 1 - Hotel Bookings Raw,deposit_type,object,0.0,0.0,ok
23,Source 1 - Hotel Bookings Raw,agent,float64,NaN,NaN,ok
24,Source 1 - Hotel Bookings Raw,company,float64,NaN,NaN,ok
25,Source 1 - Hotel Bookings Raw,days_in_waiting_list,int64,NaN,NaN,ok
26,Source 1 - Hotel Bookings Raw,customer_type,object,0.0,0.0,ok
27,Source 1 - Hotel Bookings Raw,adr,float64,NaN,NaN,ok
28,Source 1 - Hotel Bookings Raw,required_car_parking_spaces,int64,NaN,NaN,ok
29,Source 1 - Hotel Bookings Raw,total_of_special_requests,int64,NaN,NaN,ok
30,Source 1 - Hotel Bookings Raw,reservation_status,object,0.0,0.0,ok
31,Source 1 - Hotel Bookings Raw,reservation_status_date,object,0.0,100.0,review type conversion

Datatype consistency report - Source 2 - Hotel Reviews Raw

,dataset,column,dtype,numeric_parse_pct_if_object,datetime_parse_pct_if_object,recommendation
0,Source 2 - Hotel Reviews Raw,Hotel_Address,object,0.0,0.0,ok
1,Source 2 - Hotel Reviews Raw,Additional_Number_of_Scoring,int64,NaN,NaN,ok
2,Source 2 - Hotel Reviews Raw,Review_Date,object,0.0,100.0,review type conversion
3,Source 2 - Hotel Reviews Raw,Average_Score,float64,NaN,NaN,ok
4,Source 2 - Hotel Reviews Raw,Hotel_Name,object,0.0,0.0,ok
5,Source 2 - Hotel Reviews Raw,Reviewer_Nationality,object,0.0,0.0,ok
6,Source 2 - Hotel Reviews Raw,Negative_Review,object,0.0,0.0,ok
7,Source 2 - Hotel Reviews Raw,Review_Total_Negative_Word_Counts,int64,NaN,NaN,ok
8,Source 2 - Hotel Reviews Raw,Total_Number_of_Reviews,int64,NaN,NaN,ok
9,Source 2 - Hotel Reviews Raw,Positive_Review,object,0.0,0.0,ok
10,Source 2 - Hotel Reviews Raw,Review_Total_Positive_Word_Counts,int64,NaN,NaN,ok
11,Source 2 - Hotel Reviews Raw,Total_Number_of_Reviews_Reviewer_Has_Given,int64,NaN,NaN,ok
12,Source 2 - Hotel Reviews Raw,Reviewer_Score,float64,NaN,NaN,ok
13,Source 2 - Hotel Reviews Raw,Tags,object,0.0,0.0,ok
14,Source 2 - Hotel Reviews Raw,days_since_review,object,0.0,0.0,ok
15,Source 2 - Hotel Reviews Raw,lat,float64,NaN,NaN,ok
16,Source 2 - Hotel Reviews Raw,lng,float64,NaN,NaN,ok

Distribution report - Source 1 - Hotel Bookings Raw

,dataset,column,count,mean,std,min,25%,50%,75%,max
0,Source 1 - Hotel Bookings Raw,is_canceled,119390.0,0.370416,0.482918,0.0,0.0,0.0,1.0,1.0
1,Source 1 - Hotel Bookings Raw,lead_time,119390.0,104.011416,106.863097,0.0,18.0,69.0,160.0,737.0
2,Source 1 - Hotel Bookings Raw,arrival_date_year,119390.0,2016.156554,0.707476,2015.0,2016.0,2016.0,2017.0,2017.0
3,Source 1 - Hotel Bookings Raw,arrival_date_week_number,119390.0,27.165173,13.605138,1.0,16.0,28.0,38.0,53.0
4,Source 1 - Hotel Bookings Raw,arrival_date_day_of_month,119390.0,15.798241,8.780829,1.0,8.0,16.0,23.0,31.0
5,Source 1 - Hotel Bookings Raw,stays_in_weekend_nights,119390.0,0.927599,0.998613,0.0,0.0,1.0,2.0,19.0
6,Source 1 - Hotel Bookings Raw,stays_in_week_nights,119390.0,2.500302,1.908286,0.0,1.0,2.0,3.0,50.0
7,Source 1 - Hotel Bookings Raw,adults,119390.0,1.856403,0.579261,0.0,2.0,2.0,2.0,55.0
8,Source 1 - Hotel Bookings Raw,children,119386.0,0.103890,0.398561,0.0,0.0,0.0,0.0,10.0
9,Source 1 - Hotel Bookings Raw,babies,119390.0,0.007949,0.097436,0.0,0.0,0.0,0.0,10.0
10,Source 1 - Hotel Bookings Raw,is_repeated_guest,119390.0,0.031912,0.175767,0.0,0.0,0.0,0.0,1.0
11,Source 1 - Hotel Bookings Raw,previous_cancellations,119390.0,0.087118,0.844336,0.0,0.0,0.0,0.0,26.0

Distribution report - Source 2 - Hotel Reviews Raw

,dataset,column,count,mean,std,min,25%,50%,75%,max
0,Source 2 - Hotel Reviews Raw,Additional_Number_of_Scoring,515738.0,498.081836,500.538467,1.000000,169.000000,341.000000,660.000000,2682.000000
1,Source 2 - Hotel Reviews Raw,Average_Score,515738.0,8.397487,0.548048,5.200000,8.100000,8.400000,8.800000,9.800000
2,Source 2 - Hotel Reviews Raw,Review_Total_Negative_Word_Counts,515738.0,18.539450,29.690831,0.000000,2.000000,9.000000,23.000000,408.000000
3,Source 2 - Hotel Reviews Raw,Total_Number_of_Reviews,515738.0,2743.743944,2317.464868,43.000000,1161.000000,2134.000000,3613.000000,16670.000000
4,Source 2 - Hotel Reviews Raw,Review_Total_Positive_Word_Counts,515738.0,17.776458,21.804185,0.000000,5.000000,11.000000,22.000000,395.000000
5,Source 2 - Hotel Reviews Raw,Total_Number_of_Reviews_Reviewer_Has_Given,515738.0,7.166001,11.040228,1.000000,1.000000,3.000000,8.000000,355.000000
6,Source 2 - Hotel Reviews Raw,Reviewer_Score,515738.0,8.395077,1.637856,2.500000,7.500000,8.800000,9.600000,10.000000
7,Source 2 - Hotel Reviews Raw,lat,512470.0,49.442439,3.466325,41.328376,48.214662,51.499981,51.516288,52.400181
8,Source 2 - Hotel Reviews Raw,lng,512470.0,2.823803,4.579425,-0.369758,-0.143372,0.010607,4.834443,16.429233

## **Load**

### Dimensions and Lake Preparations

In [ ]:
def build_dimension_from_values(values, id_col, value_col, unknown_value="Unknown"):
    cleaned = pd.Series(values, dtype="string").fillna(unknown_value).astype(str).str.strip()
    cleaned = cleaned.replace(UNUSUAL_VALUES, unknown_value)
    unique_values = sorted(set([x if x else unknown_value for x in cleaned.tolist()]))
    if unknown_value not in unique_values:
        unique_values.insert(0, unknown_value)
    else:
        unique_values = [unknown_value] + [x for x in unique_values if x != unknown_value]
    dim = pd.DataFrame({value_col: unique_values})
    dim[id_col] = range(1, len(dim) + 1)
    return dim[[id_col, value_col]]


def build_date_dimension(*date_series_list):
    all_dates = []
    for series in date_series_list:
        if series is None:
            continue
        all_dates.extend(pd.to_datetime(series, errors="coerce").fillna(DATE_FILL_VALUE).tolist())
    dates = pd.Series(all_dates).dropna().drop_duplicates().sort_values()
    if dates.empty:
        dates = pd.Series([DATE_FILL_VALUE])
    if DATE_FILL_VALUE not in list(dates):
        dates = pd.concat([pd.Series([DATE_FILL_VALUE]), dates]).drop_duplicates().sort_values()
    dim = pd.DataFrame({"date": pd.to_datetime(dates)})
    dim["date_id"] = range(1, len(dim) + 1)
    dim["year"] = dim["date"].dt.year.astype(int)
    dim["month"] = dim["date"].dt.month.astype(int)
    dim["day"] = dim["date"].dt.day.astype(int)
    dim["quarter"] = dim["date"].dt.quarter.astype(int)
    dim["month_name"] = dim["date"].dt.month_name()
    dim["year_month"] = dim["date"].dt.to_period("M").astype(str)
    return dim[["date_id", "date", "year", "month", "day", "quarter", "month_name", "year_month"]]


def make_review_hotel_dimension(reviews):
    cols = ["hotel_name", "hotel_address", "lat", "lng", "average_score"]
    for col in cols:
        if col not in reviews.columns:
            reviews[col] = "Unknown" if col in ["hotel_name", "hotel_address"] else 0
    dim = reviews[cols].drop_duplicates(subset=["hotel_name", "hotel_address"]).reset_index(drop=True).copy()
    unknown_row = pd.DataFrame([{"hotel_name": "Unknown", "hotel_address": "Unknown", "lat": 0, "lng": 0, "average_score": 0}])
    dim = pd.concat([unknown_row, dim], ignore_index=True).drop_duplicates(subset=["hotel_name", "hotel_address"], keep="first")
    dim["review_hotel_id"] = range(1, len(dim) + 1)
    return dim[["review_hotel_id", "hotel_name", "hotel_address", "lat", "lng", "average_score"]]


def add_outlier_columns(df, dataset_name, exclude_cols=None):
    report, mask_df = outlier_report_iqr(df, dataset_name, exclude_cols=exclude_cols)
    out = df.copy()
    out["outlier_count"] = mask_df.sum(axis=1).astype(int) if not mask_df.empty else 0
    out["outlier_label"] = np.where(out["outlier_count"] > 0, "Has Outlier", "No Outlier")
    return out, report


def validate_table(df, table_name, primary_key=None, expected_not_null=None, range_rules=None):
    rows = []
    if primary_key:
        rows.append({
            "table": table_name,
            "rule_type": "uniqueness check",
            "rule": f"{primary_key} must be unique",
            "status": "PASS" if primary_key in df.columns and df[primary_key].is_unique else "FAIL",
            "invalid_count": 0 if primary_key in df.columns and df[primary_key].is_unique else None,
        })
        rows.append({
            "table": table_name,
            "rule_type": "null check",
            "rule": f"{primary_key} must not be null",
            "status": "PASS" if primary_key in df.columns and df[primary_key].notna().all() else "FAIL",
            "invalid_count": int(df[primary_key].isna().sum()) if primary_key in df.columns else None,
        })
    expected_not_null = expected_not_null or []
    for col in expected_not_null:
        if col in df.columns:
            invalid = int(df[col].isna().sum())
            rows.append({"table": table_name, "rule_type": "null check", "rule": f"{col} must not be null", "status": "PASS" if invalid == 0 else "FAIL", "invalid_count": invalid})
    range_rules = range_rules or {}
    for col, rule in range_rules.items():
        if col not in df.columns:
            rows.append({"table": table_name, "rule_type": "range check", "rule": f"{col} {rule}", "status": "MISSING_COLUMN", "invalid_count": None})
            continue
        values = pd.to_numeric(df[col], errors="coerce")
        invalid_mask = pd.Series(False, index=df.index)
        if "min" in rule:
            invalid_mask = invalid_mask | (values < rule["min"])
        if "max" in rule:
            invalid_mask = invalid_mask | (values > rule["max"])
        invalid = int(invalid_mask.fillna(False).sum())
        rows.append({"table": table_name, "rule_type": "range check", "rule": f"{col} {rule}", "status": "PASS" if invalid == 0 else "FAIL", "invalid_count": invalid})
    return pd.DataFrame(rows)


def validate_referential_integrity(child_df, child_col, parent_df, parent_col, relationship_name):
    child_values = child_df[child_col].dropna().astype(str) if child_col in child_df.columns else pd.Series(dtype=str)
    parent_values = set(parent_df[parent_col].dropna().astype(str)) if parent_col in parent_df.columns else set()
    invalid = int((~child_values.isin(parent_values)).sum()) if len(child_values) else 0
    return {
        "relationship": relationship_name,
        "rule_type": "referential integrity",
        "child_column": child_col,
        "parent_column": parent_col,
        "status": "PASS" if invalid == 0 else "FAIL",
        "invalid_count": invalid,
    }


def validation_suite(tables, prefix=""):
    start = time.time()
    p = f"{prefix}_" if prefix else ""
    validations = []
    key_map = {
        "dim_date": "date_id",
        "dim_booking_hotel_type": "booking_hotel_type_id",
        "dim_country": "country_id",
        "dim_meal": "meal_id",
        "dim_market_segment": "market_segment_id",
        "dim_distribution_channel": "distribution_channel_id",
        "dim_customer_type": "customer_type_id",
        "dim_deposit_type": "deposit_type_id",
        "dim_room_type": "room_type_id",
        "dim_review_hotel": "review_hotel_id",
        "fact_bookings": "booking_id",
        "fact_reviews": "review_id",
        "fact_hotel_monthly_performance": "performance_id",
    }
    range_rules = {
        "fact_bookings": {"adr": {"min": 0}, "total_guests": {"min": 0}, "total_nights": {"min": 0}},
        "fact_reviews": {"reviewer_score": {"min": 0, "max": 10}, "average_score": {"min": 0, "max": 10}},
        "fact_hotel_monthly_performance": {"booking_count": {"min": 0}, "review_count": {"min": 0}},
    }
    for table_name, pk in key_map.items():
        if table_name in tables:
            id_columns = [col for col in tables[table_name].columns if col.endswith("_id") or col in ["booking_id", "review_id", "performance_id"]]
            validations.append(validate_table(tables[table_name], p + table_name, primary_key=pk, expected_not_null=id_columns, range_rules=range_rules.get(table_name, {})))
    validation_df = pd.concat(validations, ignore_index=True) if validations else pd.DataFrame()

    fk_rows = []
    if {"fact_bookings", "dim_date"}.issubset(tables):
        fk_rows.extend([
            validate_referential_integrity(tables["fact_bookings"], "arrival_date_id", tables["dim_date"], "date_id", f"{p}fact_bookings.arrival_date_id -> {p}dim_date.date_id"),
            validate_referential_integrity(tables["fact_bookings"], "reservation_status_date_id", tables["dim_date"], "date_id", f"{p}fact_bookings.reservation_status_date_id -> {p}dim_date.date_id"),
        ])
    if {"fact_bookings", "dim_country"}.issubset(tables):
        fk_rows.append(validate_referential_integrity(tables["fact_bookings"], "country_id", tables["dim_country"], "country_id", f"{p}fact_bookings.country_id -> {p}dim_country.country_id"))
    for dim_name, fk_col, pk_col in [
        ("dim_booking_hotel_type", "booking_hotel_type_id", "booking_hotel_type_id"),
        ("dim_meal", "meal_id", "meal_id"),
        ("dim_market_segment", "market_segment_id", "market_segment_id"),
        ("dim_distribution_channel", "distribution_channel_id", "distribution_channel_id"),
        ("dim_customer_type", "customer_type_id", "customer_type_id"),
        ("dim_deposit_type", "deposit_type_id", "deposit_type_id"),
        ("dim_room_type", "reserved_room_type_id", "room_type_id"),
        ("dim_room_type", "assigned_room_type_id", "room_type_id"),
    ]:
        if {"fact_bookings", dim_name}.issubset(tables):
            fk_rows.append(validate_referential_integrity(tables["fact_bookings"], fk_col, tables[dim_name], pk_col, f"{p}fact_bookings.{fk_col} -> {p}{dim_name}.{pk_col}"))
    if {"fact_reviews", "dim_date"}.issubset(tables):
        fk_rows.append(validate_referential_integrity(tables["fact_reviews"], "review_date_id", tables["dim_date"], "date_id", f"{p}fact_reviews.review_date_id -> {p}dim_date.date_id"))
    if {"fact_reviews", "dim_country"}.issubset(tables):
        fk_rows.append(validate_referential_integrity(tables["fact_reviews"], "reviewer_country_id", tables["dim_country"], "country_id", f"{p}fact_reviews.reviewer_country_id -> {p}dim_country.country_id"))
    if {"fact_reviews", "dim_review_hotel"}.issubset(tables):
        fk_rows.append(validate_referential_integrity(tables["fact_reviews"], "review_hotel_id", tables["dim_review_hotel"], "review_hotel_id", f"{p}fact_reviews.review_hotel_id -> {p}dim_review_hotel.review_hotel_id"))
    if {"fact_hotel_monthly_performance", "dim_date"}.issubset(tables):
        fk_rows.append(validate_referential_integrity(tables["fact_hotel_monthly_performance"], "month_start_date_id", tables["dim_date"], "date_id", f"{p}fact_hotel_monthly_performance.month_start_date_id -> {p}dim_date.date_id"))

    fk_df = pd.DataFrame(fk_rows)
    print("Validation rules: uniqueness, null, range, datatype consistency, referential integrity, data distribution")
    display(validation_df)
    display(fk_df)
    log_step("Validation Suite", f"{prefix} warehouse validation complete", start)
    return validation_df, fk_df


def get_dtype_map(df):
    dtype_map = {}
    for col in df.columns:
        if col.endswith("_id") or col in ["booking_id", "review_id", "performance_id"]:
            dtype_map[col] = BigInteger()
        elif pd.api.types.is_integer_dtype(df[col]):
            dtype_map[col] = BigInteger()
        elif pd.api.types.is_float_dtype(df[col]):
            dtype_map[col] = Float()
        elif pd.api.types.is_datetime64_any_dtype(df[col]):
            dtype_map[col] = DateTime()
        elif col in ["hotel_name", "hotel_address", "positive_review", "negative_review", "tags"]:
            dtype_map[col] = Text()
        elif pd.api.types.is_object_dtype(df[col]) or str(df[col].dtype).startswith("string"):
            dtype_map[col] = String(255)
    return dtype_map


def get_engine_or_sqlite(database_url, fallback_sqlite_path):
    if is_placeholder(database_url):
        print(f"Warehouse URL not configured. Using local SQLite fallback: {fallback_sqlite_path}")
        return create_engine(f"sqlite:///{fallback_sqlite_path}"), "sqlite_fallback"
    return create_engine(database_url), "external_warehouse"


def read_sql_df(sql, engine):
    with engine.connect() as conn:
        return pd.read_sql_query(text(sql), con=conn)


def execute_ddl_safely(engine, sql, label):
    try:
        with engine.begin() as conn:
            conn.execute(text(sql))
        process_log.append({
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "step": "Warehouse DDL",
            "status": "SUCCESS",
            "detail": label,
            "rows": None,
            "columns": None,
            "execution_seconds": None,
        })
        print(f"OK: {label}")
    except Exception as exc:
        process_log.append({
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "step": "Warehouse DDL",
            "status": "WARNING",
            "detail": f"{label}: {exc}",
            "rows": None,
            "columns": None,
            "execution_seconds": None,
        })
        print(f"WARNING: {label}: {exc}")


def load_tables_to_warehouse(tables, engine, prefix, create_constraints=True, chunksize=5000):
    start = time.time()
    table_order = [
        "dim_date", "dim_booking_hotel_type", "dim_country", "dim_meal", "dim_market_segment",
        "dim_distribution_channel", "dim_customer_type", "dim_deposit_type", "dim_room_type", "dim_review_hotel",
        "fact_bookings", "fact_reviews", "fact_hotel_monthly_performance",
        "metric_booking_by_segment", "metric_review_by_hotel", "metric_monthly_kpi"
    ]
    available_order = [t for t in table_order if t in tables]
    dialect = engine.dialect.name
    physical_names = {name: f"{prefix}_{name}" for name in available_order}

    # Drop children first to avoid foreign-key dependency issues.
    if dialect == "mysql":
        execute_ddl_safely(engine, "SET FOREIGN_KEY_CHECKS=0", "disable foreign key checks before replace")
    for name in reversed(available_order):
        execute_ddl_safely(
            engine,
            f"DROP TABLE IF EXISTS {physical_names[name]}",
            f"drop {physical_names[name]} if exists",
        )
    if dialect == "mysql":
        execute_ddl_safely(engine, "SET FOREIGN_KEY_CHECKS=1", "enable foreign key checks after drop")

    for name in available_order:
        df = safe_for_sql(tables[name])
        df.to_sql(
            physical_names[name],
            con=engine,
            if_exists="replace",
            index=False,
            chunksize=chunksize,
            dtype=get_dtype_map(df),
        )
        print(f"Loaded {physical_names[name]}: {df.shape[0]:,} rows, {df.shape[1]:,} columns")

    # Add physical PK/FK constraints for MySQL-compatible and PostgreSQL warehouses.
    if create_constraints and dialect in ["mysql", "postgresql"]:
        pk_map = {
            "dim_date": "date_id",
            "dim_booking_hotel_type": "booking_hotel_type_id",
            "dim_country": "country_id",
            "dim_meal": "meal_id",
            "dim_market_segment": "market_segment_id",
            "dim_distribution_channel": "distribution_channel_id",
            "dim_customer_type": "customer_type_id",
            "dim_deposit_type": "deposit_type_id",
            "dim_room_type": "room_type_id",
            "dim_review_hotel": "review_hotel_id",
            "fact_bookings": "booking_id",
            "fact_reviews": "review_id",
            "fact_hotel_monthly_performance": "performance_id",
        }
        for name, pk in pk_map.items():
            if name not in physical_names:
                continue
            table_name = physical_names[name]
            if dialect == "postgresql":
                execute_ddl_safely(
                    engine,
                    f"ALTER TABLE {table_name} ALTER COLUMN {pk} SET NOT NULL",
                    f"set {table_name}.{pk} NOT NULL",
                )
            else:
                execute_ddl_safely(
                    engine,
                    f"ALTER TABLE {table_name} MODIFY {pk} BIGINT NOT NULL",
                    f"set {table_name}.{pk} NOT NULL",
                )
            execute_ddl_safely(
                engine,
                f"ALTER TABLE {table_name} ADD PRIMARY KEY ({pk})",
                f"primary key for {table_name}.{pk}",
            )

        fk_map = [
            ("fact_bookings", "arrival_date_id", "dim_date", "date_id"),
            ("fact_bookings", "reservation_status_date_id", "dim_date", "date_id"),
            ("fact_bookings", "country_id", "dim_country", "country_id"),
            ("fact_bookings", "booking_hotel_type_id", "dim_booking_hotel_type", "booking_hotel_type_id"),
            ("fact_bookings", "meal_id", "dim_meal", "meal_id"),
            ("fact_bookings", "market_segment_id", "dim_market_segment", "market_segment_id"),
            ("fact_bookings", "distribution_channel_id", "dim_distribution_channel", "distribution_channel_id"),
            ("fact_bookings", "customer_type_id", "dim_customer_type", "customer_type_id"),
            ("fact_bookings", "deposit_type_id", "dim_deposit_type", "deposit_type_id"),
            ("fact_bookings", "reserved_room_type_id", "dim_room_type", "room_type_id"),
            ("fact_bookings", "assigned_room_type_id", "dim_room_type", "room_type_id"),
            ("fact_reviews", "review_date_id", "dim_date", "date_id"),
            ("fact_reviews", "reviewer_country_id", "dim_country", "country_id"),
            ("fact_reviews", "review_hotel_id", "dim_review_hotel", "review_hotel_id"),
            ("fact_hotel_monthly_performance", "month_start_date_id", "dim_date", "date_id"),
        ]
        for child, child_col, parent, parent_col in fk_map:
            if child in physical_names and parent in physical_names:
                idx = f"idx_{prefix}_{child}_{child_col}"[:60]
                fk = f"fk_{prefix}_{child}_{child_col}"[:60]
                execute_ddl_safely(
                    engine,
                    f"CREATE INDEX {idx} ON {physical_names[child]} ({child_col})",
                    f"index {idx}",
                )
                execute_ddl_safely(
                    engine,
                    f"ALTER TABLE {physical_names[child]} ADD CONSTRAINT {fk} "
                    f"FOREIGN KEY ({child_col}) REFERENCES {physical_names[parent]}({parent_col})",
                    f"foreign key {fk}",
                )

    log_step(
        "Load Warehouse",
        f"Loaded {len(available_order)} tables with prefix {prefix} into {engine.dialect.name}",
        start,
    )
    return physical_names

def build_analytic_queries(prefix):
    p = prefix
    return {
        "01_monthly_booking_volume": f"""
            SELECT d.year_month, COUNT(*) AS booking_count,
                   ROUND(CAST(AVG(fb.adr) AS NUMERIC), 2) AS avg_adr
            FROM {p}_fact_bookings fb
            JOIN {p}_dim_date d ON fb.arrival_date_id = d.date_id
            GROUP BY d.year_month
            ORDER BY d.year_month
            LIMIT 24
        """,
        "02_cancellation_rate_by_hotel_type": f"""
            SELECT ht.hotel_type, COUNT(*) AS booking_count,
                   ROUND(CAST(AVG(fb.is_canceled) * 100 AS NUMERIC), 2) AS cancellation_rate_pct
            FROM {p}_fact_bookings fb
            JOIN {p}_dim_booking_hotel_type ht ON fb.booking_hotel_type_id = ht.booking_hotel_type_id
            GROUP BY ht.hotel_type
            ORDER BY cancellation_rate_pct DESC
        """,
        "03_average_adr_by_market_segment": f"""
            SELECT ms.market_segment, COUNT(*) AS booking_count,
                   ROUND(CAST(AVG(fb.adr) AS NUMERIC), 2) AS avg_adr
            FROM {p}_fact_bookings fb
            JOIN {p}_dim_market_segment ms ON fb.market_segment_id = ms.market_segment_id
            GROUP BY ms.market_segment
            ORDER BY avg_adr DESC
            LIMIT 10
        """,
        "04_revenue_proxy_by_customer_type": f"""
            SELECT ct.customer_type, COUNT(*) AS booking_count,
                   ROUND(CAST(SUM(fb.adr * fb.total_nights) AS NUMERIC), 2) AS revenue_proxy
            FROM {p}_fact_bookings fb
            JOIN {p}_dim_customer_type ct ON fb.customer_type_id = ct.customer_type_id
            GROUP BY ct.customer_type
            ORDER BY revenue_proxy DESC
        """,
        "05_room_change_rate": f"""
            SELECT rr.room_type AS reserved_room_type, COUNT(*) AS booking_count,
                   ROUND(CAST(AVG(fb.room_changed) * 100 AS NUMERIC), 2) AS room_change_rate_pct
            FROM {p}_fact_bookings fb
            JOIN {p}_dim_room_type rr ON fb.reserved_room_type_id = rr.room_type_id
            GROUP BY rr.room_type
            ORDER BY room_change_rate_pct DESC
            LIMIT 10
        """,
        "06_review_score_by_reviewer_country": f"""
            SELECT c.country_name AS reviewer_country, COUNT(*) AS review_count,
                   ROUND(CAST(AVG(fr.reviewer_score) AS NUMERIC), 2) AS avg_reviewer_score
            FROM {p}_fact_reviews fr
            JOIN {p}_dim_country c ON fr.reviewer_country_id = c.country_id
            GROUP BY c.country_name
            HAVING COUNT(*) >= 20
            ORDER BY avg_reviewer_score DESC
            LIMIT 15
        """,
        "07_top_reviewed_hotels": f"""
            SELECT rh.hotel_name, COUNT(*) AS review_count,
                   ROUND(CAST(AVG(fr.reviewer_score) AS NUMERIC), 2) AS avg_reviewer_score
            FROM {p}_fact_reviews fr
            JOIN {p}_dim_review_hotel rh ON fr.review_hotel_id = rh.review_hotel_id
            GROUP BY rh.hotel_name
            ORDER BY review_count DESC
            LIMIT 15
        """,
        "08_review_word_balance_by_hotel": f"""
            SELECT rh.hotel_name, COUNT(*) AS review_count,
                   ROUND(CAST(AVG(fr.positive_review_word_count) AS NUMERIC), 2) AS avg_positive_words,
                   ROUND(CAST(AVG(fr.negative_review_word_count) AS NUMERIC), 2) AS avg_negative_words,
                   ROUND(CAST(AVG(fr.sentiment_word_balance) AS NUMERIC), 2) AS avg_sentiment_word_balance
            FROM {p}_fact_reviews fr
            JOIN {p}_dim_review_hotel rh ON fr.review_hotel_id = rh.review_hotel_id
            GROUP BY rh.hotel_name
            HAVING COUNT(*) >= 20
            ORDER BY avg_sentiment_word_balance DESC
            LIMIT 15
        """,
        "09_merged_monthly_performance": f"""
            SELECT d.year_month, fp.booking_count, fp.review_count,
                   ROUND(CAST(fp.cancellation_rate * 100 AS NUMERIC), 2) AS cancellation_rate_pct,
                   ROUND(CAST(fp.avg_adr AS NUMERIC), 2) AS avg_adr,
                   ROUND(CAST(fp.avg_reviewer_score AS NUMERIC), 2) AS avg_reviewer_score
            FROM {p}_fact_hotel_monthly_performance fp
            JOIN {p}_dim_date d ON fp.month_start_date_id = d.date_id
            ORDER BY d.year_month
            LIMIT 24
        """,
        "10_special_requests_vs_cancellation": f"""
            SELECT fb.total_of_special_requests, COUNT(*) AS booking_count,
                   ROUND(CAST(AVG(fb.is_canceled) * 100 AS NUMERIC), 2) AS cancellation_rate_pct,
                   ROUND(CAST(AVG(fb.adr) AS NUMERIC), 2) AS avg_adr
            FROM {p}_fact_bookings fb
            GROUP BY fb.total_of_special_requests
            ORDER BY fb.total_of_special_requests
        """,
    }

def run_analytic_queries(engine, prefix):
    start = time.time()
    results = {}
    queries = build_analytic_queries(prefix)
    for name, sql in queries.items():
        print(f"Analytic SQL Query - {name}")
        try:
            result = read_sql_df(sql, engine)
            results[name] = result
            display(result)
        except Exception as exc:
            results[name] = pd.DataFrame({"error": [str(exc)]})
            print(f"Query failed: {exc}")
    log_step("Analytic SQL Queries", f"Executed {len(queries)} analytic SQL queries for prefix {prefix}", start)
    return results

### Lake Creation

In [ ]:

def create_sqlite_lake_engine(lake_url="sqlite:////content/hotel_elt_lake.db"):
    return create_engine(lake_url, future=True)


def register_sqlite_udfs(engine):
    raw = engine.raw_connection()

    def parse_mdy_date(value):
        try:
            parsed = pd.to_datetime(value, errors="coerce")
            if pd.isna(parsed):
                return "1900-01-01"
            return parsed.strftime("%Y-%m-%d")
        except Exception:
            return "1900-01-01"

    raw.create_function("PARSE_MDY_DATE", 1, parse_mdy_date)
    raw.commit()
    raw.close()


def exec_sql(engine, sql, label=None):
    start = time.time()
    with engine.begin() as conn:
        for statement in [s.strip() for s in sql.split(";") if s.strip()]:
            conn.execute(text(statement))
    if label:
        log_step("SQL Transform", label, start)
        print(f"SQL executed: {label}")


def read_lake_table(engine, table_name):
    return read_sql_df(f'SELECT * FROM "{table_name}"', engine)


def lake_table_exists(engine, table_name):
    query = """
    SELECT name
    FROM sqlite_master
    WHERE type = 'table' AND name = :table_name
    """
    with engine.connect() as conn:
        return conn.execute(text(query), {"table_name": table_name}).fetchone() is not None


def show_lake_tables(engine):
    with engine.connect() as conn:
        tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name", conn)
    display(tables)
    return tables


def load_raw_to_lake(bookings_raw, reviews_raw, lake_engine):
    start = time.time()
    bookings_std = standardize_column_names(bookings_raw)
    reviews_std = standardize_column_names(reviews_raw)
    bookings_std.to_sql("lake_raw_hotel_bookings", con=lake_engine, if_exists="replace", index=False, chunksize=5000, dtype=get_dtype_map(bookings_std))
    reviews_std.to_sql("lake_raw_hotel_reviews", con=lake_engine, if_exists="replace", index=False, chunksize=5000, dtype=get_dtype_map(reviews_std))
    log_step("ELT Load Raw to Lake", "Loaded raw standardized datasets into lake_raw_hotel_bookings and lake_raw_hotel_reviews", start, bookings_std.shape[0] + reviews_std.shape[0], bookings_std.shape[1] + reviews_std.shape[1])
    return bookings_std, reviews_std


def sql_assessment_lake(lake_engine):
    queries = {
        "raw_bookings_row_count": "SELECT COUNT(*) AS row_count FROM lake_raw_hotel_bookings",
        "raw_reviews_row_count": "SELECT COUNT(*) AS row_count FROM lake_raw_hotel_reviews",
        "raw_bookings_duplicate_proxy": "SELECT COUNT(*) AS total_rows, COUNT(DISTINCT hotel || arrival_date_year || arrival_date_month || arrival_date_day_of_month) AS approximate_distinct_rows FROM lake_raw_hotel_bookings",
        "raw_reviews_duplicate_proxy": "SELECT COUNT(*) AS total_rows, COUNT(DISTINCT hotel_name || reviewer_nationality || reviewer_score) AS approximate_distinct_rows FROM lake_raw_hotel_reviews",
    }
    results = []
    for name, sql in queries.items():
        try:
            temp = read_sql_df(sql, lake_engine)
            temp.insert(0, "check_name", name)
            results.append(temp)
        except Exception as exc:
            results.append(pd.DataFrame({"check_name": [name], "error": [str(exc)]}))
    out = pd.concat(results, ignore_index=True)
    display(out)
    return out

In [ ]:
# This lake URL is intentionally separate from the final ELT warehouse.
# Keep SQLite for the raw lake and SQL transform layer; the final warehouse is exported to Neon PostgreSQL later.
ELT_LAKE_URL = "sqlite:////content/hotel_elt_lake.db"

elt_lake_engine = create_sqlite_lake_engine(ELT_LAKE_URL)
source1_lake_raw, source2_lake_raw = load_raw_to_lake(source1_raw, source2_raw, elt_lake_engine)

print("Raw lake tables created:")
display(pd.DataFrame([
    {"lake_table": "lake_raw_hotel_bookings", "rows": source1_lake_raw.shape[0], "columns": source1_lake_raw.shape[1]},
    {"lake_table": "lake_raw_hotel_reviews", "rows": source2_lake_raw.shape[0], "columns": source2_lake_raw.shape[1]},
]))

Raw lake tables created:

                lake_table    rows  columns
0  lake_raw_hotel_bookings  119390       32
1   lake_raw_hotel_reviews  515738       17

## **Transform**

### Quality Checks and Assessment Plans

In [ ]:
source1_std_preview = standardize_column_names(source1_raw)
source2_std_preview = standardize_column_names(source2_raw)

source1_assessment_plan = quality_assessment_plan(source1_std_preview, "Source 1 - Hotel Bookings", "ELT SQL transform after lake load")
source2_assessment_plan = quality_assessment_plan(source2_std_preview, "Source 2 - Hotel Reviews", "ELT SQL transform after lake load")

elt_sql_raw_assessment = sql_assessment_lake(elt_lake_engine)

booking_range_rules = {
    "lead_time": {"min": 0},
    "adults": {"min": 0},
    "children": {"min": 0},
    "babies": {"min": 0},
    "adr": {"min": 0},
    "stays_in_weekend_nights": {"min": 0},
    "stays_in_week_nights": {"min": 0},
}
review_range_rules = {
    "average_score": {"min": 0, "max": 10},
    "reviewer_score": {"min": 0, "max": 10},
    "lat": {"min": -90, "max": 90},
    "lng": {"min": -180, "max": 180},
}

source1_range_report = range_check_report(source1_std_preview, "Source 1 - Hotel Bookings Raw", booking_range_rules)
source2_range_report = range_check_report(source2_std_preview, "Source 2 - Hotel Reviews Raw", review_range_rules)

Quality assessment plan - Source 1 - Hotel Bookings

,dataset,transform_method,stage,method,target_columns,priority,status
0,Source 1 - Hotel Bookings,ELT SQL transform after lake load,column standardization,lowercase snake_case columns,all,high,planned
1,Source 1 - Hotel Bookings,ELT SQL transform after lake load,missing value handling,"fill categorical with Unknown, numeric with 0/median, dates with 1900-01-01",all nullable columns,high,planned
2,Source 1 - Hotel Bookings,ELT SQL transform after lake load,unusual value handling,"replace placeholders such as No Negative, No Positive, NULL, N/A",categorical/text,high,planned
3,Source 1 - Hotel Bookings,ELT SQL transform after lake load,datatype conversion,convert date and numeric columns into consistent types,date/numeric fields,high,planned
4,Source 1 - Hotel Bookings,ELT SQL transform after lake load,range validation,"validate impossible values such as negative guests, scores outside 0-10, invalid lat/lng",numeric business fields,high,planned
5,Source 1 - Hotel Bookings,ELT SQL transform after lake load,outlier detection,IQR tagging for ETL/Pandas and SQL aggregate/range checks for ELT,"is_canceled, lead_time, arrival_date_year, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, is_repe...",medium,planned
6,Source 1 - Hotel Bookings,ELT SQL transform after lake load,categorical encoding,frequency encoding for selected categorical columns,"hotel, arrival_date_month, meal, country, market_segment, distribution_channel, reserved_room_type, assigned_room_type, deposit_type, customer_type",new addition,planned
7,Source 1 - Hotel Bookings,ELT SQL transform after lake load,numerical normalization,min-max normalization for selected numeric columns,"is_canceled, lead_time, arrival_date_year, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies",new addition,planned
8,Source 1 - Hotel Bookings,ELT SQL transform after lake load,primary key preparation,create deterministic integer surrogate keys before warehouse load,"booking_id, review_id, dimension ids",high,planned
9,Source 1 - Hotel Bookings,ELT SQL transform after lake load,foreign key preparation,map facts into dimension surrogate keys before loading constraints,*_id fields,high,planned
10,Source 1 - Hotel Bookings,ELT SQL transform after lake load,distribution validation,describe numeric distribution and categorical frequency before/after cleaning,all analytical fields,high,planned

Quality assessment plan - Source 2 - Hotel Reviews

,dataset,transform_method,stage,method,target_columns,priority,status
0,Source 2 - Hotel Reviews,ELT SQL transform after lake load,column standardization,lowercase snake_case columns,all,high,planned
1,Source 2 - Hotel Reviews,ELT SQL transform after lake load,missing value handling,"fill categorical with Unknown, numeric with 0/median, dates with 1900-01-01",all nullable columns,high,planned
2,Source 2 - Hotel Reviews,ELT SQL transform after lake load,unusual value handling,"replace placeholders such as No Negative, No Positive, NULL, N/A",categorical/text,high,planned
3,Source 2 - Hotel Reviews,ELT SQL transform after lake load,datatype conversion,convert date and numeric columns into consistent types,date/numeric fields,high,planned
4,Source 2 - Hotel Reviews,ELT SQL transform after lake load,range validation,"validate impossible values such as negative guests, scores outside 0-10, invalid lat/lng",numeric business fields,high,planned
5,Source 2 - Hotel Reviews,ELT SQL transform after lake load,outlier detection,IQR tagging for ETL/Pandas and SQL aggregate/range checks for ELT,"additional_number_of_scoring, average_score, review_total_negative_word_counts, total_number_of_reviews, review_total_positive_word_counts, total_number_of_reviews_reviewer_has...",medium,planned
6,Source 2 - Hotel Reviews,ELT SQL transform after lake load,categorical encoding,frequency encoding for selected categorical columns,"hotel_address, review_date, hotel_name, reviewer_nationality, negative_review, positive_review, tags, days_since_review",new addition,planned
7,Source 2 - Hotel Reviews,ELT SQL transform after lake load,numerical normalization,min-max normalization for selected numeric columns,"additional_number_of_scoring, average_score, review_total_negative_word_counts, total_number_of_reviews, review_total_positive_word_counts, total_number_of_reviews_reviewer_has...",new addition,planned
8,Source 2 - Hotel Reviews,ELT SQL transform after lake load,primary key preparation,create deterministic integer surrogate keys before warehouse load,"booking_id, review_id, dimension ids",high,planned
9,Source 2 - Hotel Reviews,ELT SQL transform after lake load,foreign key preparation,map facts into dimension surrogate keys before loading constraints,*_id fields,high,planned
10,Source 2 - Hotel Reviews,ELT SQL transform after lake load,distribution validation,describe numeric distribution and categorical frequency before/after cleaning,all analytical fields,high,planned

,check_name,row_count,total_rows,approximate_distinct_rows
0,raw_bookings_row_count,119390.0,NaN,NaN
1,raw_reviews_row_count,515738.0,NaN,NaN
2,raw_bookings_duplicate_proxy,NaN,119390.0,1586.0
3,raw_reviews_duplicate_proxy,NaN,515738.0,191183.0

Range check report - Source 1 - Hotel Bookings Raw

,dataset,column,rule,status,invalid_count
0,Source 1 - Hotel Bookings Raw,lead_time,{'min': 0},PASS,0
1,Source 1 - Hotel Bookings Raw,adults,{'min': 0},PASS,0
2,Source 1 - Hotel Bookings Raw,children,{'min': 0},PASS,0
3,Source 1 - Hotel Bookings Raw,babies,{'min': 0},PASS,0
4,Source 1 - Hotel Bookings Raw,adr,{'min': 0},FAIL,1
5,Source 1 - Hotel Bookings Raw,stays_in_weekend_nights,{'min': 0},PASS,0
6,Source 1 - Hotel Bookings Raw,stays_in_week_nights,{'min': 0},PASS,0

Range check report - Source 2 - Hotel Reviews Raw

,dataset,column,rule,status,invalid_count
0,Source 2 - Hotel Reviews Raw,average_score,"{'min': 0, 'max': 10}",PASS,0
1,Source 2 - Hotel Reviews Raw,reviewer_score,"{'min': 0, 'max': 10}",PASS,0
2,Source 2 - Hotel Reviews Raw,lat,"{'min': -90, 'max': 90}",PASS,0
3,Source 2 - Hotel Reviews Raw,lng,"{'min': -180, 'max': 180}",PASS,0

### Transformation Processes

In [ ]:

def get_sqlite_columns(engine, table_name):
    with engine.connect() as conn:
        rows = conn.execute(text(f'PRAGMA table_info("{table_name}")')).fetchall()
    return [row[1] for row in rows]


def qcol(col):
    return f'"{col}"'


def text_expr(cols, col, default="Unknown"):
    if col in cols:
        return f"TRIM(COALESCE(NULLIF(CAST({qcol(col)} AS TEXT), ''), '{default}'))"
    return f"'{default}'"


def num_expr(cols, col, default=0):
    if col in cols:
        return f"CAST(COALESCE(NULLIF(CAST({qcol(col)} AS TEXT), ''), {default}) AS REAL)"
    return f"CAST({default} AS REAL)"


def int_expr(cols, col, default=0):
    if col in cols:
        return f"CAST(COALESCE(NULLIF(CAST({qcol(col)} AS TEXT), ''), {default}) AS INTEGER)"
    return f"CAST({default} AS INTEGER)"


def date_expr(cols, col, default="1900-01-01"):
    if col in cols:
        return f"COALESCE(date({qcol(col)}), '{default}')"
    return f"'{default}'"


def mdy_date_expr(cols, col, default="1900-01-01"):
    """Parse M/D/YYYY text with native SQLite expressions instead of a Python row UDF."""
    if col not in cols:
        return f"'{default}'"

    value = f"TRIM(CAST({qcol(col)} AS TEXT))"
    first_slash = f"instr({value}, '/')"
    remainder = f"substr({value}, {first_slash} + 1)"
    second_slash = f"instr({remainder}, '/')"

    return f"""CASE
        WHEN {value} = '' THEN '{default}'
        WHEN {first_slash} > 0 AND {second_slash} > 0 THEN
            printf(
                '%04d-%02d-%02d',
                CAST(substr({remainder}, {second_slash} + 1) AS INTEGER),
                CAST(substr({value}, 1, {first_slash} - 1) AS INTEGER),
                CAST(substr({remainder}, 1, {second_slash} - 1) AS INTEGER)
            )
        ELSE COALESCE(date({qcol(col)}), '{default}')
    END"""


def exec_sql_safe(engine, sql, label="SQL step"):
    start = time.time()
    with engine.begin() as conn:
        for stmt in [s.strip() for s in sql.split(";") if s.strip()]:
            conn.execute(text(stmt))
    print(f"Finished: {label} in {round(time.time() - start, 2)} seconds")


def build_elt_sql_tables(lake_engine):
    """
    Build the ELT lake/curated snowflake schema using SQL after raw data has been loaded.
    Lake tables keep the physical elt_ prefix; collect_elt_tables() returns logical keys.
    """
    start_all = time.time()
    register_sqlite_udfs(lake_engine)

    booking_cols = get_sqlite_columns(lake_engine, "lake_raw_hotel_bookings")
    review_cols = get_sqlite_columns(lake_engine, "lake_raw_hotel_reviews")
    print("Detected booking columns:", len(booking_cols))
    print("Detected review columns:", len(review_cols))

    hotel = text_expr(booking_cols, "hotel")
    is_canceled = int_expr(booking_cols, "is_canceled", 0)
    lead_time = num_expr(booking_cols, "lead_time", 0)
    arrival_year = int_expr(booking_cols, "arrival_date_year", 1900)
    arrival_month = text_expr(booking_cols, "arrival_date_month", "January")
    arrival_week = int_expr(booking_cols, "arrival_date_week_number", 1)
    arrival_day = int_expr(booking_cols, "arrival_date_day_of_month", 1)
    weekend_nights = num_expr(booking_cols, "stays_in_weekend_nights", 0)
    week_nights = num_expr(booking_cols, "stays_in_week_nights", 0)
    adults = num_expr(booking_cols, "adults", 0)
    children = num_expr(booking_cols, "children", 0)
    babies = num_expr(booking_cols, "babies", 0)
    meal = text_expr(booking_cols, "meal")
    country = text_expr(booking_cols, "country")
    market_segment = text_expr(booking_cols, "market_segment")
    distribution_channel = text_expr(booking_cols, "distribution_channel")
    repeated_guest = int_expr(booking_cols, "is_repeated_guest", 0)
    prev_cancel = num_expr(booking_cols, "previous_cancellations", 0)
    prev_not_cancel = num_expr(booking_cols, "previous_bookings_not_canceled", 0)
    reserved_room = text_expr(booking_cols, "reserved_room_type")
    assigned_room = text_expr(booking_cols, "assigned_room_type")
    booking_changes = num_expr(booking_cols, "booking_changes", 0)
    deposit_type = text_expr(booking_cols, "deposit_type")
    agent = text_expr(booking_cols, "agent")
    company = text_expr(booking_cols, "company")
    waiting = num_expr(booking_cols, "days_in_waiting_list", 0)
    customer_type = text_expr(booking_cols, "customer_type")
    adr = num_expr(booking_cols, "adr", 0)
    parking = num_expr(booking_cols, "required_car_parking_spaces", 0)
    special_requests = num_expr(booking_cols, "total_of_special_requests", 0)
    reservation_status = text_expr(booking_cols, "reservation_status")
    reservation_status_date = date_expr(booking_cols, "reservation_status_date")

    exec_sql_safe(lake_engine, f"""
    DROP TABLE IF EXISTS elt_clean_hotel_bookings;

    CREATE TABLE elt_clean_hotel_bookings AS
    WITH base AS (
        SELECT
            ROW_NUMBER() OVER (ORDER BY rowid) AS booking_id,
            {hotel} AS hotel,
            CASE WHEN {is_canceled} NOT IN (0, 1) THEN 0 ELSE {is_canceled} END AS is_canceled,
            CASE WHEN {lead_time} < 0 THEN 0 ELSE {lead_time} END AS lead_time,
            {arrival_year} AS arrival_date_year,
            {arrival_month} AS arrival_date_month,
            {arrival_week} AS arrival_date_week_number,
            {arrival_day} AS arrival_date_day_of_month,
            CASE WHEN {weekend_nights} < 0 THEN 0 ELSE {weekend_nights} END AS stays_in_weekend_nights,
            CASE WHEN {week_nights} < 0 THEN 0 ELSE {week_nights} END AS stays_in_week_nights,
            CASE WHEN {adults} < 0 THEN 0 ELSE {adults} END AS adults,
            CASE WHEN {children} < 0 THEN 0 ELSE {children} END AS children,
            CASE WHEN {babies} < 0 THEN 0 ELSE {babies} END AS babies,
            {meal} AS meal,
            {country} AS country,
            {market_segment} AS market_segment,
            {distribution_channel} AS distribution_channel,
            {repeated_guest} AS is_repeated_guest,
            CASE WHEN {prev_cancel} < 0 THEN 0 ELSE {prev_cancel} END AS previous_cancellations,
            CASE WHEN {prev_not_cancel} < 0 THEN 0 ELSE {prev_not_cancel} END AS previous_bookings_not_canceled,
            {reserved_room} AS reserved_room_type,
            {assigned_room} AS assigned_room_type,
            CASE WHEN {booking_changes} < 0 THEN 0 ELSE {booking_changes} END AS booking_changes,
            {deposit_type} AS deposit_type,
            {agent} AS agent,
            {company} AS company,
            CASE WHEN {waiting} < 0 THEN 0 ELSE {waiting} END AS days_in_waiting_list,
            {customer_type} AS customer_type,
            CASE WHEN {adr} < 0 THEN 0 ELSE {adr} END AS adr,
            CASE WHEN {parking} < 0 THEN 0 ELSE {parking} END AS required_car_parking_spaces,
            CASE WHEN {special_requests} < 0 THEN 0 ELSE {special_requests} END AS total_of_special_requests,
            {reservation_status} AS reservation_status,
            {reservation_status_date} AS reservation_status_date
        FROM lake_raw_hotel_bookings
    ),
    enriched AS (
        SELECT
            *,
            adults + children + babies AS total_guests,
            stays_in_weekend_nights + stays_in_week_nights AS total_nights,
            CASE WHEN adults + children + babies <= 0 THEN 1 ELSE 0 END AS zero_guest_flag,
            CASE WHEN stays_in_weekend_nights + stays_in_week_nights <= 0 THEN 1 ELSE 0 END AS zero_night_flag,
            CASE WHEN LOWER(agent) = 'unknown' THEN 0 ELSE 1 END AS has_agent,
            CASE WHEN LOWER(company) = 'unknown' THEN 0 ELSE 1 END AS has_company,
            CASE WHEN reserved_room_type <> assigned_room_type THEN 1 ELSE 0 END AS room_changed,
            printf('%04d-%02d-%02d',
                arrival_date_year,
                CASE LOWER(arrival_date_month)
                    WHEN 'january' THEN 1 WHEN 'february' THEN 2 WHEN 'march' THEN 3 WHEN 'april' THEN 4
                    WHEN 'may' THEN 5 WHEN 'june' THEN 6 WHEN 'july' THEN 7 WHEN 'august' THEN 8
                    WHEN 'september' THEN 9 WHEN 'october' THEN 10 WHEN 'november' THEN 11 WHEN 'december' THEN 12
                    ELSE 1
                END,
                CASE WHEN arrival_date_day_of_month BETWEEN 1 AND 28 THEN arrival_date_day_of_month ELSE 1 END
            ) AS arrival_date
        FROM base
    ),
    stats AS (
        SELECT MIN(lead_time) min_lead_time, MAX(lead_time) max_lead_time,
               MIN(adr) min_adr, MAX(adr) max_adr,
               MIN(total_nights) min_total_nights, MAX(total_nights) max_total_nights,
               MIN(total_guests) min_total_guests, MAX(total_guests) max_total_guests
        FROM enriched
    )
    SELECT
        e.*,
        CASE WHEN s.max_lead_time = s.min_lead_time THEN 0 ELSE ROUND((e.lead_time - s.min_lead_time) / (s.max_lead_time - s.min_lead_time), 6) END AS lead_time_minmax,
        CASE WHEN s.max_adr = s.min_adr THEN 0 ELSE ROUND((e.adr - s.min_adr) / (s.max_adr - s.min_adr), 6) END AS adr_minmax,
        CASE WHEN s.max_total_nights = s.min_total_nights THEN 0 ELSE ROUND((e.total_nights - s.min_total_nights) / (s.max_total_nights - s.min_total_nights), 6) END AS total_nights_minmax,
        CASE WHEN s.max_total_guests = s.min_total_guests THEN 0 ELSE ROUND((e.total_guests - s.min_total_guests) / (s.max_total_guests - s.min_total_guests), 6) END AS total_guests_minmax,
        0 AS source_duplicate_flag,
        0 AS outlier_count
    FROM enriched e CROSS JOIN stats s;
    """, "Create SQL-cleaned hotel bookings")

    exec_sql_safe(lake_engine, """
    DROP TABLE IF EXISTS tmp_market_segment_freq;
    CREATE TABLE tmp_market_segment_freq AS
    SELECT market_segment, COUNT(*) * 1.0 / (SELECT COUNT(*) FROM elt_clean_hotel_bookings) AS market_segment_freq_encoded
    FROM elt_clean_hotel_bookings GROUP BY market_segment;

    DROP TABLE IF EXISTS tmp_customer_type_freq;
    CREATE TABLE tmp_customer_type_freq AS
    SELECT customer_type, COUNT(*) * 1.0 / (SELECT COUNT(*) FROM elt_clean_hotel_bookings) AS customer_type_freq_encoded
    FROM elt_clean_hotel_bookings GROUP BY customer_type;

    DROP TABLE IF EXISTS elt_clean_hotel_bookings_v2;
    CREATE TABLE elt_clean_hotel_bookings_v2 AS
    SELECT b.*, COALESCE(ms.market_segment_freq_encoded, 0) AS market_segment_freq_encoded,
           COALESCE(ct.customer_type_freq_encoded, 0) AS customer_type_freq_encoded
    FROM elt_clean_hotel_bookings b
    LEFT JOIN tmp_market_segment_freq ms ON b.market_segment = ms.market_segment
    LEFT JOIN tmp_customer_type_freq ct ON b.customer_type = ct.customer_type;

    DROP TABLE elt_clean_hotel_bookings;
    ALTER TABLE elt_clean_hotel_bookings_v2 RENAME TO elt_clean_hotel_bookings;
    DROP TABLE IF EXISTS tmp_market_segment_freq;
    DROP TABLE IF EXISTS tmp_customer_type_freq;
    """, "Add SQL frequency encoding to bookings")

    hotel_address = text_expr(review_cols, "hotel_address")
    scoring = num_expr(review_cols, "additional_number_of_scoring", 0)
    average_score = num_expr(review_cols, "average_score", 0)
    hotel_name = text_expr(review_cols, "hotel_name")
    reviewer_nationality = text_expr(review_cols, "reviewer_nationality")
    negative_review = text_expr(review_cols, "negative_review", "No negative review provided")
    negative_words = num_expr(review_cols, "review_total_negative_word_counts", 0)
    total_reviews = num_expr(review_cols, "total_number_of_reviews", 0)
    positive_review = text_expr(review_cols, "positive_review", "No positive review provided")
    positive_words = num_expr(review_cols, "review_total_positive_word_counts", 0)
    reviewer_total_reviews = num_expr(review_cols, "total_number_of_reviews_reviewer_has_given", 0)
    reviewer_score = num_expr(review_cols, "reviewer_score", 0)
    tags = text_expr(review_cols, "tags")
    lat = num_expr(review_cols, "lat", 0)
    lng = num_expr(review_cols, "lng", 0)
    review_date_sql = mdy_date_expr(review_cols, "review_date")
    days_since_review = "CAST(COALESCE(REPLACE(CAST(days_since_review AS TEXT), ' days', ''), 0) AS INTEGER)" if "days_since_review" in review_cols else "CAST(0 AS INTEGER)"

    exec_sql_safe(lake_engine, f"""
    DROP TABLE IF EXISTS tmp_reviewer_nationality_freq;
    CREATE TABLE tmp_reviewer_nationality_freq AS
    SELECT
        {reviewer_nationality} AS reviewer_nationality,
        COUNT(*) * 1.0 / (SELECT COUNT(*) FROM lake_raw_hotel_reviews) AS reviewer_nationality_freq_encoded
    FROM lake_raw_hotel_reviews
    GROUP BY {reviewer_nationality};
    CREATE UNIQUE INDEX idx_tmp_reviewer_nationality_freq
    ON tmp_reviewer_nationality_freq(reviewer_nationality);

    DROP TABLE IF EXISTS tmp_hotel_name_freq;
    CREATE TABLE tmp_hotel_name_freq AS
    SELECT
        {hotel_name} AS hotel_name,
        COUNT(*) * 1.0 / (SELECT COUNT(*) FROM lake_raw_hotel_reviews) AS hotel_name_freq_encoded
    FROM lake_raw_hotel_reviews
    GROUP BY {hotel_name};
    CREATE UNIQUE INDEX idx_tmp_hotel_name_freq
    ON tmp_hotel_name_freq(hotel_name);

    DROP TABLE IF EXISTS tmp_elt_review_stats;
    CREATE TABLE tmp_elt_review_stats AS
    SELECT
        MIN(CASE WHEN {average_score} < 0 THEN 0 WHEN {average_score} > 10 THEN 10 ELSE {average_score} END) AS min_average_score,
        MAX(CASE WHEN {average_score} < 0 THEN 0 WHEN {average_score} > 10 THEN 10 ELSE {average_score} END) AS max_average_score,
        MIN(CASE WHEN {reviewer_score} < 0 THEN 0 WHEN {reviewer_score} > 10 THEN 10 ELSE {reviewer_score} END) AS min_reviewer_score,
        MAX(CASE WHEN {reviewer_score} < 0 THEN 0 WHEN {reviewer_score} > 10 THEN 10 ELSE {reviewer_score} END) AS max_reviewer_score,
        MIN(CASE WHEN {positive_words} < 0 THEN 0 ELSE {positive_words} END) AS min_positive_words,
        MAX(CASE WHEN {positive_words} < 0 THEN 0 ELSE {positive_words} END) AS max_positive_words,
        MIN(CASE WHEN {negative_words} < 0 THEN 0 ELSE {negative_words} END) AS min_negative_words,
        MAX(CASE WHEN {negative_words} < 0 THEN 0 ELSE {negative_words} END) AS max_negative_words
    FROM lake_raw_hotel_reviews;
    """, "Prepare SQL review encoding and normalization statistics")

    exec_sql_safe(lake_engine, f"""
    DROP TABLE IF EXISTS elt_clean_hotel_reviews;
    CREATE TABLE elt_clean_hotel_reviews AS
    WITH base AS (
        SELECT
            ROW_NUMBER() OVER (ORDER BY rowid) AS review_id,
            {hotel_address} AS hotel_address,
            CASE WHEN {scoring} < 0 THEN 0 ELSE {scoring} END AS additional_number_of_scoring,
            CASE WHEN {average_score} < 0 THEN 0 WHEN {average_score} > 10 THEN 10 ELSE {average_score} END AS average_score,
            {hotel_name} AS hotel_name,
            {reviewer_nationality} AS reviewer_nationality,
            {negative_review} AS negative_review,
            CASE WHEN {negative_words} < 0 THEN 0 ELSE {negative_words} END AS negative_review_word_count,
            CASE WHEN {total_reviews} < 0 THEN 0 ELSE {total_reviews} END AS total_number_of_reviews,
            {positive_review} AS positive_review,
            CASE WHEN {positive_words} < 0 THEN 0 ELSE {positive_words} END AS positive_review_word_count,
            CASE WHEN {reviewer_total_reviews} < 0 THEN 0 ELSE {reviewer_total_reviews} END AS total_number_of_reviews_reviewer_has_given,
            CASE WHEN {reviewer_score} < 0 THEN 0 WHEN {reviewer_score} > 10 THEN 10 ELSE {reviewer_score} END AS reviewer_score,
            {tags} AS tags,
            CASE WHEN {lat} < -90 OR {lat} > 90 THEN 0 ELSE {lat} END AS lat,
            CASE WHEN {lng} < -180 OR {lng} > 180 THEN 0 ELSE {lng} END AS lng,
            {review_date_sql} AS review_date,
            {days_since_review} AS days_since_review_numeric
        FROM lake_raw_hotel_reviews
    )
    SELECT
        b.*,
        LENGTH(b.positive_review) AS positive_review_length,
        LENGTH(b.negative_review) AS negative_review_length,
        b.positive_review_word_count - b.negative_review_word_count AS sentiment_word_balance,
        LENGTH(b.tags) - LENGTH(REPLACE(b.tags, ',', '')) + 1 AS tag_count,
        0 AS source_duplicate_flag,
        0 AS outlier_count,
        CASE WHEN s.max_average_score = s.min_average_score THEN 0
             ELSE ROUND((b.average_score - s.min_average_score) / (s.max_average_score - s.min_average_score), 6)
        END AS average_score_minmax,
        CASE WHEN s.max_reviewer_score = s.min_reviewer_score THEN 0
             ELSE ROUND((b.reviewer_score - s.min_reviewer_score) / (s.max_reviewer_score - s.min_reviewer_score), 6)
        END AS reviewer_score_minmax,
        CASE WHEN s.max_positive_words = s.min_positive_words THEN 0
             ELSE ROUND((b.positive_review_word_count - s.min_positive_words) / (s.max_positive_words - s.min_positive_words), 6)
        END AS positive_review_word_count_minmax,
        CASE WHEN s.max_negative_words = s.min_negative_words THEN 0
             ELSE ROUND((b.negative_review_word_count - s.min_negative_words) / (s.max_negative_words - s.min_negative_words), 6)
        END AS negative_review_word_count_minmax,
        COALESCE(rn.reviewer_nationality_freq_encoded, 0) AS reviewer_nationality_freq_encoded,
        COALESCE(hn.hotel_name_freq_encoded, 0) AS hotel_name_freq_encoded
    FROM base b
    CROSS JOIN tmp_elt_review_stats s
    LEFT JOIN tmp_reviewer_nationality_freq rn
        ON b.reviewer_nationality = rn.reviewer_nationality
    LEFT JOIN tmp_hotel_name_freq hn
        ON b.hotel_name = hn.hotel_name;

    DROP TABLE IF EXISTS tmp_reviewer_nationality_freq;
    DROP TABLE IF EXISTS tmp_hotel_name_freq;
    DROP TABLE IF EXISTS tmp_elt_review_stats;
    """, "Create SQL-cleaned hotel reviews with encoding and normalization")

    exec_sql_safe(lake_engine, """
    DROP TABLE IF EXISTS elt_dim_date;
    CREATE TABLE elt_dim_date AS
    WITH dates AS (
        SELECT arrival_date AS date_value FROM elt_clean_hotel_bookings
        UNION SELECT reservation_status_date FROM elt_clean_hotel_bookings
        UNION SELECT review_date FROM elt_clean_hotel_reviews
        UNION SELECT date(arrival_date, 'start of month') FROM elt_clean_hotel_bookings
        UNION SELECT date(review_date, 'start of month') FROM elt_clean_hotel_reviews
        UNION SELECT '1900-01-01'
    )
    SELECT ROW_NUMBER() OVER (ORDER BY date_value) AS date_id,
           date_value AS date,
           CAST(strftime('%Y', date_value) AS INTEGER) AS year,
           CAST(strftime('%m', date_value) AS INTEGER) AS month,
           CAST(strftime('%d', date_value) AS INTEGER) AS day,
           ((CAST(strftime('%m', date_value) AS INTEGER) - 1) / 3) + 1 AS quarter,
           CASE strftime('%m', date_value)
                WHEN '01' THEN 'January' WHEN '02' THEN 'February' WHEN '03' THEN 'March' WHEN '04' THEN 'April'
                WHEN '05' THEN 'May' WHEN '06' THEN 'June' WHEN '07' THEN 'July' WHEN '08' THEN 'August'
                WHEN '09' THEN 'September' WHEN '10' THEN 'October' WHEN '11' THEN 'November' WHEN '12' THEN 'December'
                ELSE 'Unknown' END AS month_name,
           strftime('%Y-%m', date_value) AS year_month
    FROM dates;

    DROP TABLE IF EXISTS elt_dim_booking_hotel_type;
    CREATE TABLE elt_dim_booking_hotel_type AS
    SELECT ROW_NUMBER() OVER (ORDER BY hotel_type) AS booking_hotel_type_id, hotel_type
    FROM (SELECT DISTINCT COALESCE(hotel, 'Unknown') AS hotel_type FROM elt_clean_hotel_bookings UNION SELECT 'Unknown');

    DROP TABLE IF EXISTS elt_dim_country;
    CREATE TABLE elt_dim_country AS
    SELECT ROW_NUMBER() OVER (ORDER BY country_name) AS country_id, country_name
    FROM (
        SELECT DISTINCT COALESCE(country, 'Unknown') AS country_name FROM elt_clean_hotel_bookings
        UNION SELECT DISTINCT COALESCE(reviewer_nationality, 'Unknown') FROM elt_clean_hotel_reviews
        UNION SELECT 'Unknown'
    );

    DROP TABLE IF EXISTS elt_dim_meal;
    CREATE TABLE elt_dim_meal AS
    SELECT ROW_NUMBER() OVER (ORDER BY meal) AS meal_id, meal
    FROM (SELECT DISTINCT COALESCE(meal, 'Unknown') AS meal FROM elt_clean_hotel_bookings UNION SELECT 'Unknown');

    DROP TABLE IF EXISTS elt_dim_market_segment;
    CREATE TABLE elt_dim_market_segment AS
    SELECT ROW_NUMBER() OVER (ORDER BY market_segment) AS market_segment_id, market_segment
    FROM (SELECT DISTINCT COALESCE(market_segment, 'Unknown') AS market_segment FROM elt_clean_hotel_bookings UNION SELECT 'Unknown');

    DROP TABLE IF EXISTS elt_dim_distribution_channel;
    CREATE TABLE elt_dim_distribution_channel AS
    SELECT ROW_NUMBER() OVER (ORDER BY distribution_channel) AS distribution_channel_id, distribution_channel
    FROM (SELECT DISTINCT COALESCE(distribution_channel, 'Unknown') AS distribution_channel FROM elt_clean_hotel_bookings UNION SELECT 'Unknown');

    DROP TABLE IF EXISTS elt_dim_customer_type;
    CREATE TABLE elt_dim_customer_type AS
    SELECT ROW_NUMBER() OVER (ORDER BY customer_type) AS customer_type_id, customer_type
    FROM (SELECT DISTINCT COALESCE(customer_type, 'Unknown') AS customer_type FROM elt_clean_hotel_bookings UNION SELECT 'Unknown');

    DROP TABLE IF EXISTS elt_dim_deposit_type;
    CREATE TABLE elt_dim_deposit_type AS
    SELECT ROW_NUMBER() OVER (ORDER BY deposit_type) AS deposit_type_id, deposit_type
    FROM (SELECT DISTINCT COALESCE(deposit_type, 'Unknown') AS deposit_type FROM elt_clean_hotel_bookings UNION SELECT 'Unknown');

    DROP TABLE IF EXISTS elt_dim_room_type;
    CREATE TABLE elt_dim_room_type AS
    SELECT ROW_NUMBER() OVER (ORDER BY room_type) AS room_type_id, room_type
    FROM (
        SELECT DISTINCT COALESCE(reserved_room_type, 'Unknown') AS room_type FROM elt_clean_hotel_bookings
        UNION SELECT DISTINCT COALESCE(assigned_room_type, 'Unknown') FROM elt_clean_hotel_bookings
        UNION SELECT 'Unknown'
    );

    DROP TABLE IF EXISTS elt_dim_review_hotel;
    CREATE TABLE elt_dim_review_hotel AS
    SELECT ROW_NUMBER() OVER (ORDER BY hotel_name, hotel_address) AS review_hotel_id,
           hotel_name, hotel_address, AVG(lat) AS lat, AVG(lng) AS lng, AVG(average_score) AS average_score
    FROM (
        SELECT hotel_name, hotel_address, lat, lng, average_score FROM elt_clean_hotel_reviews
        UNION ALL SELECT 'Unknown', 'Unknown', 0, 0, 0
    )
    GROUP BY hotel_name, hotel_address;
    """, "Create ELT snowflake dimensions")

    exec_sql_safe(lake_engine, """
    DROP TABLE IF EXISTS elt_fact_bookings;
    CREATE TABLE elt_fact_bookings AS
    SELECT b.booking_id,
           COALESCE(da.date_id, 1) AS arrival_date_id,
           COALESCE(dr.date_id, 1) AS reservation_status_date_id,
           COALESCE(ht.booking_hotel_type_id, 1) AS booking_hotel_type_id,
           COALESCE(c.country_id, 1) AS country_id,
           COALESCE(meal.meal_id, 1) AS meal_id,
           COALESCE(ms.market_segment_id, 1) AS market_segment_id,
           COALESCE(dc.distribution_channel_id, 1) AS distribution_channel_id,
           COALESCE(ct.customer_type_id, 1) AS customer_type_id,
           COALESCE(dep.deposit_type_id, 1) AS deposit_type_id,
           COALESCE(rr.room_type_id, 1) AS reserved_room_type_id,
           COALESCE(ar.room_type_id, 1) AS assigned_room_type_id,
           b.is_canceled, b.lead_time, b.arrival_date_week_number,
           b.stays_in_weekend_nights, b.stays_in_week_nights, b.total_nights,
           b.adults, b.children, b.babies, b.total_guests,
           b.is_repeated_guest, b.previous_cancellations, b.previous_bookings_not_canceled,
           b.booking_changes, b.days_in_waiting_list, b.adr,
           b.adr * b.total_nights AS total_revenue_proxy,
           b.required_car_parking_spaces, b.total_of_special_requests,
           b.zero_guest_flag, b.zero_night_flag, b.has_agent, b.has_company, b.room_changed,
           b.source_duplicate_flag, b.outlier_count,
           b.lead_time_minmax, b.adr_minmax, b.total_guests_minmax, b.total_nights_minmax,
           b.market_segment_freq_encoded, b.customer_type_freq_encoded
    FROM elt_clean_hotel_bookings b
    LEFT JOIN elt_dim_date da ON b.arrival_date = da.date
    LEFT JOIN elt_dim_date dr ON b.reservation_status_date = dr.date
    LEFT JOIN elt_dim_booking_hotel_type ht ON b.hotel = ht.hotel_type
    LEFT JOIN elt_dim_country c ON b.country = c.country_name
    LEFT JOIN elt_dim_meal meal ON b.meal = meal.meal
    LEFT JOIN elt_dim_market_segment ms ON b.market_segment = ms.market_segment
    LEFT JOIN elt_dim_distribution_channel dc ON b.distribution_channel = dc.distribution_channel
    LEFT JOIN elt_dim_customer_type ct ON b.customer_type = ct.customer_type
    LEFT JOIN elt_dim_deposit_type dep ON b.deposit_type = dep.deposit_type
    LEFT JOIN elt_dim_room_type rr ON b.reserved_room_type = rr.room_type
    LEFT JOIN elt_dim_room_type ar ON b.assigned_room_type = ar.room_type;

    DROP TABLE IF EXISTS elt_fact_reviews;
    CREATE TABLE elt_fact_reviews AS
    SELECT r.review_id,
           COALESCE(d.date_id, 1) AS review_date_id,
           COALESCE(c.country_id, 1) AS reviewer_country_id,
           COALESCE(h.review_hotel_id, 1) AS review_hotel_id,
           r.additional_number_of_scoring, r.average_score, r.total_number_of_reviews,
           r.total_number_of_reviews_reviewer_has_given, r.reviewer_score,
           r.positive_review_word_count, r.negative_review_word_count,
           r.positive_review_length, r.negative_review_length,
           r.sentiment_word_balance, r.tag_count, r.days_since_review_numeric,
           r.source_duplicate_flag, r.outlier_count,
           r.average_score_minmax, r.reviewer_score_minmax,
           r.positive_review_word_count_minmax, r.negative_review_word_count_minmax,
           r.reviewer_nationality_freq_encoded, r.hotel_name_freq_encoded
    FROM elt_clean_hotel_reviews r
    LEFT JOIN elt_dim_date d ON r.review_date = d.date
    LEFT JOIN elt_dim_country c ON r.reviewer_nationality = c.country_name
    LEFT JOIN elt_dim_review_hotel h ON r.hotel_name = h.hotel_name AND r.hotel_address = h.hotel_address;
    """, "Create ELT fact tables")

    exec_sql_safe(lake_engine, """
    DROP TABLE IF EXISTS elt_fact_hotel_monthly_performance;
    CREATE TABLE elt_fact_hotel_monthly_performance AS
    WITH booking_metric AS (
        SELECT d_month.date_id AS month_start_date_id,
               COUNT(f.booking_id) AS booking_count,
               SUM(f.is_canceled) AS canceled_booking_count,
               AVG(f.is_canceled) AS cancellation_rate,
               AVG(f.adr) AS avg_adr,
               SUM(f.total_revenue_proxy) AS total_revenue_proxy,
               AVG(f.total_nights) AS avg_total_nights,
               AVG(f.total_guests) AS avg_total_guests
        FROM elt_fact_bookings f
        JOIN elt_dim_date d ON f.arrival_date_id = d.date_id
        JOIN elt_dim_date d_month ON date(d.date, 'start of month') = d_month.date
        GROUP BY d_month.date_id
    ),
    review_metric AS (
        SELECT d_month.date_id AS month_start_date_id,
               COUNT(r.review_id) AS review_count,
               AVG(r.reviewer_score) AS avg_reviewer_score,
               AVG(r.sentiment_word_balance) AS avg_sentiment_word_balance
        FROM elt_fact_reviews r
        JOIN elt_dim_date d ON r.review_date_id = d.date_id
        JOIN elt_dim_date d_month ON date(d.date, 'start of month') = d_month.date
        GROUP BY d_month.date_id
    )
    SELECT ROW_NUMBER() OVER (ORDER BY b.month_start_date_id) AS performance_id,
           b.month_start_date_id,
           b.booking_count,
           b.canceled_booking_count,
           b.cancellation_rate,
           b.avg_adr,
           b.total_revenue_proxy,
           b.avg_total_nights,
           b.avg_total_guests,
           COALESCE(r.review_count, 0) AS review_count,
           COALESCE(r.avg_reviewer_score, 0) AS avg_reviewer_score,
           COALESCE(r.avg_sentiment_word_balance, 0) AS avg_sentiment_word_balance
    FROM booking_metric b
    LEFT JOIN review_metric r ON b.month_start_date_id = r.month_start_date_id;

    DROP TABLE IF EXISTS elt_metric_booking_by_segment;
    CREATE TABLE elt_metric_booking_by_segment AS
    SELECT ROW_NUMBER() OVER (ORDER BY ms.market_segment) AS metric_segment_id,
           ms.market_segment, COUNT(f.booking_id) AS booking_count,
           AVG(f.is_canceled) AS cancellation_rate,
           AVG(f.adr) AS avg_adr,
           SUM(f.total_revenue_proxy) AS total_revenue_proxy,
           AVG(f.total_nights) AS avg_total_nights
    FROM elt_fact_bookings f
    LEFT JOIN elt_dim_market_segment ms ON f.market_segment_id = ms.market_segment_id
    GROUP BY ms.market_segment;

    DROP TABLE IF EXISTS elt_metric_review_by_hotel;
    CREATE TABLE elt_metric_review_by_hotel AS
    SELECT ROW_NUMBER() OVER (ORDER BY h.hotel_name) AS metric_review_hotel_id,
           h.hotel_name, COUNT(r.review_id) AS review_count,
           AVG(r.reviewer_score) AS avg_reviewer_score,
           AVG(r.average_score) AS avg_average_score,
           AVG(r.positive_review_word_count) AS avg_positive_words,
           AVG(r.negative_review_word_count) AS avg_negative_words,
           AVG(r.sentiment_word_balance) AS avg_sentiment_word_balance
    FROM elt_fact_reviews r
    LEFT JOIN elt_dim_review_hotel h ON r.review_hotel_id = h.review_hotel_id
    GROUP BY h.hotel_name;

    DROP TABLE IF EXISTS elt_metric_monthly_kpi;
    CREATE TABLE elt_metric_monthly_kpi AS
    SELECT * FROM elt_fact_hotel_monthly_performance;
    """, "Create ELT aggregation and metric analytics tables")

    log_step("ELT SQL Transform", "Built SQL-cleaned tables, snowflake schema, foreign keys, and metric analytics in lake", start_all)
    print(f"ELT SQL build completed in {round(time.time() - start_all, 2)} seconds")

In [ ]:
build_elt_sql_tables(elt_lake_engine)

source1_clean = read_lake_table(elt_lake_engine, "elt_clean_hotel_bookings")
source2_clean = read_lake_table(elt_lake_engine, "elt_clean_hotel_reviews")

print("ELT SQL-cleaned Source 1 shape:", source1_clean.shape)
print("ELT SQL-cleaned Source 2 shape:", source2_clean.shape)
display(source1_clean.head())
display(source2_clean.head())

print("Primary key checks after SQL cleaning")
display(pd.DataFrame([
    {"dataset": "elt_clean_hotel_bookings", "primary_key": "booking_id", "is_unique": source1_clean["booking_id"].is_unique, "null_count": int(source1_clean["booking_id"].isna().sum())},
    {"dataset": "elt_clean_hotel_reviews", "primary_key": "review_id", "is_unique": source2_clean["review_id"].is_unique, "null_count": int(source2_clean["review_id"].isna().sum())},
]))

Detected booking columns: 32
Detected review columns: 17
Finished: Create SQL-cleaned hotel bookings in 5.04 seconds
Finished: Add SQL frequency encoding to bookings in 1.91 seconds
Finished: Prepare SQL review encoding and normalization statistics in 5.61 seconds
Finished: Create SQL-cleaned hotel reviews with encoding and normalization in 18.57 seconds
Finished: Create ELT snowflake dimensions in 3.61 seconds
Finished: Create ELT fact tables in 3.21 seconds
Finished: Create ELT aggregation and metric analytics tables in 2.26 seconds
ELT SQL build completed in 40.21 seconds
ELT SQL-cleaned Source 1 shape: (119390, 49)
ELT SQL-cleaned Source 2 shape: (515738, 30)

,booking_id,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_guests,total_nights,zero_guest_flag,zero_night_flag,has_agent,has_company,room_changed,arrival_date,lead_time_minmax,adr_minmax,total_nights_minmax,total_guests_minmax,source_duplicate_flag,outlier_count,market_segment_freq_encoded,customer_type_freq_encoded
0,1,Resort Hotel,0,342.0,2015,July,27,1,0.0,0.0,2.0,0.0,0.0,BB,PRT,Direct,Direct,0,0.0,0.0,C,C,3.0,No Deposit,Unknown,Unknown,0.0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01,2.0,0.0,0,1,0,0,0,2015-07-01,0.464043,0.000000,0.000000,0.036364,0,0,0.105587,0.750591
1,2,Resort Hotel,0,737.0,2015,July,27,1,0.0,0.0,2.0,0.0,0.0,BB,PRT,Direct,Direct,0,0.0,0.0,C,C,4.0,No Deposit,Unknown,Unknown,0.0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01,2.0,0.0,0,1,0,0,0,2015-07-01,1.000000,0.000000,0.000000,0.036364,0,0,0.105587,0.750591
2,3,Resort Hotel,0,7.0,2015,July,27,1,0.0,1.0,1.0,0.0,0.0,BB,GBR,Direct,Direct,0,0.0,0.0,A,C,0.0,No Deposit,Unknown,Unknown,0.0,Transient,75.0,0.0,0.0,Check-Out,2015-07-02,1.0,1.0,0,0,0,0,1,2015-07-01,0.009498,0.013889,0.014493,0.018182,0,0,0.105587,0.750591
3,4,Resort Hotel,0,13.0,2015,July,27,1,0.0,1.0,1.0,0.0,0.0,BB,GBR,Corporate,Corporate,0,0.0,0.0,A,A,0.0,No Deposit,304.0,Unknown,0.0,Transient,75.0,0.0,0.0,Check-Out,2015-07-02,1.0,1.0,0,0,1,0,0,2015-07-01,0.017639,0.013889,0.014493,0.018182,0,0,0.044350,0.750591
4,5,Resort Hotel,0,14.0,2015,July,27,1,0.0,2.0,2.0,0.0,0.0,BB,GBR,Online TA,TA/TO,0,0.0,0.0,A,A,0.0,No Deposit,240.0,Unknown,0.0,Transient,98.0,0.0,1.0,Check-Out,2015-07-03,2.0,2.0,0,0,1,0,0,2015-07-01,0.018996,0.018148,0.028986,0.036364,0,0,0.473046,0.750591

,review_id,hotel_address,additional_number_of_scoring,average_score,hotel_name,reviewer_nationality,negative_review,negative_review_word_count,total_number_of_reviews,positive_review,positive_review_word_count,total_number_of_reviews_reviewer_has_given,reviewer_score,tags,lat,lng,review_date,days_since_review_numeric,positive_review_length,negative_review_length,sentiment_word_balance,tag_count,source_duplicate_flag,outlier_count,average_score_minmax,reviewer_score_minmax,positive_review_word_count_minmax,negative_review_word_count_minmax,reviewer_nationality_freq_encoded,hotel_name_freq_encoded
0,1,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194.0,7.7,Hotel Arena,Russia,I am so angry that i made this post available via all possible sites i use when planing my trips so no one will make the mistake of booking this place I made my booking via boo...,397.0,1403.0,Only the park outside of the hotel was beautiful,11.0,7.0,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double Room ', ' Stayed 6 nights ']",52.360576,4.915968,2017-08-03,0,48,1861,-386.0,4,0,0,0.543478,0.053333,0.027848,0.973039,0.007562,0.000785
1,2,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194.0,7.7,Hotel Arena,Ireland,No Negative,0.0,1403.0,No real complaints the hotel was great great location surroundings rooms amenities and service Two recommendations however firstly the staff upon check in are very confusing re...,105.0,7.0,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double Room ', ' Stayed 4 nights ']",52.360576,4.915968,2017-08-03,0,609,11,105.0,4,0,0,0.543478,0.666667,0.265823,0.000000,0.028749,0.000785
2,3,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194.0,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficult as most rooms are two story with narrow steps So ask for single level Inside the rooms are very very basic just tea coffee and bo...,42.0,1403.0,Location was good and staff were ok It is cute hotel the breakfast range is nice Will go back,21.0,9.0,7.1,"[' Leisure trip ', ' Family with young children ', ' Duplex Double Room ', ' Stayed 3 nights ', ' Submitted from a mobile device ']",52.360576,4.915968,2017-07-31,3,93,204,-21.0,5,0,0,0.543478,0.613333,0.053165,0.102941,0.042048,0.000785
3,4,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194.0,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk barefoot on the floor which looked as if it was not cleaned in weeks White furniture which looked nice in pictures was dirty too and ...,210.0,1403.0,Great location in nice surroundings the bar and restaurant are nice and have a lovely outdoor area The building also has quite some character,26.0,1.0,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex Double Room ', ' Stayed 3 nights ']",52.360576,4.915968,2017-07-31,3,141,1076,-184.0,4,0,0,0.543478,0.173333,0.065823,0.514706,0.475524,0.000785
4,5,s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands,194.0,7.7,Hotel Arena,New Zealand,You When I booked with your company on line you showed me pictures of a room I thought I was getting and paying for and then when we arrived that s room was booked and the staf...,140.0,1403.0,Amazing location and building Romantic setting,8.0,3.0,6.7,"[' Leisure trip ', ' Couple ', ' Suite ', ' Stayed 2 nights ', ' Submitted from a mobile device ']",52.360576,4.915968,2017-07-24,10,46,724,-132.0,5,0,0,0.543478,0.560000,0.020253,0.343137,0.006276,0.000785

Primary key checks after SQL cleaning

                    dataset primary_key  is_unique  null_count
0  elt_clean_hotel_bookings  booking_id       True           0
1   elt_clean_hotel_reviews   review_id       True           0

### Clean Overview Reports and Frequency Displays

In [ ]:
source1_clean_overview_summary, source1_clean_column_overview = overview_report(source1_clean, "Source 1 - Hotel Bookings SQL Clean")
source2_clean_overview_summary, source2_clean_column_overview = overview_report(source2_clean, "Source 2 - Hotel Reviews SQL Clean")

source1_clean_memory_report = memory_usage_report(source1_clean, "Source 1 - Hotel Bookings SQL Clean")
source2_clean_memory_report = memory_usage_report(source2_clean, "Source 2 - Hotel Reviews SQL Clean")

source1_clean_frequency = frequency_display(source1_clean, "Source 1 - Hotel Bookings SQL Clean")
source2_clean_frequency = frequency_display(source2_clean, "Source 2 - Hotel Reviews SQL Clean")

source1_clean_unusual_report = unusual_values_report(source1_clean, "Source 1 - Hotel Bookings SQL Clean")
source2_clean_unusual_report = unusual_values_report(source2_clean, "Source 2 - Hotel Reviews SQL Clean")

source1_clean_datatype_report = datatype_consistency_report(source1_clean, "Source 1 - Hotel Bookings SQL Clean")
source2_clean_datatype_report = datatype_consistency_report(source2_clean, "Source 2 - Hotel Reviews SQL Clean")

source1_clean_distribution_report = data_distribution_report(source1_clean, "Source 1 - Hotel Bookings SQL Clean")
source2_clean_distribution_report = data_distribution_report(source2_clean, "Source 2 - Hotel Reviews SQL Clean")

Overview report - Source 1 - Hotel Bookings SQL Clean

,dataset,rows,columns,cells,duplicated_rows,missing_cells,missing_cell_pct,unusual_value_cells,memory_mb,numeric_columns,categorical_columns,datetime_columns,execution_seconds
0,Source 1 - Hotel Bookings SQL Clean,119390,49,5850110,0,0,0.0,129421,125.8117,34,15,0,3.4195

,dataset,column,dtype,non_null_count,null_count,null_pct,unique_count,unique_pct,sample_values,memory_mb
0,Source 1 - Hotel Bookings SQL Clean,booking_id,int64,119390,0,0.0,119390,100.0000,"1, 2, 3",0.9109
1,Source 1 - Hotel Bookings SQL Clean,hotel,object,119390,0,0.0,2,0.0017,"Resort Hotel, City Hotel",6.7941
2,Source 1 - Hotel Bookings SQL Clean,is_canceled,int64,119390,0,0.0,2,0.0017,"0, 1",0.9109
3,Source 1 - Hotel Bookings SQL Clean,lead_time,float64,119390,0,0.0,479,0.4012,"342.0, 737.0, 7.0",0.9109
4,Source 1 - Hotel Bookings SQL Clean,arrival_date_year,int64,119390,0,0.0,3,0.0025,"2015, 2016, 2017",0.9109
5,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,object,119390,0,0.0,12,0.0101,"July, August, September",6.2512
6,Source 1 - Hotel Bookings SQL Clean,arrival_date_week_number,int64,119390,0,0.0,53,0.0444,"27, 28, 29",0.9109
7,Source 1 - Hotel Bookings SQL Clean,arrival_date_day_of_month,int64,119390,0,0.0,31,0.0260,"1, 2, 3",0.9109
8,Source 1 - Hotel Bookings SQL Clean,stays_in_weekend_nights,float64,119390,0,0.0,17,0.0142,"0.0, 1.0, 2.0",0.9109
9,Source 1 - Hotel Bookings SQL Clean,stays_in_week_nights,float64,119390,0,0.0,35,0.0293,"0.0, 1.0, 2.0",0.9109
10,Source 1 - Hotel Bookings SQL Clean,adults,float64,119390,0,0.0,14,0.0117,"2.0, 1.0, 3.0",0.9109
11,Source 1 - Hotel Bookings SQL Clean,children,float64,119390,0,0.0,5,0.0042,"0.0, 1.0, 2.0",0.9109
12,Source 1 - Hotel Bookings SQL Clean,babies,float64,119390,0,0.0,5,0.0042,"0.0, 1.0, 2.0",0.9109
13,Source 1 - Hotel Bookings SQL Clean,meal,object,119390,0,0.0,5,0.0042,"BB, FB, HB",5.8146
14,Source 1 - Hotel Bookings SQL Clean,country,object,119390,0,0.0,178,0.1491,"PRT, GBR, USA",5.9213
15,Source 1 - Hotel Bookings SQL Clean,market_segment,object,119390,0,0.0,8,0.0067,"Direct, Corporate, Online TA",6.6061
16,Source 1 - Hotel Bookings SQL Clean,distribution_channel,object,119390,0,0.0,5,0.0042,"Direct, Corporate, TA/TO",6.1875
17,Source 1 - Hotel Bookings SQL Clean,is_repeated_guest,int64,119390,0,0.0,2,0.0017,"0, 1",0.9109
18,Source 1 - Hotel Bookings SQL Clean,previous_cancellations,float64,119390,0,0.0,15,0.0126,"0.0, 1.0, 2.0",0.9109
19,Source 1 - Hotel Bookings SQL Clean,previous_bookings_not_canceled,float64,119390,0,0.0,73,0.0611,"0.0, 1.0, 2.0",0.9109
20,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,object,119390,0,0.0,10,0.0084,"C, A, D",5.6930
21,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,object,119390,0,0.0,12,0.0101,"C, A, D",5.6930
22,Source 1 - Hotel Bookings SQL Clean,booking_changes,float64,119390,0,0.0,21,0.0176,"3.0, 4.0, 0.0",0.9109
23,Source 1 - Hotel Bookings SQL Clean,deposit_type,object,119390,0,0.0,3,0.0025,"No Deposit, Refundable, Non Refund",6.7177
24,Source 1 - Hotel Bookings SQL Clean,agent,object,119390,0,0.0,334,0.2798,"Unknown, 304.0, 240.0",6.0652
25,Source 1 - Hotel Bookings SQL Clean,company,object,119390,0,0.0,353,0.2957,"Unknown, 110.0, 113.0",6.3609
26,Source 1 - Hotel Bookings SQL Clean,days_in_waiting_list,float64,119390,0,0.0,128,0.1072,"0.0, 50.0, 47.0",0.9109
27,Source 1 - Hotel Bookings SQL Clean,customer_type,object,119390,0,0.0,4,0.0034,"Transient, Contract, Transient-Party",6.7415
28,Source 1 - Hotel Bookings SQL Clean,adr,float64,119390,0,0.0,8878,7.4361,"0.0, 75.0, 98.0",0.9109
29,Source 1 - Hotel Bookings SQL Clean,required_car_parking_spaces,float64,119390,0,0.0,5,0.0042,"0.0, 1.0, 2.0",0.9109
30,Source 1 - Hotel Bookings SQL Clean,total_of_special_requests,float64,119390,0,0.0,6,0.0050,"0.0, 1.0, 3.0",0.9109
31,Source 1 - Hotel Bookings SQL Clean,reservation_status,object,119390,0,0.0,3,0.0025,"Check-Out, Canceled, No-Show",6.5605
32,Source 1 - Hotel Bookings SQL Clean,reservation_status_date,object,119390,0,0.0,926,0.7756,"2015-07-01, 2015-07-02, 2015-07-03",6.7177
33,Source 1 - Hotel Bookings SQL Clean,total_guests,float64,119390,0,0.0,15,0.0126,"2.0, 1.0, 3.0",0.9109
34,Source 1 - Hotel Bookings SQL Clean,total_nights,float64,119390,0,0.0,45,0.0377,"0.0, 1.0, 2.0",0.9109
35,Source 1 - Hotel Bookings SQL Clean,zero_guest_flag,int64,119390,0,0.0,2,0.0017,"0, 1",0.9109
36,Source 1 - Hotel Bookings SQL Clean,zero_night_flag,int64,119390,0,0.0,2,0.0017,"1, 0",0.9109
37,Source 1 - Hotel Bookings SQL Clean,has_agent,int64,119390,0,0.0,2,0.0017,"0, 1",0.9109
38,Source 1 - Hotel Bookings SQL Clean,has_company,int64,119390,0,0.0,2,0.0017,"0, 1",0.9109
39,Source 1 - Hotel Bookings SQL Clean,room_changed,int64,119390,0,0.0,2,0.0017,"0, 1",0.9109
40,Source 1 - Hotel Bookings SQL Clean,arrival_date,object,119390,0,0.0,728,0.6098,"2015-07-01, 2015-07-02, 2015-07-03",6.7177
41,Source 1 - Hotel Bookings SQL Clean,lead_time_minmax,float64,119390,0,0.0,479,0.4012,"0.464043, 1.0, 0.009498",0.9109
42,Source 1 - Hotel Bookings SQL Clean,adr_minmax,float64,119390,0,0.0,8878,7.4361,"0.0, 0.013889, 0.018148",0.9109
43,Source 1 - Hotel Bookings SQL Clean,total_nights_minmax,float64,119390,0,0.0,45,0.0377,"0.0, 0.014493, 0.028986",0.9109
44,Source 1 - Hotel Bookings SQL Clean,total_guests_minmax,float64,119390,0,0.0,15,0.0126,"0.036364, 0.018182, 0.054545",0.9109
45,Source 1 - Hotel Bookings SQL Clean,source_duplicate_flag,int64,119390,0,0.0,1,0.0008,0,0.9109
46,Source 1 - Hotel Bookings SQL Clean,outlier_count,int64,119390,0,0.0,1,0.0008,0,0.9109
47,Source 1 - Hotel Bookings SQL Clean,market_segment_freq_encoded,float64,119390,0,0.0,8,0.0067,"0.1055867325571656, 0.044350448111232094, 0.47304631878716813",0.9109
48,Source 1 - Hotel Bookings SQL Clean,customer_type_freq_encoded,float64,119390,0,0.0,4,0.0034,"0.7505905017170618, 0.03414021274813636, 0.21043638495686406",0.9109

Overview report - Source 2 - Hotel Reviews SQL Clean

,dataset,rows,columns,cells,duplicated_rows,missing_cells,missing_cell_pct,unusual_value_cells,memory_mb,numeric_columns,categorical_columns,datetime_columns,execution_seconds
0,Source 2 - Hotel Reviews SQL Clean,515738,30,15472140,0,0,0.0,167082,453.6895,23,7,0,4.4934

,dataset,column,dtype,non_null_count,null_count,null_pct,unique_count,unique_pct,sample_values,memory_mb
0,Source 2 - Hotel Reviews SQL Clean,review_id,int64,515738,0,0.0,515738,100.0000,"1, 2, 3",3.9348
1,Source 2 - Hotel Reviews SQL Clean,hotel_address,object,515738,0,0.0,1493,0.2895,"s Gravesandestraat 55 Oost 1092 AA Amsterdam Netherlands, 1 15 Templeton Place Earl s Court Kensington and Chelsea London SW5 9NB United Kingdom, 1 2 Serjeant s Inn Fleet Stree...",53.5515
2,Source 2 - Hotel Reviews SQL Clean,additional_number_of_scoring,float64,515738,0,0.0,480,0.0931,"194.0, 244.0, 639.0",3.9348
3,Source 2 - Hotel Reviews SQL Clean,average_score,float64,515738,0,0.0,34,0.0066,"7.7, 8.5, 9.2",3.9348
4,Source 2 - Hotel Reviews SQL Clean,hotel_name,object,515738,0,0.0,1492,0.2893,"Hotel Arena, K K Hotel George, Apex Temple Court Hotel",36.5458
5,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,object,515738,0,0.0,227,0.0440,"Russia, Ireland, Australia",30.0210
6,Source 2 - Hotel Reviews SQL Clean,negative_review,object,515738,0,0.0,326566,63.3201,I am so angry that i made this post available via all possible sites i use when planing my trips so no one will make the mistake of booking this place I made my booking via boo...,69.6516
7,Source 2 - Hotel Reviews SQL Clean,negative_review_word_count,float64,515738,0,0.0,402,0.0779,"397.0, 0.0, 42.0",3.9348
8,Source 2 - Hotel Reviews SQL Clean,total_number_of_reviews,float64,515738,0,0.0,1142,0.2214,"1403.0, 1831.0, 2619.0",3.9348
9,Source 2 - Hotel Reviews SQL Clean,positive_review,object,515738,0,0.0,407552,79.0231,"Only the park outside of the hotel was beautiful, No real complaints the hotel was great great location surroundings rooms amenities and service Two recommendations however fir...",69.9266
10,Source 2 - Hotel Reviews SQL Clean,positive_review_word_count,float64,515738,0,0.0,365,0.0708,"11.0, 105.0, 21.0",3.9348
11,Source 2 - Hotel Reviews SQL Clean,total_number_of_reviews_reviewer_has_given,float64,515738,0,0.0,198,0.0384,"7.0, 9.0, 1.0",3.9348
12,Source 2 - Hotel Reviews SQL Clean,reviewer_score,float64,515738,0,0.0,37,0.0072,"2.9, 7.5, 7.1",3.9348
13,Source 2 - Hotel Reviews SQL Clean,tags,object,515738,0,0.0,55242,10.7113,"[' Leisure trip ', ' Couple ', ' Duplex Double Room ', ' Stayed 6 nights '], [' Leisure trip ', ' Couple ', ' Duplex Double Room ', ' Stayed 4 nights '], [' Leisure trip ', ' F...",74.4743
14,Source 2 - Hotel Reviews SQL Clean,lat,float64,515738,0,0.0,1473,0.2856,"52.3605759, 51.4918878, 51.5137335",3.9348
15,Source 2 - Hotel Reviews SQL Clean,lng,float64,515738,0,0.0,1473,0.2856,"4.9159683, -0.1949706, -0.1087512",3.9348
16,Source 2 - Hotel Reviews SQL Clean,review_date,object,515738,0,0.0,731,0.1417,"2017-08-03, 2017-07-31, 2017-07-24",29.0189
17,Source 2 - Hotel Reviews SQL Clean,days_since_review_numeric,int64,515738,0,0.0,731,0.1417,"0, 3, 10",3.9348
18,Source 2 - Hotel Reviews SQL Clean,positive_review_length,int64,515738,0,0.0,1455,0.2821,"48, 609, 93",3.9348
19,Source 2 - Hotel Reviews SQL Clean,negative_review_length,int64,515738,0,0.0,1789,0.3469,"1861, 11, 204",3.9348
20,Source 2 - Hotel Reviews SQL Clean,sentiment_word_balance,float64,515738,0,0.0,737,0.1429,"-386.0, 105.0, -21.0",3.9348
21,Source 2 - Hotel Reviews SQL Clean,tag_count,int64,515738,0,0.0,6,0.0012,"4, 5, 3",3.9348
22,Source 2 - Hotel Reviews SQL Clean,source_duplicate_flag,int64,515738,0,0.0,1,0.0002,0,3.9348
23,Source 2 - Hotel Reviews SQL Clean,outlier_count,int64,515738,0,0.0,1,0.0002,0,3.9348
24,Source 2 - Hotel Reviews SQL Clean,average_score_minmax,float64,515738,0,0.0,34,0.0066,"0.543478, 0.717391, 0.869565",3.9348
25,Source 2 - Hotel Reviews SQL Clean,reviewer_score_minmax,float64,515738,0,0.0,37,0.0072,"0.053333, 0.666667, 0.613333",3.9348
26,Source 2 - Hotel Reviews SQL Clean,positive_review_word_count_minmax,float64,515738,0,0.0,365,0.0708,"0.027848, 0.265823, 0.053165",3.9348
27,Source 2 - Hotel Reviews SQL Clean,negative_review_word_count_minmax,float64,515738,0,0.0,402,0.0779,"0.973039, 0.0, 0.102941",3.9348
28,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality_freq_encoded,float64,515738,0,0.0,148,0.0287,"0.0075619791444493135, 0.028749093531987173, 0.04204848198116098",3.9348
29,Source 2 - Hotel Reviews SQL Clean,hotel_name_freq_encoded,float64,515738,0,0.0,663,0.1286,"0.0007852824496158902, 0.001097456460450849, 0.0020107108648189584",3.9348

Memory usage report - Source 1 - Hotel Bookings SQL Clean

,dataset,column,memory_bytes,memory_mb
0,Source 1 - Hotel Bookings SQL Clean,hotel,7124130,6.7941
1,Source 1 - Hotel Bookings SQL Clean,customer_type,7068980,6.7415
2,Source 1 - Hotel Bookings SQL Clean,arrival_date,7044010,6.7177
3,Source 1 - Hotel Bookings SQL Clean,reservation_status_date,7044010,6.7177
4,Source 1 - Hotel Bookings SQL Clean,deposit_type,7044010,6.7177
5,Source 1 - Hotel Bookings SQL Clean,market_segment,6926980,6.6061
6,Source 1 - Hotel Bookings SQL Clean,reservation_status,6879189,6.5605
7,Source 1 - Hotel Bookings SQL Clean,company,6669849,6.3609
8,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,6554891,6.2512
9,Source 1 - Hotel Bookings SQL Clean,distribution_channel,6488047,6.1875
10,Source 1 - Hotel Bookings SQL Clean,agent,6359845,6.0652
11,Source 1 - Hotel Bookings SQL Clean,country,6208953,5.9213
12,Source 1 - Hotel Bookings SQL Clean,meal,6097073,5.8146
13,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,5969500,5.6930
14,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,5969500,5.6930
15,Source 1 - Hotel Bookings SQL Clean,stays_in_weekend_nights,955120,0.9109
16,Source 1 - Hotel Bookings SQL Clean,lead_time,955120,0.9109
17,Source 1 - Hotel Bookings SQL Clean,booking_id,955120,0.9109
18,Source 1 - Hotel Bookings SQL Clean,required_car_parking_spaces,955120,0.9109
19,Source 1 - Hotel Bookings SQL Clean,stays_in_week_nights,955120,0.9109
20,Source 1 - Hotel Bookings SQL Clean,children,955120,0.9109
21,Source 1 - Hotel Bookings SQL Clean,adults,955120,0.9109
22,Source 1 - Hotel Bookings SQL Clean,arrival_date_year,955120,0.9109
23,Source 1 - Hotel Bookings SQL Clean,arrival_date_week_number,955120,0.9109
24,Source 1 - Hotel Bookings SQL Clean,arrival_date_day_of_month,955120,0.9109
25,Source 1 - Hotel Bookings SQL Clean,babies,955120,0.9109
26,Source 1 - Hotel Bookings SQL Clean,is_canceled,955120,0.9109
27,Source 1 - Hotel Bookings SQL Clean,booking_changes,955120,0.9109
28,Source 1 - Hotel Bookings SQL Clean,previous_cancellations,955120,0.9109
29,Source 1 - Hotel Bookings SQL Clean,is_repeated_guest,955120,0.9109
30,Source 1 - Hotel Bookings SQL Clean,adr,955120,0.9109
31,Source 1 - Hotel Bookings SQL Clean,days_in_waiting_list,955120,0.9109
32,Source 1 - Hotel Bookings SQL Clean,total_of_special_requests,955120,0.9109
33,Source 1 - Hotel Bookings SQL Clean,previous_bookings_not_canceled,955120,0.9109
34,Source 1 - Hotel Bookings SQL Clean,lead_time_minmax,955120,0.9109
35,Source 1 - Hotel Bookings SQL Clean,total_guests,955120,0.9109
36,Source 1 - Hotel Bookings SQL Clean,zero_guest_flag,955120,0.9109
37,Source 1 - Hotel Bookings SQL Clean,total_nights,955120,0.9109
38,Source 1 - Hotel Bookings SQL Clean,zero_night_flag,955120,0.9109
39,Source 1 - Hotel Bookings SQL Clean,has_agent,955120,0.9109
40,Source 1 - Hotel Bookings SQL Clean,has_company,955120,0.9109
41,Source 1 - Hotel Bookings SQL Clean,room_changed,955120,0.9109
42,Source 1 - Hotel Bookings SQL Clean,source_duplicate_flag,955120,0.9109
43,Source 1 - Hotel Bookings SQL Clean,adr_minmax,955120,0.9109
44,Source 1 - Hotel Bookings SQL Clean,total_nights_minmax,955120,0.9109
45,Source 1 - Hotel Bookings SQL Clean,total_guests_minmax,955120,0.9109
46,Source 1 - Hotel Bookings SQL Clean,market_segment_freq_encoded,955120,0.9109
47,Source 1 - Hotel Bookings SQL Clean,outlier_count,955120,0.9109
48,Source 1 - Hotel Bookings SQL Clean,customer_type_freq_encoded,955120,0.9109
49,Source 1 - Hotel Bookings SQL Clean,Index,132,0.0001

Memory usage report - Source 2 - Hotel Reviews SQL Clean

,dataset,column,memory_bytes,memory_mb
0,Source 2 - Hotel Reviews SQL Clean,tags,78091984,74.4743
1,Source 2 - Hotel Reviews SQL Clean,positive_review,73323339,69.9266
2,Source 2 - Hotel Reviews SQL Clean,negative_review,73035040,69.6516
3,Source 2 - Hotel Reviews SQL Clean,hotel_address,56152817,53.5515
4,Source 2 - Hotel Reviews SQL Clean,hotel_name,38321068,36.5458
5,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,31479248,30.0210
6,Source 2 - Hotel Reviews SQL Clean,review_date,30428542,29.0189
7,Source 2 - Hotel Reviews SQL Clean,total_number_of_reviews,4125904,3.9348
8,Source 2 - Hotel Reviews SQL Clean,additional_number_of_scoring,4125904,3.9348
9,Source 2 - Hotel Reviews SQL Clean,review_id,4125904,3.9348
10,Source 2 - Hotel Reviews SQL Clean,negative_review_word_count,4125904,3.9348
11,Source 2 - Hotel Reviews SQL Clean,total_number_of_reviews_reviewer_has_given,4125904,3.9348
12,Source 2 - Hotel Reviews SQL Clean,positive_review_word_count,4125904,3.9348
13,Source 2 - Hotel Reviews SQL Clean,reviewer_score,4125904,3.9348
14,Source 2 - Hotel Reviews SQL Clean,average_score,4125904,3.9348
15,Source 2 - Hotel Reviews SQL Clean,source_duplicate_flag,4125904,3.9348
16,Source 2 - Hotel Reviews SQL Clean,lat,4125904,3.9348
17,Source 2 - Hotel Reviews SQL Clean,lng,4125904,3.9348
18,Source 2 - Hotel Reviews SQL Clean,days_since_review_numeric,4125904,3.9348
19,Source 2 - Hotel Reviews SQL Clean,positive_review_length,4125904,3.9348
20,Source 2 - Hotel Reviews SQL Clean,negative_review_length,4125904,3.9348
21,Source 2 - Hotel Reviews SQL Clean,sentiment_word_balance,4125904,3.9348
22,Source 2 - Hotel Reviews SQL Clean,tag_count,4125904,3.9348
23,Source 2 - Hotel Reviews SQL Clean,positive_review_word_count_minmax,4125904,3.9348
24,Source 2 - Hotel Reviews SQL Clean,outlier_count,4125904,3.9348
25,Source 2 - Hotel Reviews SQL Clean,average_score_minmax,4125904,3.9348
26,Source 2 - Hotel Reviews SQL Clean,reviewer_score_minmax,4125904,3.9348
27,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality_freq_encoded,4125904,3.9348
28,Source 2 - Hotel Reviews SQL Clean,negative_review_word_count_minmax,4125904,3.9348
29,Source 2 - Hotel Reviews SQL Clean,hotel_name_freq_encoded,4125904,3.9348
30,Source 2 - Hotel Reviews SQL Clean,Index,132,0.0001

Frequency display - Source 1 - Hotel Bookings SQL Clean - hotel

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings SQL Clean,hotel,City Hotel,79330,66.4461
1,Source 1 - Hotel Bookings SQL Clean,hotel,Resort Hotel,40060,33.5539

Frequency display - Source 1 - Hotel Bookings SQL Clean - arrival_date_month

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,August,13877,11.6233
1,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,July,12661,10.6047
2,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,May,11791,9.876
3,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,October,11160,9.3475
4,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,April,11089,9.288
5,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,June,10939,9.1624
6,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,September,10508,8.8014
7,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,March,9794,8.2034
8,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,February,8068,6.7577
9,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,November,6794,5.6906
10,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,December,6780,5.6789
11,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,January,5929,4.9661

Frequency display - Source 1 - Hotel Bookings SQL Clean - meal

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings SQL Clean,meal,BB,92310,77.318
1,Source 1 - Hotel Bookings SQL Clean,meal,HB,14463,12.1141
2,Source 1 - Hotel Bookings SQL Clean,meal,SC,10650,8.9203
3,Source 1 - Hotel Bookings SQL Clean,meal,Undefined,1169,0.9791
4,Source 1 - Hotel Bookings SQL Clean,meal,FB,798,0.6684

Frequency display - Source 1 - Hotel Bookings SQL Clean - country

                                dataset   column value  frequency  percentage
0   Source 1 - Hotel Bookings SQL Clean  country   PRT      48590     40.6986
1   Source 1 - Hotel Bookings SQL Clean  country   GBR      12129     10.1591
2   Source 1 - Hotel Bookings SQL Clean  country   FRA      10415      8.7235
3   Source 1 - Hotel Bookings SQL Clean  country   ESP       8568      7.1765
4   Source 1 - Hotel Bookings SQL Clean  country   DEU       7287      6.1035
5   Source 1 - Hotel Bookings SQL Clean  country   ITA       3766      3.1544
6   Source 1 - Hotel Bookings SQL Clean  country   IRL       3375      2.8269
7   Source 1 - Hotel Bookings SQL Clean  country   BEL       2342      1.9616
8   Source 1 - Hotel Bookings SQL Clean  country   BRA       2224      1.8628
9   Source 1 - Hotel Bookings SQL Clean  country   NLD       2104      1.7623
10  Source 1 - Hotel Bookings SQL Clean  country   USA       2097      1.7564
11  Source 1 - Hotel Bookings SQL Clean  country   CHE       1730       1.449

Frequency display - Source 1 - Hotel Bookings SQL Clean - market_segment

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings SQL Clean,market_segment,Online TA,56477,47.3046
1,Source 1 - Hotel Bookings SQL Clean,market_segment,Offline TA/TO,24219,20.2856
2,Source 1 - Hotel Bookings SQL Clean,market_segment,Groups,19811,16.5935
3,Source 1 - Hotel Bookings SQL Clean,market_segment,Direct,12606,10.5587
4,Source 1 - Hotel Bookings SQL Clean,market_segment,Corporate,5295,4.435
5,Source 1 - Hotel Bookings SQL Clean,market_segment,Complementary,743,0.6223
6,Source 1 - Hotel Bookings SQL Clean,market_segment,Aviation,237,0.1985
7,Source 1 - Hotel Bookings SQL Clean,market_segment,Undefined,2,0.0017

Frequency display - Source 1 - Hotel Bookings SQL Clean - distribution_channel

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings SQL Clean,distribution_channel,TA/TO,97870,81.975
1,Source 1 - Hotel Bookings SQL Clean,distribution_channel,Direct,14645,12.2665
2,Source 1 - Hotel Bookings SQL Clean,distribution_channel,Corporate,6677,5.5926
3,Source 1 - Hotel Bookings SQL Clean,distribution_channel,GDS,193,0.1617
4,Source 1 - Hotel Bookings SQL Clean,distribution_channel,Undefined,5,0.0042

Frequency display - Source 1 - Hotel Bookings SQL Clean - reserved_room_type

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,A,85994,72.0278
1,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,D,19201,16.0826
2,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,E,6535,5.4737
3,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,F,2897,2.4265
4,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,G,2094,1.7539
5,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,B,1118,0.9364
6,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,C,932,0.7806
7,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,H,601,0.5034
8,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,P,12,0.0101
9,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,L,6,0.005

Frequency display - Source 1 - Hotel Bookings SQL Clean - assigned_room_type

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,A,74053,62.0261
1,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,D,25322,21.2095
2,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,E,7806,6.5382
3,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,F,3751,3.1418
4,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,G,2553,2.1384
5,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,C,2375,1.9893
6,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,B,2163,1.8117
7,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,H,712,0.5964
8,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,I,363,0.304
9,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,K,279,0.2337
10,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,P,12,0.0101
11,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,L,1,0.0008

Frequency display - Source 1 - Hotel Bookings SQL Clean - deposit_type

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings SQL Clean,deposit_type,No Deposit,104641,87.6464
1,Source 1 - Hotel Bookings SQL Clean,deposit_type,Non Refund,14587,12.2179
2,Source 1 - Hotel Bookings SQL Clean,deposit_type,Refundable,162,0.1357

Frequency display - Source 1 - Hotel Bookings SQL Clean - agent

                                dataset column    value  frequency  percentage
0   Source 1 - Hotel Bookings SQL Clean  agent      9.0      31961     26.7702
1   Source 1 - Hotel Bookings SQL Clean  agent  Unknown      16340     13.6862
2   Source 1 - Hotel Bookings SQL Clean  agent    240.0      13922     11.6609
3   Source 1 - Hotel Bookings SQL Clean  agent      1.0       7191      6.0231
4   Source 1 - Hotel Bookings SQL Clean  agent     14.0       3640      3.0488
5   Source 1 - Hotel Bookings SQL Clean  agent      7.0       3539      2.9642
6   Source 1 - Hotel Bookings SQL Clean  agent      6.0       3290      2.7557
7   Source 1 - Hotel Bookings SQL Clean  agent    250.0       2870      2.4039
8   Source 1 - Hotel Bookings SQL Clean  agent    241.0       1721      1.4415
9   Source 1 - Hotel Bookings SQL Clean  agent     28.0       1666      1.3954
10  Source 1 - Hotel Bookings SQL Clean  agent      8.0       1514      1.2681
11  Source 1 - Hotel Bookings SQL Clean  agent      3.0       1336       1.119

Frequency display - Source 1 - Hotel Bookings SQL Clean - company

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings SQL Clean,company,Unknown,112593,94.3069
1,Source 1 - Hotel Bookings SQL Clean,company,40.0,927,0.7764
2,Source 1 - Hotel Bookings SQL Clean,company,223.0,784,0.6567
3,Source 1 - Hotel Bookings SQL Clean,company,67.0,267,0.2236
4,Source 1 - Hotel Bookings SQL Clean,company,45.0,250,0.2094
5,Source 1 - Hotel Bookings SQL Clean,company,153.0,215,0.1801
6,Source 1 - Hotel Bookings SQL Clean,company,174.0,149,0.1248
7,Source 1 - Hotel Bookings SQL Clean,company,219.0,141,0.1181
8,Source 1 - Hotel Bookings SQL Clean,company,281.0,138,0.1156
9,Source 1 - Hotel Bookings SQL Clean,company,154.0,133,0.1114
10,Source 1 - Hotel Bookings SQL Clean,company,405.0,119,0.0997
11,Source 1 - Hotel Bookings SQL Clean,company,233.0,114,0.0955

Frequency display - Source 1 - Hotel Bookings SQL Clean - customer_type

,dataset,column,value,frequency,percentage
0,Source 1 - Hotel Bookings SQL Clean,customer_type,Transient,89613,75.0591
1,Source 1 - Hotel Bookings SQL Clean,customer_type,Transient-Party,25124,21.0436
2,Source 1 - Hotel Bookings SQL Clean,customer_type,Contract,4076,3.414
3,Source 1 - Hotel Bookings SQL Clean,customer_type,Group,577,0.4833

Frequency display - Source 2 - Hotel Reviews SQL Clean - hotel_address

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews SQL Clean,hotel_address,163 Marsh Wall Docklands Tower Hamlets London E14 9SJ United Kingdom,4789,0.9286
1,Source 2 - Hotel Reviews SQL Clean,hotel_address,372 Strand Westminster Borough London WC2R 0JJ United Kingdom,4256,0.8252
2,Source 2 - Hotel Reviews SQL Clean,hotel_address,Westminster Bridge Road Lambeth London SE1 7UT United Kingdom,4169,0.8084
3,Source 2 - Hotel Reviews SQL Clean,hotel_address,Scarsdale Place Kensington Kensington and Chelsea London W8 5SY United Kingdom,3578,0.6938
4,Source 2 - Hotel Reviews SQL Clean,hotel_address,7 Pepys Street City of London London EC3N 4AF United Kingdom,3212,0.6228
5,Source 2 - Hotel Reviews SQL Clean,hotel_address,1 Inverness Terrace Westminster Borough London W2 3JP United Kingdom,2958,0.5735
6,Source 2 - Hotel Reviews SQL Clean,hotel_address,Wrights Lane Kensington and Chelsea London W8 5SP United Kingdom,2768,0.5367
7,Source 2 - Hotel Reviews SQL Clean,hotel_address,225 Edgware Road Westminster Borough London W2 1JU United Kingdom,2628,0.5096
8,Source 2 - Hotel Reviews SQL Clean,hotel_address,4 18 Harrington Gardens Kensington and Chelsea London SW7 4LH United Kingdom,2565,0.4973
9,Source 2 - Hotel Reviews SQL Clean,hotel_address,1 Waterview Drive Greenwich London SE10 0TW United Kingdom,2551,0.4946
10,Source 2 - Hotel Reviews SQL Clean,hotel_address,27 Devonshire Terrace Westminster Borough London W2 3DP United Kingdom,2288,0.4436
11,Source 2 - Hotel Reviews SQL Clean,hotel_address,Lakeside Way Brent London HA9 0BU United Kingdom,2227,0.4318

Frequency display - Source 2 - Hotel Reviews SQL Clean - hotel_name

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews SQL Clean,hotel_name,Britannia International Hotel Canary Wharf,4789,0.9286
1,Source 2 - Hotel Reviews SQL Clean,hotel_name,Strand Palace Hotel,4256,0.8252
2,Source 2 - Hotel Reviews SQL Clean,hotel_name,Park Plaza Westminster Bridge London,4169,0.8084
3,Source 2 - Hotel Reviews SQL Clean,hotel_name,Copthorne Tara Hotel London Kensington,3578,0.6938
4,Source 2 - Hotel Reviews SQL Clean,hotel_name,DoubleTree by Hilton Hotel London Tower of London,3212,0.6228
5,Source 2 - Hotel Reviews SQL Clean,hotel_name,Grand Royale London Hyde Park,2958,0.5735
6,Source 2 - Hotel Reviews SQL Clean,hotel_name,Holiday Inn London Kensington,2768,0.5367
7,Source 2 - Hotel Reviews SQL Clean,hotel_name,Hilton London Metropole,2628,0.5096
8,Source 2 - Hotel Reviews SQL Clean,hotel_name,Millennium Gloucester Hotel London,2565,0.4973
9,Source 2 - Hotel Reviews SQL Clean,hotel_name,Intercontinental London The O2,2551,0.4946
10,Source 2 - Hotel Reviews SQL Clean,hotel_name,Park Grand Paddington Court,2288,0.4436
11,Source 2 - Hotel Reviews SQL Clean,hotel_name,Hilton London Wembley,2227,0.4318

Frequency display - Source 2 - Hotel Reviews SQL Clean - reviewer_nationality

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,United Kingdom,245246,47.5524
1,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,United States of America,35437,6.8711
2,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,Australia,21686,4.2048
3,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,Ireland,14827,2.8749
4,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,United Arab Emirates,10235,1.9845
5,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,Saudi Arabia,8951,1.7356
6,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,Netherlands,8772,1.7009
7,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,Switzerland,8678,1.6826
8,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,Germany,7941,1.5397
9,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,Canada,7894,1.5306
10,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,France,7296,1.4147
11,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,Israel,6610,1.2817

Frequency display - Source 2 - Hotel Reviews SQL Clean - negative_review

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews SQL Clean,negative_review,No Negative,127890,24.7975
1,Source 2 - Hotel Reviews SQL Clean,negative_review,Nothing,18531,3.5931
2,Source 2 - Hotel Reviews SQL Clean,negative_review,nothing,2508,0.4863
3,Source 2 - Hotel Reviews SQL Clean,negative_review,None,1166,0.2261
4,Source 2 - Hotel Reviews SQL Clean,negative_review,N A,1060,0.2055
5,Source 2 - Hotel Reviews SQL Clean,negative_review,,849,0.1646
6,Source 2 - Hotel Reviews SQL Clean,negative_review,Nothing really,570,0.1105
7,Source 2 - Hotel Reviews SQL Clean,negative_review,N a,520,0.1008
8,Source 2 - Hotel Reviews SQL Clean,negative_review,All good,470,0.0911
9,Source 2 - Hotel Reviews SQL Clean,negative_review,Small room,455,0.0882
10,Source 2 - Hotel Reviews SQL Clean,negative_review,No complaints,450,0.0873
11,Source 2 - Hotel Reviews SQL Clean,negative_review,Breakfast,449,0.0871

Frequency display - Source 2 - Hotel Reviews SQL Clean - positive_review

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews SQL Clean,positive_review,No Positive,35946,6.9698
1,Source 2 - Hotel Reviews SQL Clean,positive_review,Location,10137,1.9655
2,Source 2 - Hotel Reviews SQL Clean,positive_review,Everything,2897,0.5617
3,Source 2 - Hotel Reviews SQL Clean,positive_review,location,1736,0.3366
4,Source 2 - Hotel Reviews SQL Clean,positive_review,Nothing,1468,0.2846
5,Source 2 - Hotel Reviews SQL Clean,positive_review,Great location,1419,0.2751
6,Source 2 - Hotel Reviews SQL Clean,positive_review,The location,1341,0.26
7,Source 2 - Hotel Reviews SQL Clean,positive_review,Good location,1203,0.2333
8,Source 2 - Hotel Reviews SQL Clean,positive_review,Breakfast,664,0.1287
9,Source 2 - Hotel Reviews SQL Clean,positive_review,Friendly staff,603,0.1169
10,Source 2 - Hotel Reviews SQL Clean,positive_review,Excellent location,547,0.1061
11,Source 2 - Hotel Reviews SQL Clean,positive_review,Staff,486,0.0942

Frequency display - Source 2 - Hotel Reviews SQL Clean - tags

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Double Room ', ' Stayed 1 night ', ' Submitted from a mobile device ']",5101,0.9891
1,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Standard Double Room ', ' Stayed 1 night ', ' Submitted from a mobile device ']",4931,0.9561
2,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Superior Double Room ', ' Stayed 1 night ', ' Submitted from a mobile device ']",4366,0.8466
3,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Deluxe Double Room ', ' Stayed 1 night ', ' Submitted from a mobile device ']",3991,0.7738
4,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Double Room ', ' Stayed 2 nights ', ' Submitted from a mobile device ']",3291,0.6381
5,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Superior Double Room ', ' Stayed 2 nights ', ' Submitted from a mobile device ']",3102,0.6015
6,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Standard Double Room ', ' Stayed 2 nights ', ' Submitted from a mobile device ']",2947,0.5714
7,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Double Room ', ' Stayed 1 night ']",2906,0.5635
8,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Standard Double Room ', ' Stayed 1 night ']",2620,0.508
9,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Deluxe Double Room ', ' Stayed 2 nights ', ' Submitted from a mobile device ']",2362,0.458
10,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Superior Double Room ', ' Stayed 1 night ']",2215,0.4295
11,Source 2 - Hotel Reviews SQL Clean,tags,"[' Leisure trip ', ' Couple ', ' Double Room ', ' Stayed 2 nights ']",2175,0.4217

Frequency display - Source 2 - Hotel Reviews SQL Clean - review_date

,dataset,column,value,frequency,percentage
0,Source 2 - Hotel Reviews SQL Clean,review_date,2017-08-02,2585,0.5012
1,Source 2 - Hotel Reviews SQL Clean,review_date,2016-09-15,2308,0.4475
2,Source 2 - Hotel Reviews SQL Clean,review_date,2017-04-05,2284,0.4429
3,Source 2 - Hotel Reviews SQL Clean,review_date,2016-08-30,1963,0.3806
4,Source 2 - Hotel Reviews SQL Clean,review_date,2016-02-16,1940,0.3762
5,Source 2 - Hotel Reviews SQL Clean,review_date,2016-07-05,1904,0.3692
6,Source 2 - Hotel Reviews SQL Clean,review_date,2016-05-31,1860,0.3606
7,Source 2 - Hotel Reviews SQL Clean,review_date,2016-12-05,1803,0.3496
8,Source 2 - Hotel Reviews SQL Clean,review_date,2016-07-12,1801,0.3492
9,Source 2 - Hotel Reviews SQL Clean,review_date,2016-08-02,1783,0.3457
10,Source 2 - Hotel Reviews SQL Clean,review_date,2016-06-21,1750,0.3393
11,Source 2 - Hotel Reviews SQL Clean,review_date,2016-05-03,1732,0.3358

Unusual/missing values report - Source 1 - Hotel Bookings SQL Clean

,dataset,column,missing_count,unusual_value_count,unusual_examples
0,Source 1 - Hotel Bookings SQL Clean,country,0,488,Unknown
1,Source 1 - Hotel Bookings SQL Clean,agent,0,16340,Unknown
2,Source 1 - Hotel Bookings SQL Clean,company,0,112593,Unknown

Unusual/missing values report - Source 2 - Hotel Reviews SQL Clean

,dataset,column,missing_count,unusual_value_count,unusual_examples
0,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,0,523,
1,Source 2 - Hotel Reviews SQL Clean,negative_review,0,130380,"No Negative, , None, none, NA"
2,Source 2 - Hotel Reviews SQL Clean,positive_review,0,36179,"No Positive, None, , NA, none"

Datatype consistency report - Source 1 - Hotel Bookings SQL Clean

,dataset,column,dtype,numeric_parse_pct_if_object,datetime_parse_pct_if_object,recommendation
0,Source 1 - Hotel Bookings SQL Clean,booking_id,int64,NaN,NaN,ok
1,Source 1 - Hotel Bookings SQL Clean,hotel,object,0.0,0.0,ok
2,Source 1 - Hotel Bookings SQL Clean,is_canceled,int64,NaN,NaN,ok
3,Source 1 - Hotel Bookings SQL Clean,lead_time,float64,NaN,NaN,ok
4,Source 1 - Hotel Bookings SQL Clean,arrival_date_year,int64,NaN,NaN,ok
5,Source 1 - Hotel Bookings SQL Clean,arrival_date_month,object,0.0,0.0,ok
6,Source 1 - Hotel Bookings SQL Clean,arrival_date_week_number,int64,NaN,NaN,ok
7,Source 1 - Hotel Bookings SQL Clean,arrival_date_day_of_month,int64,NaN,NaN,ok
8,Source 1 - Hotel Bookings SQL Clean,stays_in_weekend_nights,float64,NaN,NaN,ok
9,Source 1 - Hotel Bookings SQL Clean,stays_in_week_nights,float64,NaN,NaN,ok
10,Source 1 - Hotel Bookings SQL Clean,adults,float64,NaN,NaN,ok
11,Source 1 - Hotel Bookings SQL Clean,children,float64,NaN,NaN,ok
12,Source 1 - Hotel Bookings SQL Clean,babies,float64,NaN,NaN,ok
13,Source 1 - Hotel Bookings SQL Clean,meal,object,0.0,0.0,ok
14,Source 1 - Hotel Bookings SQL Clean,country,object,0.0,0.0,ok
15,Source 1 - Hotel Bookings SQL Clean,market_segment,object,0.0,0.0,ok
16,Source 1 - Hotel Bookings SQL Clean,distribution_channel,object,0.0,0.0,ok
17,Source 1 - Hotel Bookings SQL Clean,is_repeated_guest,int64,NaN,NaN,ok
18,Source 1 - Hotel Bookings SQL Clean,previous_cancellations,float64,NaN,NaN,ok
19,Source 1 - Hotel Bookings SQL Clean,previous_bookings_not_canceled,float64,NaN,NaN,ok
20,Source 1 - Hotel Bookings SQL Clean,reserved_room_type,object,0.0,0.0,ok
21,Source 1 - Hotel Bookings SQL Clean,assigned_room_type,object,0.0,0.0,ok
22,Source 1 - Hotel Bookings SQL Clean,booking_changes,float64,NaN,NaN,ok
23,Source 1 - Hotel Bookings SQL Clean,deposit_type,object,0.0,0.0,ok
24,Source 1 - Hotel Bookings SQL Clean,agent,object,91.0,0.0,review type conversion
25,Source 1 - Hotel Bookings SQL Clean,company,object,0.5,0.0,ok
26,Source 1 - Hotel Bookings SQL Clean,days_in_waiting_list,float64,NaN,NaN,ok
27,Source 1 - Hotel Bookings SQL Clean,customer_type,object,0.0,0.0,ok
28,Source 1 - Hotel Bookings SQL Clean,adr,float64,NaN,NaN,ok
29,Source 1 - Hotel Bookings SQL Clean,required_car_parking_spaces,float64,NaN,NaN,ok
30,Source 1 - Hotel Bookings SQL Clean,total_of_special_requests,float64,NaN,NaN,ok
31,Source 1 - Hotel Bookings SQL Clean,reservation_status,object,0.0,0.0,ok
32,Source 1 - Hotel Bookings SQL Clean,reservation_status_date,object,0.0,100.0,review type conversion
33,Source 1 - Hotel Bookings SQL Clean,total_guests,float64,NaN,NaN,ok
34,Source 1 - Hotel Bookings SQL Clean,total_nights,float64,NaN,NaN,ok
35,Source 1 - Hotel Bookings SQL Clean,zero_guest_flag,int64,NaN,NaN,ok
36,Source 1 - Hotel Bookings SQL Clean,zero_night_flag,int64,NaN,NaN,ok
37,Source 1 - Hotel Bookings SQL Clean,has_agent,int64,NaN,NaN,ok
38,Source 1 - Hotel Bookings SQL Clean,has_company,int64,NaN,NaN,ok
39,Source 1 - Hotel Bookings SQL Clean,room_changed,int64,NaN,NaN,ok
40,Source 1 - Hotel Bookings SQL Clean,arrival_date,object,0.0,100.0,review type conversion
41,Source 1 - Hotel Bookings SQL Clean,lead_time_minmax,float64,NaN,NaN,ok
42,Source 1 - Hotel Bookings SQL Clean,adr_minmax,float64,NaN,NaN,ok
43,Source 1 - Hotel Bookings SQL Clean,total_nights_minmax,float64,NaN,NaN,ok
44,Source 1 - Hotel Bookings SQL Clean,total_guests_minmax,float64,NaN,NaN,ok
45,Source 1 - Hotel Bookings SQL Clean,source_duplicate_flag,int64,NaN,NaN,ok
46,Source 1 - Hotel Bookings SQL Clean,outlier_count,int64,NaN,NaN,ok
47,Source 1 - Hotel Bookings SQL Clean,market_segment_freq_encoded,float64,NaN,NaN,ok
48,Source 1 - Hotel Bookings SQL Clean,customer_type_freq_encoded,float64,NaN,NaN,ok

Datatype consistency report - Source 2 - Hotel Reviews SQL Clean

,dataset,column,dtype,numeric_parse_pct_if_object,datetime_parse_pct_if_object,recommendation
0,Source 2 - Hotel Reviews SQL Clean,review_id,int64,NaN,NaN,ok
1,Source 2 - Hotel Reviews SQL Clean,hotel_address,object,0.0,0.0,ok
2,Source 2 - Hotel Reviews SQL Clean,additional_number_of_scoring,float64,NaN,NaN,ok
3,Source 2 - Hotel Reviews SQL Clean,average_score,float64,NaN,NaN,ok
4,Source 2 - Hotel Reviews SQL Clean,hotel_name,object,0.0,0.0,ok
5,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality,object,0.0,0.0,ok
6,Source 2 - Hotel Reviews SQL Clean,negative_review,object,0.0,0.0,ok
7,Source 2 - Hotel Reviews SQL Clean,negative_review_word_count,float64,NaN,NaN,ok
8,Source 2 - Hotel Reviews SQL Clean,total_number_of_reviews,float64,NaN,NaN,ok
9,Source 2 - Hotel Reviews SQL Clean,positive_review,object,0.0,0.0,ok
10,Source 2 - Hotel Reviews SQL Clean,positive_review_word_count,float64,NaN,NaN,ok
11,Source 2 - Hotel Reviews SQL Clean,total_number_of_reviews_reviewer_has_given,float64,NaN,NaN,ok
12,Source 2 - Hotel Reviews SQL Clean,reviewer_score,float64,NaN,NaN,ok
13,Source 2 - Hotel Reviews SQL Clean,tags,object,0.0,0.0,ok
14,Source 2 - Hotel Reviews SQL Clean,lat,float64,NaN,NaN,ok
15,Source 2 - Hotel Reviews SQL Clean,lng,float64,NaN,NaN,ok
16,Source 2 - Hotel Reviews SQL Clean,review_date,object,0.0,100.0,review type conversion
17,Source 2 - Hotel Reviews SQL Clean,days_since_review_numeric,int64,NaN,NaN,ok
18,Source 2 - Hotel Reviews SQL Clean,positive_review_length,int64,NaN,NaN,ok
19,Source 2 - Hotel Reviews SQL Clean,negative_review_length,int64,NaN,NaN,ok
20,Source 2 - Hotel Reviews SQL Clean,sentiment_word_balance,float64,NaN,NaN,ok
21,Source 2 - Hotel Reviews SQL Clean,tag_count,int64,NaN,NaN,ok
22,Source 2 - Hotel Reviews SQL Clean,source_duplicate_flag,int64,NaN,NaN,ok
23,Source 2 - Hotel Reviews SQL Clean,outlier_count,int64,NaN,NaN,ok
24,Source 2 - Hotel Reviews SQL Clean,average_score_minmax,float64,NaN,NaN,ok
25,Source 2 - Hotel Reviews SQL Clean,reviewer_score_minmax,float64,NaN,NaN,ok
26,Source 2 - Hotel Reviews SQL Clean,positive_review_word_count_minmax,float64,NaN,NaN,ok
27,Source 2 - Hotel Reviews SQL Clean,negative_review_word_count_minmax,float64,NaN,NaN,ok
28,Source 2 - Hotel Reviews SQL Clean,reviewer_nationality_freq_encoded,float64,NaN,NaN,ok
29,Source 2 - Hotel Reviews SQL Clean,hotel_name_freq_encoded,float64,NaN,NaN,ok

Distribution report - Source 1 - Hotel Bookings SQL Clean

,dataset,column,count,mean,std,min,25%,50%,75%,max
0,Source 1 - Hotel Bookings SQL Clean,booking_id,119390.0,59695.500000,34465.068657,1.0,29848.25,59695.5,89542.75,119390.0
1,Source 1 - Hotel Bookings SQL Clean,is_canceled,119390.0,0.370416,0.482918,0.0,0.00,0.0,1.00,1.0
2,Source 1 - Hotel Bookings SQL Clean,lead_time,119390.0,104.011416,106.863097,0.0,18.00,69.0,160.00,737.0
3,Source 1 - Hotel Bookings SQL Clean,arrival_date_year,119390.0,2016.156554,0.707476,2015.0,2016.00,2016.0,2017.00,2017.0
4,Source 1 - Hotel Bookings SQL Clean,arrival_date_week_number,119390.0,27.165173,13.605138,1.0,16.00,28.0,38.00,53.0
5,Source 1 - Hotel Bookings SQL Clean,arrival_date_day_of_month,119390.0,15.798241,8.780829,1.0,8.00,16.0,23.00,31.0
6,Source 1 - Hotel Bookings SQL Clean,stays_in_weekend_nights,119390.0,0.927599,0.998613,0.0,0.00,1.0,2.00,19.0
7,Source 1 - Hotel Bookings SQL Clean,stays_in_week_nights,119390.0,2.500302,1.908286,0.0,1.00,2.0,3.00,50.0
8,Source 1 - Hotel Bookings SQL Clean,adults,119390.0,1.856403,0.579261,0.0,2.00,2.0,2.00,55.0
9,Source 1 - Hotel Bookings SQL Clean,children,119390.0,0.103886,0.398555,0.0,0.00,0.0,0.00,10.0
10,Source 1 - Hotel Bookings SQL Clean,babies,119390.0,0.007949,0.097436,0.0,0.00,0.0,0.00,10.0
11,Source 1 - Hotel Bookings SQL Clean,is_repeated_guest,119390.0,0.031912,0.175767,0.0,0.00,0.0,0.00,1.0

Distribution report - Source 2 - Hotel Reviews SQL Clean

,dataset,column,count,mean,std,min,25%,50%,75%,max
0,Source 2 - Hotel Reviews SQL Clean,review_id,515738.0,257869.500000,148880.880902,1.000000,128935.250000,257869.500000,386803.750000,515738.000000
1,Source 2 - Hotel Reviews SQL Clean,additional_number_of_scoring,515738.0,498.081836,500.538467,1.000000,169.000000,341.000000,660.000000,2682.000000
2,Source 2 - Hotel Reviews SQL Clean,average_score,515738.0,8.397487,0.548048,5.200000,8.100000,8.400000,8.800000,9.800000
3,Source 2 - Hotel Reviews SQL Clean,negative_review_word_count,515738.0,18.539450,29.690831,0.000000,2.000000,9.000000,23.000000,408.000000
4,Source 2 - Hotel Reviews SQL Clean,total_number_of_reviews,515738.0,2743.743944,2317.464868,43.000000,1161.000000,2134.000000,3613.000000,16670.000000
5,Source 2 - Hotel Reviews SQL Clean,positive_review_word_count,515738.0,17.776458,21.804185,0.000000,5.000000,11.000000,22.000000,395.000000
6,Source 2 - Hotel Reviews SQL Clean,total_number_of_reviews_reviewer_has_given,515738.0,7.166001,11.040228,1.000000,1.000000,3.000000,8.000000,355.000000
7,Source 2 - Hotel Reviews SQL Clean,reviewer_score,515738.0,8.395077,1.637856,2.500000,7.500000,8.800000,9.600000,10.000000
8,Source 2 - Hotel Reviews SQL Clean,lat,515738.0,49.129144,5.227925,0.000000,48.212857,51.499981,51.516288,52.400181
9,Source 2 - Hotel Reviews SQL Clean,lng,515738.0,2.805910,4.570389,-0.369758,-0.143372,0.000000,4.831098,16.429233
10,Source 2 - Hotel Reviews SQL Clean,days_since_review_numeric,515738.0,354.441932,208.928124,0.000000,175.000000,353.000000,527.000000,730.000000
11,Source 2 - Hotel Reviews SQL Clean,positive_review_length,515738.0,93.171682,115.184799,0.000000,25.000000,57.000000,118.000000,1958.000000

### Warehouse Collection: Snowflake Scheme

In [ ]:
# ============================================================
# ELT Snowflake Warehouse Tables
# Dimension tables + Fact tables only
# ============================================================

def collect_elt_warehouse_tables(lake_engine):
    warehouse_logical_names = [
        "dim_date",
        "dim_booking_hotel_type",
        "dim_country",
        "dim_meal",
        "dim_market_segment",
        "dim_distribution_channel",
        "dim_customer_type",
        "dim_deposit_type",
        "dim_room_type",
        "dim_review_hotel",
        "fact_bookings",
        "fact_reviews",
        "fact_hotel_monthly_performance",
    ]

    tables = {}

    for logical_name in warehouse_logical_names:
        physical_name = f"elt_{logical_name}"

        if lake_table_exists(lake_engine, physical_name):
            tables[logical_name] = safe_for_sql(read_lake_table(lake_engine, physical_name))
        else:
            raise KeyError(
                f"Missing ELT lake table: {physical_name}. "
                "Rerun build_elt_sql_tables(elt_lake_engine)."
            )

    return tables


elt_warehouse_tables = collect_elt_warehouse_tables(elt_lake_engine)


elt_relationships = pd.DataFrame([
    {"fact_table": "fact_bookings", "foreign_key": "arrival_date_id", "dimension_table": "dim_date", "primary_key": "date_id"},
    {"fact_table": "fact_bookings", "foreign_key": "reservation_status_date_id", "dimension_table": "dim_date", "primary_key": "date_id"},
    {"fact_table": "fact_bookings", "foreign_key": "booking_hotel_type_id", "dimension_table": "dim_booking_hotel_type", "primary_key": "booking_hotel_type_id"},
    {"fact_table": "fact_bookings", "foreign_key": "country_id", "dimension_table": "dim_country", "primary_key": "country_id"},
    {"fact_table": "fact_bookings", "foreign_key": "meal_id", "dimension_table": "dim_meal", "primary_key": "meal_id"},
    {"fact_table": "fact_bookings", "foreign_key": "market_segment_id", "dimension_table": "dim_market_segment", "primary_key": "market_segment_id"},
    {"fact_table": "fact_bookings", "foreign_key": "distribution_channel_id", "dimension_table": "dim_distribution_channel", "primary_key": "distribution_channel_id"},
    {"fact_table": "fact_bookings", "foreign_key": "customer_type_id", "dimension_table": "dim_customer_type", "primary_key": "customer_type_id"},
    {"fact_table": "fact_bookings", "foreign_key": "deposit_type_id", "dimension_table": "dim_deposit_type", "primary_key": "deposit_type_id"},
    {"fact_table": "fact_bookings", "foreign_key": "reserved_room_type_id", "dimension_table": "dim_room_type", "primary_key": "room_type_id"},
    {"fact_table": "fact_bookings", "foreign_key": "assigned_room_type_id", "dimension_table": "dim_room_type", "primary_key": "room_type_id"},
    {"fact_table": "fact_reviews", "foreign_key": "review_date_id", "dimension_table": "dim_date", "primary_key": "date_id"},
    {"fact_table": "fact_reviews", "foreign_key": "reviewer_country_id", "dimension_table": "dim_country", "primary_key": "country_id"},
    {"fact_table": "fact_reviews", "foreign_key": "review_hotel_id", "dimension_table": "dim_review_hotel", "primary_key": "review_hotel_id"},
    {"fact_table": "fact_hotel_monthly_performance", "foreign_key": "month_start_date_id", "dimension_table": "dim_date", "primary_key": "date_id"},
])


for table_name, df in elt_warehouse_tables.items():
    print(f"ELT warehouse table: {table_name} -> {df.shape[0]:,} rows, {df.shape[1]:,} columns")
    display(df.head(10))


print("ELT snowflake schema primary key and foreign key relationship plan")
display(elt_relationships)

ELT warehouse table: dim_date -> 927 rows, 8 columns

   date_id        date  year  month  day  quarter month_name year_month
0        1  1900-01-01  1900      1    1        1    January    1900-01
1        2  2014-10-17  2014     10   17        4    October    2014-10
2        3  2014-11-18  2014     11   18        4   November    2014-11
3        4  2015-01-01  2015      1    1        1    January    2015-01
4        5  2015-01-02  2015      1    2        1    January    2015-01
5        6  2015-01-18  2015      1   18        1    January    2015-01
6        7  2015-01-20  2015      1   20        1    January    2015-01
7        8  2015-01-21  2015      1   21        1    January    2015-01
8        9  2015-01-22  2015      1   22        1    January    2015-01
9       10  2015-01-28  2015      1   28        1    January    2015-01

ELT warehouse table: dim_booking_hotel_type -> 3 rows, 2 columns

   booking_hotel_type_id    hotel_type
0                      1    City Hotel
1                      2  Resort Hotel
2                      3       Unknown

ELT warehouse table: dim_country -> 405 rows, 2 columns

   country_id country_name
0           1
1           2          ABW
2           3          AGO
3           4          AIA
4           5          ALB
5           6          AND
6           7          ARE
7           8          ARG
8           9          ARM
9          10          ASM

ELT warehouse table: dim_meal -> 6 rows, 2 columns

   meal_id       meal
0        1         BB
1        2         FB
2        3         HB
3        4         SC
4        5  Undefined
5        6    Unknown

ELT warehouse table: dim_market_segment -> 9 rows, 2 columns

   market_segment_id market_segment
0                  1       Aviation
1                  2  Complementary
2                  3      Corporate
3                  4         Direct
4                  5         Groups
5                  6  Offline TA/TO
6                  7      Online TA
7                  8      Undefined
8                  9        Unknown

ELT warehouse table: dim_distribution_channel -> 6 rows, 2 columns

   distribution_channel_id distribution_channel
0                        1            Corporate
1                        2               Direct
2                        3                  GDS
3                        4                TA/TO
4                        5            Undefined
5                        6              Unknown

ELT warehouse table: dim_customer_type -> 5 rows, 2 columns

   customer_type_id    customer_type
0                 1         Contract
1                 2            Group
2                 3        Transient
3                 4  Transient-Party
4                 5          Unknown

ELT warehouse table: dim_deposit_type -> 4 rows, 2 columns

   deposit_type_id deposit_type
0                1   No Deposit
1                2   Non Refund
2                3   Refundable
3                4      Unknown

ELT warehouse table: dim_room_type -> 13 rows, 2 columns

   room_type_id room_type
0             1         A
1             2         B
2             3         C
3             4         D
4             5         E
5             6         F
6             7         G
7             8         H
8             9         I
9            10         K

ELT warehouse table: dim_review_hotel -> 1,495 rows, 6 columns

,review_hotel_id,hotel_name,hotel_address,lat,lng,average_score
0,1,11 Cadogan Gardens,11 Cadogan Gardens Sloane Square Kensington and Chelsea London SW3 2RJ United Kingdom,51.493616,-0.159235,8.7
1,2,1K Hotel,13 Boulevard Du Temple 3rd arr 75003 Paris France,48.863932,2.365874,7.7
2,3,25hours Hotel beim MuseumsQuartier,Lerchenfelder Stra e 1 3 07 Neubau 1070 Vienna Austria,48.206474,16.354630,8.8
3,4,41,41 Buckingham Palace Road Westminster Borough London SW1W 0PS United Kingdom,51.498147,-0.143649,9.6
4,5,45 Park Lane Dorchester Collection,45 Park Lane Westminster Borough London W1K 1PN United Kingdom,51.506371,-0.151536,9.4
5,6,88 Studios,88 Holland Road Kensington and Chelsea London W14 8BN United Kingdom,51.499279,-0.209073,8.4
6,7,9Hotel Republique,7 9 Rue Pierre Chausson 10th arr 75010 Paris France,48.870842,2.360586,8.8
7,8,A La Villa Madame,44 Rue Madame 6th arr 75006 Paris France,48.848861,2.331526,8.8
8,9,ABaC Restaurant Hotel Barcelona GL Monumento,Avenida Tibidabo 1 Sarri St Gervasi 08022 Barcelona Spain,41.410694,2.136294,8.8
9,10,AC Hotel Barcelona Forum a Marriott Lifestyle Hotel,Paseo Taulat 278 Sant Mart 08019 Barcelona Spain,41.410131,2.218805,8.1

ELT warehouse table: fact_bookings -> 119,390 rows, 44 columns

,booking_id,arrival_date_id,reservation_status_date_id,booking_hotel_type_id,country_id,meal_id,market_segment_id,distribution_channel_id,customer_type_id,deposit_type_id,reserved_room_type_id,assigned_room_type_id,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,total_nights,adults,children,babies,total_guests,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,total_revenue_proxy,required_car_parking_spaces,total_of_special_requests,zero_guest_flag,zero_night_flag,has_agent,has_company,room_changed,source_duplicate_flag,outlier_count,lead_time_minmax,adr_minmax,total_guests_minmax,total_nights_minmax,market_segment_freq_encoded,customer_type_freq_encoded
0,1,123,123,2,289,1,4,2,3,1,3,3,0,342.0,27,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0.464043,0.000000,0.036364,0.000000,0.105587,0.750591
1,2,123,123,2,289,1,4,2,3,1,3,3,0,737.0,27,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,1.000000,0.000000,0.036364,0.000000,0.105587,0.750591
2,3,123,124,2,135,1,4,2,3,1,1,3,0,7.0,27,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,75.0,75.0,0.0,0.0,0,0,0,0,1,0,0,0.009498,0.013889,0.018182,0.014493,0.105587,0.750591
3,4,123,124,2,135,1,3,1,3,1,1,1,0,13.0,27,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,75.0,75.0,0.0,0.0,0,0,1,0,0,0,0,0.017639,0.013889,0.018182,0.014493,0.044350,0.750591
4,5,123,125,2,135,1,7,4,3,1,1,1,0,14.0,27,0.0,2.0,2.0,2.0,0.0,0.0,2.0,0,0.0,0.0,0.0,0.0,98.0,196.0,0.0,1.0,0,0,1,0,0,0,0,0.018996,0.018148,0.036364,0.028986,0.473046,0.750591
5,6,123,125,2,135,1,7,4,3,1,1,1,0,14.0,27,0.0,2.0,2.0,2.0,0.0,0.0,2.0,0,0.0,0.0,0.0,0.0,98.0,196.0,0.0,1.0,0,0,1,0,0,0,0,0.018996,0.018148,0.036364,0.028986,0.473046,0.750591
6,7,123,125,2,289,1,4,2,3,1,3,3,0,0.0,27,0.0,2.0,2.0,2.0,0.0,0.0,2.0,0,0.0,0.0,0.0,0.0,107.0,214.0,0.0,0.0,0,0,0,0,0,0,0,0.000000,0.019815,0.036364,0.028986,0.105587,0.750591
7,8,123,125,2,289,2,4,2,3,1,3,3,0,9.0,27,0.0,2.0,2.0,2.0,0.0,0.0,2.0,0,0.0,0.0,0.0,0.0,103.0,206.0,0.0,1.0,0,0,1,0,0,0,0,0.012212,0.019074,0.036364,0.028986,0.105587,0.750591
8,9,123,74,2,289,1,7,4,3,1,1,1,1,85.0,27,0.0,3.0,3.0,2.0,0.0,0.0,2.0,0,0.0,0.0,0.0,0.0,82.0,246.0,0.0,1.0,0,0,1,0,0,0,0,0.115332,0.015185,0.036364,0.043478,0.473046,0.750591
9,10,123,63,2,289,3,6,4,3,1,4,4,1,75.0,27,0.0,3.0,3.0,2.0,0.0,0.0,2.0,0,0.0,0.0,0.0,0.0,105.5,316.5,0.0,0.0,0,0,1,0,0,0,0,0.101764,0.019537,0.036364,0.043478,0.202856,0.750591

ELT warehouse table: fact_reviews -> 515,738 rows, 24 columns

,review_id,review_date_id,reviewer_country_id,review_hotel_id,additional_number_of_scoring,average_score,total_number_of_reviews,total_number_of_reviews_reviewer_has_given,reviewer_score,positive_review_word_count,negative_review_word_count,positive_review_length,negative_review_length,sentiment_word_balance,tag_count,days_since_review_numeric,source_duplicate_flag,outlier_count,average_score_minmax,reviewer_score_minmax,positive_review_word_count_minmax,negative_review_word_count_minmax,reviewer_nationality_freq_encoded,hotel_name_freq_encoded
0,1,887,310,568,194.0,7.7,1403.0,7.0,2.9,11.0,397.0,48,1861,-386.0,4,0,0,0,0.543478,0.053333,0.027848,0.973039,0.007562,0.000785
1,2,887,181,568,194.0,7.7,1403.0,7.0,7.5,105.0,0.0,609,11,105.0,4,0,0,0,0.543478,0.666667,0.265823,0.000000,0.028749,0.000785
2,3,884,29,568,194.0,7.7,1403.0,9.0,7.1,21.0,42.0,93,204,-21.0,5,3,0,0,0.543478,0.613333,0.053165,0.102941,0.042048,0.000785
3,4,884,386,568,194.0,7.7,1403.0,1.0,3.8,26.0,210.0,141,1076,-184.0,4,3,0,0,0.543478,0.173333,0.065823,0.514706,0.475524,0.000785
4,5,877,274,568,194.0,7.7,1403.0,3.0,6.7,8.0,140.0,46,724,-132.0,5,10,0,0,0.543478,0.560000,0.020253,0.343137,0.006276,0.000785
5,6,877,300,568,194.0,7.7,1403.0,1.0,6.7,20.0,17.0,108,74,3.0,4,10,0,0,0.543478,0.560000,0.050633,0.041667,0.005606,0.000785
6,7,870,386,568,194.0,7.7,1403.0,6.0,4.6,18.0,33.0,82,149,-15.0,5,17,0,0,0.543478,0.280000,0.045570,0.080882,0.475524,0.000785
7,8,870,386,568,194.0,7.7,1403.0,1.0,10.0,19.0,11.0,96,58,8.0,5,17,0,0,0.543478,1.000000,0.048101,0.026961,0.475524,0.000785
8,9,862,51,568,194.0,7.7,1403.0,3.0,6.5,0.0,34.0,11,161,-34.0,5,25,0,0,0.543478,0.533333,0.000000,0.083333,0.011694,0.000785
9,10,861,279,568,194.0,7.7,1403.0,1.0,7.9,50.0,15.0,241,67,35.0,4,26,0,0,0.543478,0.720000,0.126582,0.036765,0.004621,0.000785

ELT warehouse table: fact_hotel_monthly_performance -> 26 rows, 12 columns

,performance_id,month_start_date_id,booking_count,canceled_booking_count,cancellation_rate,avg_adr,total_revenue_proxy,avg_total_nights,avg_total_guests,review_count,avg_reviewer_score,avg_sentiment_word_balance
0,1,123,2776,1259,0.453530,97.834316,1146861.53,3.868156,2.058718,0,0.000000,0.000000
1,2,154,3889,1598,0.410903,105.922888,1698555.34,3.703266,2.067370,19320,8.378059,-0.359576
2,3,185,5114,2094,0.409464,94.818662,1666155.39,3.474775,1.901838,19738,8.255558,-1.185682
3,4,215,4957,1732,0.349405,78.895427,1170206.08,3.056486,1.832560,19486,8.195710,-1.495843
4,5,246,2340,486,0.207692,60.580252,462989.38,3.270940,1.626923,18056,8.316388,-0.737151
5,6,276,2920,973,0.333219,74.079243,673348.84,3.038699,1.873288,17927,8.466291,0.122553
6,7,307,2248,557,0.247776,64.767656,403694.85,2.740658,1.705961,19510,8.521030,1.236802
7,8,338,3891,1337,0.343613,70.102269,788225.29,2.876895,1.854279,18856,8.545646,-0.215634
8,9,367,4824,1477,0.306177,79.069326,1226927.65,3.232380,1.919776,20744,8.518425,0.082626
9,10,398,5428,2061,0.379698,88.918920,1522984.13,3.197863,1.929071,21481,8.479210,0.221731

ELT snowflake schema primary key and foreign key relationship plan

,fact_table,foreign_key,dimension_table,primary_key
0,fact_bookings,arrival_date_id,dim_date,date_id
1,fact_bookings,reservation_status_date_id,dim_date,date_id
2,fact_bookings,booking_hotel_type_id,dim_booking_hotel_type,booking_hotel_type_id
3,fact_bookings,country_id,dim_country,country_id
4,fact_bookings,meal_id,dim_meal,meal_id
5,fact_bookings,market_segment_id,dim_market_segment,market_segment_id
6,fact_bookings,distribution_channel_id,dim_distribution_channel,distribution_channel_id
7,fact_bookings,customer_type_id,dim_customer_type,customer_type_id
8,fact_bookings,deposit_type_id,dim_deposit_type,deposit_type_id
9,fact_bookings,reserved_room_type_id,dim_room_type,room_type_id
10,fact_bookings,assigned_room_type_id,dim_room_type,room_type_id
11,fact_reviews,review_date_id,dim_date,date_id
12,fact_reviews,reviewer_country_id,dim_country,country_id
13,fact_reviews,review_hotel_id,dim_review_hotel,review_hotel_id
14,fact_hotel_monthly_performance,month_start_date_id,dim_date,date_id

### Aggregation and Metric Analytics

In [ ]:
# ============================================================
# ELT Metric Analytics Tables
# Aggregated analytical outputs only
# ============================================================

def collect_elt_metric_tables(lake_engine):
    metric_logical_names = [
        "metric_booking_by_segment",
        "metric_review_by_hotel",
        "metric_monthly_kpi",
    ]

    metric_tables = {}

    for logical_name in metric_logical_names:
        physical_name = f"elt_{logical_name}"

        if lake_table_exists(lake_engine, physical_name):
            metric_tables[logical_name] = safe_for_sql(read_lake_table(lake_engine, physical_name))
        else:
            raise KeyError(
                f"Missing ELT metric table: {physical_name}. "
                "Rerun build_elt_sql_tables(elt_lake_engine)."
            )

    return metric_tables


elt_metric_tables = collect_elt_metric_tables(elt_lake_engine)


for table_name, df in elt_metric_tables.items():
    print(f"ELT metric analytics table: {table_name} -> {df.shape[0]:,} rows, {df.shape[1]:,} columns")
    display(df.head(10))

ELT metric analytics table: metric_booking_by_segment -> 8 rows, 7 columns

,metric_segment_id,market_segment,booking_count,cancellation_rate,avg_adr,total_revenue_proxy,avg_total_nights
0,1,Aviation,237,0.219409,100.142110,87446.36,3.607595
1,2,Complementary,743,0.130552,2.886366,5082.52,1.647376
2,3,Corporate,5295,0.187347,69.358952,774295.26,2.092918
3,4,Direct,12606,0.153419,115.445175,5093028.39,3.205775
4,5,Groups,19811,0.610620,79.479794,4669700.54,2.992529
5,6,Offline TA/TO,24219,0.343160,87.354783,8151912.73,3.903877
6,7,Online TA,56477,0.367211,117.197063,23942047.53,3.573986
7,8,Undefined,2,1.000000,15.000000,48.00,1.500000

ELT metric analytics table: metric_review_by_hotel -> 1,492 rows, 8 columns

,metric_review_hotel_id,hotel_name,review_count,avg_reviewer_score,avg_average_score,avg_positive_words,avg_negative_words,avg_sentiment_word_balance
0,1,11 Cadogan Gardens,159,8.845283,8.7,19.974843,15.528302,4.446541
1,2,1K Hotel,148,7.861486,7.7,15.601351,24.932432,-9.331081
2,3,25hours Hotel beim MuseumsQuartier,689,8.983309,8.8,21.911466,16.161103,5.750363
3,4,41,103,9.711650,9.6,25.300971,8.883495,16.417476
4,5,45 Park Lane Dorchester Collection,28,9.603571,9.4,11.535714,6.750000,4.785714
5,6,88 Studios,459,8.489107,8.4,21.464052,23.936819,-2.472767
6,7,9Hotel Republique,183,8.743716,8.8,19.338798,16.950820,2.387978
7,8,A La Villa Madame,41,8.853659,8.8,19.634146,8.463415,11.170732
8,9,ABaC Restaurant Hotel Barcelona GL Monumento,31,8.464516,8.8,18.677419,35.225806,-16.548387
9,10,AC Hotel Barcelona Forum a Marriott Lifestyle Hotel,289,8.001384,8.1,14.986159,21.626298,-6.640138

ELT metric analytics table: metric_monthly_kpi -> 26 rows, 12 columns

,performance_id,month_start_date_id,booking_count,canceled_booking_count,cancellation_rate,avg_adr,total_revenue_proxy,avg_total_nights,avg_total_guests,review_count,avg_reviewer_score,avg_sentiment_word_balance
0,1,123,2776,1259,0.453530,97.834316,1146861.53,3.868156,2.058718,0,0.000000,0.000000
1,2,154,3889,1598,0.410903,105.922888,1698555.34,3.703266,2.067370,19320,8.378059,-0.359576
2,3,185,5114,2094,0.409464,94.818662,1666155.39,3.474775,1.901838,19738,8.255558,-1.185682
3,4,215,4957,1732,0.349405,78.895427,1170206.08,3.056486,1.832560,19486,8.195710,-1.495843
4,5,246,2340,486,0.207692,60.580252,462989.38,3.270940,1.626923,18056,8.316388,-0.737151
5,6,276,2920,973,0.333219,74.079243,673348.84,3.038699,1.873288,17927,8.466291,0.122553
6,7,307,2248,557,0.247776,64.767656,403694.85,2.740658,1.705961,19510,8.521030,1.236802
7,8,338,3891,1337,0.343613,70.102269,788225.29,2.876895,1.854279,18856,8.545646,-0.215634
8,9,367,4824,1477,0.306177,79.069326,1226927.65,3.232380,1.919776,20744,8.518425,0.082626
9,10,398,5428,2061,0.379698,88.918920,1522984.13,3.197863,1.929071,21481,8.479210,0.221731

### Validation Rules

In [ ]:
# ============================================================
# ELT TABLE COMBINATION + VALIDATION
# Uses tables already collected in the two preceding sections.
# ============================================================

elt_tables = {
    **elt_warehouse_tables,
    **elt_metric_tables,
}

elt_validation_rules, elt_fk_validation = validation_suite(
    elt_tables,
    prefix="elt"
)

print(
    "Validation rules: uniqueness, null, range, datatype "
    "consistency, referential integrity, and data distribution"
)
print("Distribution reports for final fact tables")

elt_fact_bookings_distribution = data_distribution_report(
    elt_tables["fact_bookings"],
    "ELT Fact Bookings"
)
elt_fact_reviews_distribution = data_distribution_report(
    elt_tables["fact_reviews"],
    "ELT Fact Reviews"
)
elt_monthly_distribution = data_distribution_report(
    elt_tables["fact_hotel_monthly_performance"],
    "ELT Fact Hotel Monthly Performance"
)

print("ELT Validation Rules")
display(elt_validation_rules)

print("ELT Foreign Key Validation")
display(elt_fk_validation)

print("Available ELT logical tables")
display(pd.DataFrame({
    "table_name": list(elt_tables.keys()),
    "rows": [len(df) for df in elt_tables.values()],
    "columns": [len(df.columns) for df in elt_tables.values()],
}))

Validation rules: uniqueness, null, range, datatype consistency, referential integrity, data distribution

,table,rule_type,rule,status,invalid_count
0,elt_dim_date,uniqueness check,date_id must be unique,PASS,0
1,elt_dim_date,null check,date_id must not be null,PASS,0
2,elt_dim_date,null check,date_id must not be null,PASS,0
3,elt_dim_booking_hotel_type,uniqueness check,booking_hotel_type_id must be unique,PASS,0
4,elt_dim_booking_hotel_type,null check,booking_hotel_type_id must not be null,PASS,0
5,elt_dim_booking_hotel_type,null check,booking_hotel_type_id must not be null,PASS,0
6,elt_dim_country,uniqueness check,country_id must be unique,PASS,0
7,elt_dim_country,null check,country_id must not be null,PASS,0
8,elt_dim_country,null check,country_id must not be null,PASS,0
9,elt_dim_meal,uniqueness check,meal_id must be unique,PASS,0
10,elt_dim_meal,null check,meal_id must not be null,PASS,0
11,elt_dim_meal,null check,meal_id must not be null,PASS,0
12,elt_dim_market_segment,uniqueness check,market_segment_id must be unique,PASS,0
13,elt_dim_market_segment,null check,market_segment_id must not be null,PASS,0
14,elt_dim_market_segment,null check,market_segment_id must not be null,PASS,0
15,elt_dim_distribution_channel,uniqueness check,distribution_channel_id must be unique,PASS,0
16,elt_dim_distribution_channel,null check,distribution_channel_id must not be null,PASS,0
17,elt_dim_distribution_channel,null check,distribution_channel_id must not be null,PASS,0
18,elt_dim_customer_type,uniqueness check,customer_type_id must be unique,PASS,0
19,elt_dim_customer_type,null check,customer_type_id must not be null,PASS,0
20,elt_dim_customer_type,null check,customer_type_id must not be null,PASS,0
21,elt_dim_deposit_type,uniqueness check,deposit_type_id must be unique,PASS,0
22,elt_dim_deposit_type,null check,deposit_type_id must not be null,PASS,0
23,elt_dim_deposit_type,null check,deposit_type_id must not be null,PASS,0
24,elt_dim_room_type,uniqueness check,room_type_id must be unique,PASS,0
25,elt_dim_room_type,null check,room_type_id must not be null,PASS,0
26,elt_dim_room_type,null check,room_type_id must not be null,PASS,0
27,elt_dim_review_hotel,uniqueness check,review_hotel_id must be unique,PASS,0
28,elt_dim_review_hotel,null check,review_hotel_id must not be null,PASS,0
29,elt_dim_review_hotel,null check,review_hotel_id must not be null,PASS,0
30,elt_fact_bookings,uniqueness check,booking_id must be unique,PASS,0
31,elt_fact_bookings,null check,booking_id must not be null,PASS,0
32,elt_fact_bookings,null check,booking_id must not be null,PASS,0
33,elt_fact_bookings,null check,arrival_date_id must not be null,PASS,0
34,elt_fact_bookings,null check,reservation_status_date_id must not be null,PASS,0
35,elt_fact_bookings,null check,booking_hotel_type_id must not be null,PASS,0
36,elt_fact_bookings,null check,country_id must not be null,PASS,0
37,elt_fact_bookings,null check,meal_id must not be null,PASS,0
38,elt_fact_bookings,null check,market_segment_id must not be null,PASS,0
39,elt_fact_bookings,null check,distribution_channel_id must not be null,PASS,0
40,elt_fact_bookings,null check,customer_type_id must not be null,PASS,0
41,elt_fact_bookings,null check,deposit_type_id must not be null,PASS,0
42,elt_fact_bookings,null check,reserved_room_type_id must not be null,PASS,0
43,elt_fact_bookings,null check,assigned_room_type_id must not be null,PASS,0
44,elt_fact_bookings,range check,adr {'min': 0},PASS,0
45,elt_fact_bookings,range check,total_guests {'min': 0},PASS,0
46,elt_fact_bookings,range check,total_nights {'min': 0},PASS,0
47,elt_fact_reviews,uniqueness check,review_id must be unique,PASS,0
48,elt_fact_reviews,null check,review_id must not be null,PASS,0
49,elt_fact_reviews,null check,review_id must not be null,PASS,0
50,elt_fact_reviews,null check,review_date_id must not be null,PASS,0
51,elt_fact_reviews,null check,reviewer_country_id must not be null,PASS,0
52,elt_fact_reviews,null check,review_hotel_id must not be null,PASS,0
53,elt_fact_reviews,range check,"reviewer_score {'min': 0, 'max': 10}",PASS,0
54,elt_fact_reviews,range check,"average_score {'min': 0, 'max': 10}",PASS,0
55,elt_fact_hotel_monthly_performance,uniqueness check,performance_id must be unique,PASS,0
56,elt_fact_hotel_monthly_performance,null check,performance_id must not be null,PASS,0
57,elt_fact_hotel_monthly_performance,null check,performance_id must not be null,PASS,0
58,elt_fact_hotel_monthly_performance,null check,month_start_date_id must not be null,PASS,0
59,elt_fact_hotel_monthly_performance,range check,booking_count {'min': 0},PASS,0
60,elt_fact_hotel_monthly_performance,range check,review_count {'min': 0},PASS,0

,relationship,rule_type,child_column,parent_column,status,invalid_count
0,elt_fact_bookings.arrival_date_id -> elt_dim_date.date_id,referential integrity,arrival_date_id,date_id,PASS,0
1,elt_fact_bookings.reservation_status_date_id -> elt_dim_date.date_id,referential integrity,reservation_status_date_id,date_id,PASS,0
2,elt_fact_bookings.country_id -> elt_dim_country.country_id,referential integrity,country_id,country_id,PASS,0
3,elt_fact_bookings.booking_hotel_type_id -> elt_dim_booking_hotel_type.booking_hotel_type_id,referential integrity,booking_hotel_type_id,booking_hotel_type_id,PASS,0
4,elt_fact_bookings.meal_id -> elt_dim_meal.meal_id,referential integrity,meal_id,meal_id,PASS,0
5,elt_fact_bookings.market_segment_id -> elt_dim_market_segment.market_segment_id,referential integrity,market_segment_id,market_segment_id,PASS,0
6,elt_fact_bookings.distribution_channel_id -> elt_dim_distribution_channel.distribution_channel_id,referential integrity,distribution_channel_id,distribution_channel_id,PASS,0
7,elt_fact_bookings.customer_type_id -> elt_dim_customer_type.customer_type_id,referential integrity,customer_type_id,customer_type_id,PASS,0
8,elt_fact_bookings.deposit_type_id -> elt_dim_deposit_type.deposit_type_id,referential integrity,deposit_type_id,deposit_type_id,PASS,0
9,elt_fact_bookings.reserved_room_type_id -> elt_dim_room_type.room_type_id,referential integrity,reserved_room_type_id,room_type_id,PASS,0
10,elt_fact_bookings.assigned_room_type_id -> elt_dim_room_type.room_type_id,referential integrity,assigned_room_type_id,room_type_id,PASS,0
11,elt_fact_reviews.review_date_id -> elt_dim_date.date_id,referential integrity,review_date_id,date_id,PASS,0
12,elt_fact_reviews.reviewer_country_id -> elt_dim_country.country_id,referential integrity,reviewer_country_id,country_id,PASS,0
13,elt_fact_reviews.review_hotel_id -> elt_dim_review_hotel.review_hotel_id,referential integrity,review_hotel_id,review_hotel_id,PASS,0
14,elt_fact_hotel_monthly_performance.month_start_date_id -> elt_dim_date.date_id,referential integrity,month_start_date_id,date_id,PASS,0

Validation rules: uniqueness, null, range, datatype consistency, referential integrity, and data distribution
Distribution reports for final fact tables
Distribution report - ELT Fact Bookings

,dataset,column,count,mean,std,min,25%,50%,75%,max
0,ELT Fact Bookings,booking_id,119390.0,59695.500000,34465.068657,1.0,29848.25,59695.5,89542.75,119390.0
1,ELT Fact Bookings,arrival_date_id,119390.0,545.363958,223.680018,123.0,375.00,553.0,746.00,912.0
2,ELT Fact Bookings,reservation_status_date_id,119390.0,518.750147,227.476419,2.0,338.00,526.0,711.00,927.0
3,ELT Fact Bookings,booking_hotel_type_id,119390.0,1.335539,0.472181,1.0,1.00,1.0,2.00,2.0
4,ELT Fact Bookings,country_id,119390.0,202.408744,95.786593,2.0,125.00,175.0,289.00,403.0
5,ELT Fact Bookings,meal_id,119390.0,1.555742,1.068598,1.0,1.00,1.0,1.00,5.0
6,ELT Fact Bookings,market_segment_id,119390.0,5.928101,1.266726,1.0,5.00,6.0,7.00,8.0
7,ELT Fact Bookings,distribution_channel_id,119390.0,3.585317,0.907578,1.0,4.00,4.0,4.00,5.0
8,ELT Fact Bookings,customer_type_id,119390.0,3.137323,0.577040,1.0,3.00,3.0,3.00,4.0
9,ELT Fact Bookings,deposit_type_id,119390.0,1.124893,0.334678,1.0,1.00,1.0,1.00,3.0
10,ELT Fact Bookings,reserved_room_type_id,119390.0,1.989807,1.698823,1.0,1.00,1.0,4.00,12.0
11,ELT Fact Bookings,assigned_room_type_id,119390.0,2.329399,1.878762,1.0,1.00,1.0,4.00,12.0

Distribution report - ELT Fact Reviews

,dataset,column,count,mean,std,min,25%,50%,75%,max
0,ELT Fact Reviews,review_id,515738.0,257869.500000,148880.880902,1.0,128935.25,257869.5,386803.75,515738.0
1,ELT Fact Reviews,review_date_id,515738.0,532.558068,208.928124,157.0,360.00,534.0,712.00,887.0
2,ELT Fact Reviews,reviewer_country_id,515738.0,304.967805,118.010833,1.0,205.00,386.0,386.00,405.0
3,ELT Fact Reviews,review_hotel_id,515738.0,768.069844,452.887653,1.0,326.00,799.0,1178.00,1495.0
4,ELT Fact Reviews,additional_number_of_scoring,515738.0,498.081836,500.538467,1.0,169.00,341.0,660.00,2682.0
5,ELT Fact Reviews,average_score,515738.0,8.397487,0.548048,5.2,8.10,8.4,8.80,9.8
6,ELT Fact Reviews,total_number_of_reviews,515738.0,2743.743944,2317.464868,43.0,1161.00,2134.0,3613.00,16670.0
7,ELT Fact Reviews,total_number_of_reviews_reviewer_has_given,515738.0,7.166001,11.040228,1.0,1.00,3.0,8.00,355.0
8,ELT Fact Reviews,reviewer_score,515738.0,8.395077,1.637856,2.5,7.50,8.8,9.60,10.0
9,ELT Fact Reviews,positive_review_word_count,515738.0,17.776458,21.804185,0.0,5.00,11.0,22.00,395.0
10,ELT Fact Reviews,negative_review_word_count,515738.0,18.539450,29.690831,0.0,2.00,9.0,23.00,408.0
11,ELT Fact Reviews,positive_review_length,515738.0,93.171682,115.184799,0.0,25.00,57.0,118.00,1958.0

Distribution report - ELT Fact Hotel Monthly Performance

,dataset,column,count,mean,std,min,25%,50%,75%,max
0,ELT Fact Hotel Monthly Performance,performance_id,26.0,1.350000e+01,7.648529,1.000000,7.250000e+00,1.350000e+01,1.975000e+01,2.600000e+01
1,ELT Fact Hotel Monthly Performance,month_start_date_id,26.0,5.045769e+02,232.911000,123.000000,3.147500e+02,5.045000e+02,6.962500e+02,8.850000e+02
2,ELT Fact Hotel Monthly Performance,booking_count,26.0,4.591923e+03,1115.120367,2248.000000,3.889500e+03,4.941000e+03,5.373750e+03,6.313000e+03
3,ELT Fact Hotel Monthly Performance,canceled_booking_count,26.0,1.700923e+03,557.572375,486.000000,1.368750e+03,1.702000e+03,2.051250e+03,2.762000e+03
4,ELT Fact Hotel Monthly Performance,cancellation_rate,26.0,3.628114e-01,0.055776,0.207692,3.372093e-01,3.647432e-01,4.029832e-01,4.535303e-01
5,ELT Fact Hotel Monthly Performance,avg_adr,26.0,9.847454e+01,26.389792,60.580252,7.893890e+01,9.496523e+01,1.139049e+02,1.642484e+02
6,ELT Fact Hotel Monthly Performance,total_revenue_proxy,26.0,1.643214e+06,802639.413307,403694.850000,1.129425e+06,1.589362e+06,2.157052e+06,3.348627e+06
7,ELT Fact Hotel Monthly Performance,avg_total_nights,26.0,3.405490e+00,0.350168,2.740658,3.176497e+00,3.348657e+00,3.677650e+00,4.036954e+00
8,ELT Fact Hotel Monthly Performance,avg_total_guests,26.0,1.954466e+00,0.160902,1.626923,1.859031e+00,1.923938e+00,2.031232e+00,2.291132e+00
9,ELT Fact Hotel Monthly Performance,review_count,26.0,1.983608e+04,5775.260208,0.000000,1.936150e+04,2.084250e+04,2.267775e+04,2.727400e+04
10,ELT Fact Hotel Monthly Performance,avg_reviewer_score,26.0,8.072651e+00,1.648789,0.000000,8.321707e+00,8.386647e+00,8.450611e+00,8.545646e+00
11,ELT Fact Hotel Monthly Performance,avg_sentiment_word_balance,26.0,-7.367426e-01,0.760979,-2.102322,-1.240284e+00,-8.127662e-01,-2.391064e-01,1.236802e+00

ELT Validation Rules

,table,rule_type,rule,status,invalid_count
0,elt_dim_date,uniqueness check,date_id must be unique,PASS,0
1,elt_dim_date,null check,date_id must not be null,PASS,0
2,elt_dim_date,null check,date_id must not be null,PASS,0
3,elt_dim_booking_hotel_type,uniqueness check,booking_hotel_type_id must be unique,PASS,0
4,elt_dim_booking_hotel_type,null check,booking_hotel_type_id must not be null,PASS,0
5,elt_dim_booking_hotel_type,null check,booking_hotel_type_id must not be null,PASS,0
6,elt_dim_country,uniqueness check,country_id must be unique,PASS,0
7,elt_dim_country,null check,country_id must not be null,PASS,0
8,elt_dim_country,null check,country_id must not be null,PASS,0
9,elt_dim_meal,uniqueness check,meal_id must be unique,PASS,0
10,elt_dim_meal,null check,meal_id must not be null,PASS,0
11,elt_dim_meal,null check,meal_id must not be null,PASS,0
12,elt_dim_market_segment,uniqueness check,market_segment_id must be unique,PASS,0
13,elt_dim_market_segment,null check,market_segment_id must not be null,PASS,0
14,elt_dim_market_segment,null check,market_segment_id must not be null,PASS,0
15,elt_dim_distribution_channel,uniqueness check,distribution_channel_id must be unique,PASS,0
16,elt_dim_distribution_channel,null check,distribution_channel_id must not be null,PASS,0
17,elt_dim_distribution_channel,null check,distribution_channel_id must not be null,PASS,0
18,elt_dim_customer_type,uniqueness check,customer_type_id must be unique,PASS,0
19,elt_dim_customer_type,null check,customer_type_id must not be null,PASS,0
20,elt_dim_customer_type,null check,customer_type_id must not be null,PASS,0
21,elt_dim_deposit_type,uniqueness check,deposit_type_id must be unique,PASS,0
22,elt_dim_deposit_type,null check,deposit_type_id must not be null,PASS,0
23,elt_dim_deposit_type,null check,deposit_type_id must not be null,PASS,0
24,elt_dim_room_type,uniqueness check,room_type_id must be unique,PASS,0
25,elt_dim_room_type,null check,room_type_id must not be null,PASS,0
26,elt_dim_room_type,null check,room_type_id must not be null,PASS,0
27,elt_dim_review_hotel,uniqueness check,review_hotel_id must be unique,PASS,0
28,elt_dim_review_hotel,null check,review_hotel_id must not be null,PASS,0
29,elt_dim_review_hotel,null check,review_hotel_id must not be null,PASS,0
30,elt_fact_bookings,uniqueness check,booking_id must be unique,PASS,0
31,elt_fact_bookings,null check,booking_id must not be null,PASS,0
32,elt_fact_bookings,null check,booking_id must not be null,PASS,0
33,elt_fact_bookings,null check,arrival_date_id must not be null,PASS,0
34,elt_fact_bookings,null check,reservation_status_date_id must not be null,PASS,0
35,elt_fact_bookings,null check,booking_hotel_type_id must not be null,PASS,0
36,elt_fact_bookings,null check,country_id must not be null,PASS,0
37,elt_fact_bookings,null check,meal_id must not be null,PASS,0
38,elt_fact_bookings,null check,market_segment_id must not be null,PASS,0
39,elt_fact_bookings,null check,distribution_channel_id must not be null,PASS,0
40,elt_fact_bookings,null check,customer_type_id must not be null,PASS,0
41,elt_fact_bookings,null check,deposit_type_id must not be null,PASS,0
42,elt_fact_bookings,null check,reserved_room_type_id must not be null,PASS,0
43,elt_fact_bookings,null check,assigned_room_type_id must not be null,PASS,0
44,elt_fact_bookings,range check,adr {'min': 0},PASS,0
45,elt_fact_bookings,range check,total_guests {'min': 0},PASS,0
46,elt_fact_bookings,range check,total_nights {'min': 0},PASS,0
47,elt_fact_reviews,uniqueness check,review_id must be unique,PASS,0
48,elt_fact_reviews,null check,review_id must not be null,PASS,0
49,elt_fact_reviews,null check,review_id must not be null,PASS,0
50,elt_fact_reviews,null check,review_date_id must not be null,PASS,0
51,elt_fact_reviews,null check,reviewer_country_id must not be null,PASS,0
52,elt_fact_reviews,null check,review_hotel_id must not be null,PASS,0
53,elt_fact_reviews,range check,"reviewer_score {'min': 0, 'max': 10}",PASS,0
54,elt_fact_reviews,range check,"average_score {'min': 0, 'max': 10}",PASS,0
55,elt_fact_hotel_monthly_performance,uniqueness check,performance_id must be unique,PASS,0
56,elt_fact_hotel_monthly_performance,null check,performance_id must not be null,PASS,0
57,elt_fact_hotel_monthly_performance,null check,performance_id must not be null,PASS,0
58,elt_fact_hotel_monthly_performance,null check,month_start_date_id must not be null,PASS,0
59,elt_fact_hotel_monthly_performance,range check,booking_count {'min': 0},PASS,0
60,elt_fact_hotel_monthly_performance,range check,review_count {'min': 0},PASS,0

ELT Foreign Key Validation

,relationship,rule_type,child_column,parent_column,status,invalid_count
0,elt_fact_bookings.arrival_date_id -> elt_dim_date.date_id,referential integrity,arrival_date_id,date_id,PASS,0
1,elt_fact_bookings.reservation_status_date_id -> elt_dim_date.date_id,referential integrity,reservation_status_date_id,date_id,PASS,0
2,elt_fact_bookings.country_id -> elt_dim_country.country_id,referential integrity,country_id,country_id,PASS,0
3,elt_fact_bookings.booking_hotel_type_id -> elt_dim_booking_hotel_type.booking_hotel_type_id,referential integrity,booking_hotel_type_id,booking_hotel_type_id,PASS,0
4,elt_fact_bookings.meal_id -> elt_dim_meal.meal_id,referential integrity,meal_id,meal_id,PASS,0
5,elt_fact_bookings.market_segment_id -> elt_dim_market_segment.market_segment_id,referential integrity,market_segment_id,market_segment_id,PASS,0
6,elt_fact_bookings.distribution_channel_id -> elt_dim_distribution_channel.distribution_channel_id,referential integrity,distribution_channel_id,distribution_channel_id,PASS,0
7,elt_fact_bookings.customer_type_id -> elt_dim_customer_type.customer_type_id,referential integrity,customer_type_id,customer_type_id,PASS,0
8,elt_fact_bookings.deposit_type_id -> elt_dim_deposit_type.deposit_type_id,referential integrity,deposit_type_id,deposit_type_id,PASS,0
9,elt_fact_bookings.reserved_room_type_id -> elt_dim_room_type.room_type_id,referential integrity,reserved_room_type_id,room_type_id,PASS,0
10,elt_fact_bookings.assigned_room_type_id -> elt_dim_room_type.room_type_id,referential integrity,assigned_room_type_id,room_type_id,PASS,0
11,elt_fact_reviews.review_date_id -> elt_dim_date.date_id,referential integrity,review_date_id,date_id,PASS,0
12,elt_fact_reviews.reviewer_country_id -> elt_dim_country.country_id,referential integrity,reviewer_country_id,country_id,PASS,0
13,elt_fact_reviews.review_hotel_id -> elt_dim_review_hotel.review_hotel_id,referential integrity,review_hotel_id,review_hotel_id,PASS,0
14,elt_fact_hotel_monthly_performance.month_start_date_id -> elt_dim_date.date_id,referential integrity,month_start_date_id,date_id,PASS,0

Available ELT logical tables

                        table_name    rows  columns
0                         dim_date     927        8
1           dim_booking_hotel_type       3        2
2                      dim_country     405        2
3                         dim_meal       6        2
4               dim_market_segment       9        2
5         dim_distribution_channel       6        2
6                dim_customer_type       5        2
7                 dim_deposit_type       4        2
8                    dim_room_type      13        2
9                 dim_review_hotel    1495        6
10                   fact_bookings  119390       44
11                    fact_reviews  515738       24
12  fact_hotel_monthly_performance      26       12
13       metric_booking_by_segment       8        7
14          metric_review_by_hotel    1492        8
15              metric_monthly_kpi      26       12

### Export Pipeline to Warehouse

In [ ]:
ELT_WAREHOUSE_URL = os.getenv(
    "ELT_WAREHOUSE_URL",
    "postgresql+psycopg2://neondb_owner:npg_FdUZY71DojnM@ep-lively-bar-aiqh9mku-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require",
)

if is_placeholder(ELT_WAREHOUSE_URL):
    raise ValueError("Paste the Neon ELT PostgreSQL URL into ELT_WAREHOUSE_URL before running this cell.")

elt_warehouse_engine = create_engine(ELT_WAREHOUSE_URL, pool_pre_ping=True)
elt_warehouse_mode = "neon_postgresql"
elt_physical_table_names = load_tables_to_warehouse(
    elt_tables,
    elt_warehouse_engine,
    prefix="elt",
    create_constraints=True,
    chunksize=1000,
)

print("Warehouse mode:", elt_warehouse_mode)
print("Physical table names:")
display(pd.DataFrame([
    {"logical_table": k, "physical_table": v}
    for k, v in elt_physical_table_names.items()
]))

OK: drop elt_metric_monthly_kpi if exists
OK: drop elt_metric_review_by_hotel if exists
OK: drop elt_metric_booking_by_segment if exists
OK: drop elt_fact_hotel_monthly_performance if exists
OK: drop elt_fact_reviews if exists
OK: drop elt_fact_bookings if exists
OK: drop elt_dim_review_hotel if exists
OK: drop elt_dim_room_type if exists
OK: drop elt_dim_deposit_type if exists
OK: drop elt_dim_customer_type if exists
OK: drop elt_dim_distribution_channel if exists
OK: drop elt_dim_market_segment if exists
OK: drop elt_dim_meal if exists
OK: drop elt_dim_country if exists
OK: drop elt_dim_booking_hotel_type if exists
OK: drop elt_dim_date if exists
Loaded elt_dim_date: 927 rows, 8 columns
Loaded elt_dim_booking_hotel_type: 3 rows, 2 columns
Loaded elt_dim_country: 405 rows, 2 columns
Loaded elt_dim_meal: 6 rows, 2 columns
Loaded elt_dim_market_segment: 9 rows, 2 columns
Loaded elt_dim_distribution_channel: 6 rows, 2 columns
Loaded elt_dim_customer_type: 5 rows, 2 columns
Loaded elt_dim_deposit_type: 4 rows, 2 columns
Loaded elt_dim_room_type: 13 rows, 2 columns
Loaded elt_dim_review_hotel: 1,495 rows, 6 columns
Loaded elt_fact_bookings: 119,390 rows, 44 columns
Loaded elt_fact_reviews: 515,738 rows, 24 columns
Loaded elt_fact_hotel_monthly_performance: 26 rows, 12 columns
Loaded elt_metric_booking_by_segment: 8 rows, 7 columns
Loaded elt_metric_review_by_hotel: 1,492 rows, 8 columns
Loaded elt_metric_monthly_kpi: 26 rows, 12 columns
OK: set elt_dim_date.date_id NOT NULL
OK: primary key for elt_dim_date.date_id
OK: set elt_dim_booking_hotel_type.booking_hotel_type_id NOT NULL
OK: primary key for elt_dim_booking_hotel_type.booking_hotel_type_id
OK: set elt_dim_country.country_id NOT NULL
OK: primary key for elt_dim_country.country_id
OK: set elt_dim_meal.meal_id NOT NULL
OK: primary key for elt_dim_meal.meal_id
OK: set elt_dim_market_segment.market_segment_id NOT NULL
OK: primary key for elt_dim_market_segment.market_segment_id
OK: set elt_dim_distribution_channel.distribution_channel_id NOT NULL
OK: primary key for elt_dim_distribution_channel.distribution_channel_id
OK: set elt_dim_customer_type.customer_type_id NOT NULL
OK: primary key for elt_dim_customer_type.customer_type_id
OK: set elt_dim_deposit_type.deposit_type_id NOT NULL
OK: primary key for elt_dim_deposit_type.deposit_type_id
OK: set elt_dim_room_type.room_type_id NOT NULL
OK: primary key for elt_dim_room_type.room_type_id
OK: set elt_dim_review_hotel.review_hotel_id NOT NULL
OK: primary key for elt_dim_review_hotel.review_hotel_id
OK: set elt_fact_bookings.booking_id NOT NULL
OK: primary key for elt_fact_bookings.booking_id
OK: set elt_fact_reviews.review_id NOT NULL
OK: primary key for elt_fact_reviews.review_id
OK: set elt_fact_hotel_monthly_performance.performance_id NOT NULL
OK: primary key for elt_fact_hotel_monthly_performance.performance_id
OK: index idx_elt_fact_bookings_arrival_date_id
OK: foreign key fk_elt_fact_bookings_arrival_date_id
OK: index idx_elt_fact_bookings_reservation_status_date_id
OK: foreign key fk_elt_fact_bookings_reservation_status_date_id
OK: index idx_elt_fact_bookings_country_id
OK: foreign key fk_elt_fact_bookings_country_id
OK: index idx_elt_fact_bookings_booking_hotel_type_id
OK: foreign key fk_elt_fact_bookings_booking_hotel_type_id
OK: index idx_elt_fact_bookings_meal_id
OK: foreign key fk_elt_fact_bookings_meal_id
OK: index idx_elt_fact_bookings_market_segment_id
OK: foreign key fk_elt_fact_bookings_market_segment_id
OK: index idx_elt_fact_bookings_distribution_channel_id
OK: foreign key fk_elt_fact_bookings_distribution_channel_id
OK: index idx_elt_fact_bookings_customer_type_id
OK: foreign key fk_elt_fact_bookings_customer_type_id
OK: index idx_elt_fact_bookings_deposit_type_id
OK: foreign key fk_elt_fact_bookings_deposit_type_id
OK: index idx_elt_fact_bookings_reserved_room_type_id
OK: foreign key fk_elt_fact_bookings_reserved_room_type_id
OK: index idx_elt_fact_bookings_assigned_room_type_id
OK: foreign key fk_elt_fact_bookings_assigned_room_type_id
OK: index idx_elt_fact_reviews_review_date_id
OK: foreign key fk_elt_fact_reviews_review_date_id
OK: index idx_elt_fact_reviews_reviewer_country_id
OK: foreign key fk_elt_fact_reviews_reviewer_country_id
OK: index idx_elt_fact_reviews_review_hotel_id
OK: foreign key fk_elt_fact_reviews_review_hotel_id
OK: index idx_elt_fact_hotel_monthly_performance_month_start_date_id
OK: foreign key fk_elt_fact_hotel_monthly_performance_month_start_date_id
Warehouse mode: neon_postgresql
Physical table names:

                     logical_table                      physical_table
0                         dim_date                        elt_dim_date
1           dim_booking_hotel_type          elt_dim_booking_hotel_type
2                      dim_country                     elt_dim_country
3                         dim_meal                        elt_dim_meal
4               dim_market_segment              elt_dim_market_segment
5         dim_distribution_channel        elt_dim_distribution_channel
6                dim_customer_type               elt_dim_customer_type
7                 dim_deposit_type                elt_dim_deposit_type
8                    dim_room_type                   elt_dim_room_type
9                 dim_review_hotel                elt_dim_review_hotel
10                   fact_bookings                   elt_fact_bookings
11                    fact_reviews                    elt_fact_reviews
12  fact_hotel_monthly_performance  elt_fact_hotel_monthly_performance
13       metric_booking_by_segment       elt_metric_booking_by_segment
14          metric_review_by_hotel          elt_metric_review_by_hotel
15              metric_monthly_kpi              elt_metric_monthly_kpi

### Analytic SQL Queries

In [ ]:
elt_analytic_results = run_analytic_queries(elt_warehouse_engine, prefix="elt")

'''
-- QUERY 1: Monthly booking volume and average ADR

SELECT
d.year_month,
COUNT(*) AS booking_count,
ROUND(CAST(AVG(fb.adr) AS NUMERIC), 2) AS avg_adr
FROM public.elt_fact_bookings AS fb
JOIN public.elt_dim_date AS d
ON fb.arrival_date_id = d.date_id
GROUP BY d.year_month
ORDER BY d.year_month
LIMIT 24;

-- QUERY 2: Cancellation rate by hotel type

SELECT
ht.hotel_type,
COUNT(*) AS booking_count,
ROUND(
CAST(AVG(fb.is_canceled) * 100 AS NUMERIC),
2
) AS cancellation_rate_pct
FROM public.elt_fact_bookings AS fb
JOIN public.elt_dim_booking_hotel_type AS ht
ON fb.booking_hotel_type_id = ht.booking_hotel_type_id
GROUP BY ht.hotel_type
ORDER BY cancellation_rate_pct DESC;

-- QUERY 3: Average ADR by market segment

SELECT
ms.market_segment,
COUNT(*) AS booking_count,
ROUND(CAST(AVG(fb.adr) AS NUMERIC), 2) AS avg_adr
FROM public.elt_fact_bookings AS fb
JOIN public.elt_dim_market_segment AS ms
ON fb.market_segment_id = ms.market_segment_id
GROUP BY ms.market_segment
ORDER BY avg_adr DESC
LIMIT 10;

-- QUERY 4: Revenue proxy by customer type
Revenue proxy = ADR × total nights

SELECT
ct.customer_type,
COUNT(*) AS booking_count,
ROUND(
CAST(SUM(fb.adr * fb.total_nights) AS NUMERIC),
2
) AS revenue_proxy
FROM public.elt_fact_bookings AS fb
JOIN public.elt_dim_customer_type AS ct
ON fb.customer_type_id = ct.customer_type_id
GROUP BY ct.customer_type
ORDER BY revenue_proxy DESC;

-- QUERY 5: Room-change rate by reserved room type

SELECT
rr.room_type AS reserved_room_type,
COUNT(*) AS booking_count,
ROUND(
CAST(AVG(fb.room_changed) * 100 AS NUMERIC),
2
) AS room_change_rate_pct
FROM public.elt_fact_bookings AS fb
JOIN public.elt_dim_room_type AS rr
ON fb.reserved_room_type_id = rr.room_type_id
GROUP BY rr.room_type
ORDER BY room_change_rate_pct DESC
LIMIT 10;

-- QUERY 6: Review score by reviewer country

SELECT
c.country_name AS reviewer_country,
COUNT(*) AS review_count,
ROUND(
CAST(AVG(fr.reviewer_score) AS NUMERIC),
2
) AS avg_reviewer_score
FROM public.elt_fact_reviews AS fr
JOIN public.elt_dim_country AS c
ON fr.reviewer_country_id = c.country_id
GROUP BY c.country_name
HAVING COUNT(*) >= 20
ORDER BY avg_reviewer_score DESC
LIMIT 15;

-- QUERY 7: Top reviewed hotels

SELECT
rh.hotel_name,
COUNT(*) AS review_count,
ROUND(
CAST(AVG(fr.reviewer_score) AS NUMERIC),
2
) AS avg_reviewer_score
FROM public.elt_fact_reviews AS fr
JOIN public.elt_dim_review_hotel AS rh
ON fr.review_hotel_id = rh.review_hotel_id
GROUP BY rh.hotel_name
ORDER BY review_count DESC
LIMIT 15;

-- QUERY 8: Positive and negative review-word balance by hotel

SELECT
rh.hotel_name,
COUNT(*) AS review_count,
ROUND(
CAST(AVG(fr.positive_review_word_count) AS NUMERIC),
2
) AS avg_positive_words,
ROUND(
CAST(AVG(fr.negative_review_word_count) AS NUMERIC),
2
) AS avg_negative_words,
ROUND(
CAST(AVG(fr.sentiment_word_balance) AS NUMERIC),
2
) AS avg_sentiment_word_balance
FROM public.elt_fact_reviews AS fr
JOIN public.elt_dim_review_hotel AS rh
ON fr.review_hotel_id = rh.review_hotel_id
GROUP BY rh.hotel_name
HAVING COUNT(*) >= 20
ORDER BY avg_sentiment_word_balance DESC
LIMIT 15;

-- QUERY 9: Merged monthly hotel performance

SELECT
d.year_month,
fp.booking_count,
fp.review_count,
ROUND(
CAST(fp.cancellation_rate * 100 AS NUMERIC),
2
) AS cancellation_rate_pct,
ROUND(CAST(fp.avg_adr AS NUMERIC), 2) AS avg_adr,
ROUND(
CAST(fp.avg_reviewer_score AS NUMERIC),
2
) AS avg_reviewer_score
FROM public.elt_fact_hotel_monthly_performance AS fp
JOIN public.elt_dim_date AS d
ON fp.month_start_date_id = d.date_id
ORDER BY d.year_month
LIMIT 24;

-- QUERY 10: Special requests versus cancellation

SELECT
fb.total_of_special_requests,
COUNT(*) AS booking_count,
ROUND(
CAST(AVG(fb.is_canceled) * 100 AS NUMERIC),
2
) AS cancellation_rate_pct,
ROUND(CAST(AVG(fb.adr) AS NUMERIC), 2) AS avg_adr
FROM public.elt_fact_bookings AS fb
GROUP BY fb.total_of_special_requests
ORDER BY fb.total_of_special_requests;
'''

Analytic SQL Query - 01_monthly_booking_volume

   year_month  booking_count  avg_adr
0     2015-07           2776    97.83
1     2015-08           3889   105.92
2     2015-09           5114    94.82
3     2015-10           4957    78.90
4     2015-11           2340    60.58
5     2015-12           2920    74.08
6     2016-01           2248    64.77
7     2016-02           3891    70.10
8     2016-03           4824    79.07
9     2016-04           5428    88.92
10    2016-05           5478    96.40
11    2016-06           5292   106.98
12    2016-07           4572   125.48
13    2016-08           5063   142.89
14    2016-09           5394   114.75
15    2016-10           6203    95.11
16    2016-11           4454    80.74
17    2016-12           3860    86.37
18    2017-01           3681    73.78
19    2017-02           4177    76.82
20    2017-03           4970    82.24
21    2017-04           5661   111.37
22    2017-05           6313   119.37
23    2017-06           5647   125.76

Analytic SQL Query - 02_cancellation_rate_by_hotel_type

     hotel_type  booking_count  cancellation_rate_pct
0    City Hotel          79330                  41.73
1  Resort Hotel          40060                  27.76

Analytic SQL Query - 03_average_adr_by_market_segment

  market_segment  booking_count  avg_adr
0      Online TA          56477   117.20
1         Direct          12606   115.45
2       Aviation            237   100.14
3  Offline TA/TO          24219    87.35
4         Groups          19811    79.48
5      Corporate           5295    69.36
6      Undefined              2    15.00
7  Complementary            743     2.89

Analytic SQL Query - 04_revenue_proxy_by_customer_type

     customer_type  booking_count  revenue_proxy
0        Transient          89613    34199103.91
1  Transient-Party          25124     6544699.38
2         Contract           4076     1839077.75
3            Group            577      140680.29

Analytic SQL Query - 05_room_change_rate

  reserved_room_type  booking_count  room_change_rate_pct
0                  L              6                 83.33
1                  A          85994                 14.41
2                  B           1118                 11.63
3                  E           6535                  9.36
4                  D          19201                  7.63
5                  F           2897                  6.56
6                  C            932                  5.26
7                  H            601                  2.83
8                  G           2094                  2.53
9                  P             12                  0.00

Analytic SQL Query - 06_review_score_by_reviewer_country

            reviewer_country  review_count  avg_reviewer_score
0                 Kyrgyzstan            21                9.00
1              Liechtenstein            20                8.89
2                Puerto Rico           180                8.80
3                     Panama           122                8.80
4   United States of America         35437                8.79
5                   Honduras            22                8.78
6                El Salvador            24                8.69
7                     Israel          6610                8.69
8        Trinidad and Tobago           154                8.68
9                New Zealand          3237                8.65
10                 Venezuela            78                8.64
11                   Ecuador            61                8.62
12                   Cura ao            41                8.61
13                   Bermuda           103                8.60
14                 Australia         21686                8.59

Analytic SQL Query - 07_top_reviewed_hotels

,hotel_name,review_count,avg_reviewer_score
0,Britannia International Hotel Canary Wharf,4789,6.83
1,Strand Palace Hotel,4256,8.13
2,Park Plaza Westminster Bridge London,4169,8.65
3,Copthorne Tara Hotel London Kensington,3578,8.09
4,DoubleTree by Hilton Hotel London Tower of London,3212,8.66
5,Grand Royale London Hyde Park,2958,7.62
6,Holiday Inn London Kensington,2768,7.72
7,Hilton London Metropole,2628,7.32
8,Millennium Gloucester Hotel London,2565,7.67
9,Intercontinental London The O2,2551,9.45
10,Park Grand Paddington Court,2288,8.19
11,Hilton London Wembley,2227,8.76
12,Park Plaza County Hall London,2223,8.37
13,Blakemore Hyde Park,2178,8.53
14,Park Plaza London Riverbank,2167,8.23

Analytic SQL Query - 08_review_word_balance_by_hotel

,hotel_name,review_count,avg_positive_words,avg_negative_words,avg_sentiment_word_balance
0,Pillows Anna van den Vondel Amsterdam,56,47.96,14.09,33.88
1,Hotel Villa Lafayette Paris IX,25,37.68,12.24,25.44
2,H tel Thoumieux,37,39.11,13.73,25.38
3,Hotel Casa Camper,301,31.68,7.42,24.27
4,Goralska R sidences H tel Paris Bastille,24,39.00,16.17,22.83
5,Hotel Le Mareuil,47,30.77,8.70,22.06
6,Hotel Whistler,28,36.07,14.29,21.79
7,Small Luxury Hotel Altstadt Vienna,173,31.06,10.55,20.51
8,Hotel Monge,115,27.83,8.30,19.53
9,Hotel K nig von Ungarn,268,27.28,8.09,19.20
10,H tel Fabric,103,27.66,8.57,19.09
11,Hollmann Beletage Design Boutique,102,29.85,11.00,18.85
12,Hotel The Serras,213,26.53,7.89,18.64
13,Relais H tel du Vieux Paris,156,30.61,12.31,18.29
14,Catalonia Magdalenes,311,29.57,11.49,18.08

Analytic SQL Query - 09_merged_monthly_performance

,year_month,booking_count,review_count,cancellation_rate_pct,avg_adr,avg_reviewer_score
0,2015-07,2776,0,45.35,97.83,0.00
1,2015-08,3889,19320,41.09,105.92,8.38
2,2015-09,5114,19738,40.95,94.82,8.26
3,2015-10,4957,19486,34.94,78.90,8.20
4,2015-11,2340,18056,20.77,60.58,8.32
5,2015-12,2920,17927,33.32,74.08,8.47
6,2016-01,2248,19510,24.78,64.77,8.52
7,2016-02,3891,18856,34.36,70.10,8.55
8,2016-03,4824,20744,30.62,79.07,8.52
9,2016-04,5428,21481,37.97,88.92,8.48
10,2016-05,5478,23071,34.96,96.40,8.44
11,2016-06,5292,20941,39.61,106.98,8.41
12,2016-07,4572,25885,32.79,125.48,8.39
13,2016-08,5063,27274,36.05,142.89,8.44
14,2016-09,5394,22690,37.49,114.75,8.32
15,2016-10,6203,24357,40.53,95.11,8.31
16,2016-11,4454,17914,36.73,80.74,8.36
17,2016-12,3860,21680,36.22,86.37,8.39
18,2017-01,3681,22641,33.96,73.78,8.45
19,2017-02,4177,19514,32.54,76.82,8.51
20,2017-03,4970,20366,33.64,82.24,8.44
21,2017-04,5661,21402,43.51,111.37,8.38
22,2017-05,6313,23419,43.75,119.37,8.32
23,2017-06,5647,21955,43.19,125.76,8.37

Analytic SQL Query - 10_special_requests_vs_cancellation

   total_of_special_requests  booking_count  cancellation_rate_pct  avg_adr
0                        0.0          70318                  47.72    94.96
1                        1.0          33226                  22.02   108.46
2                        2.0          12969                  22.10   117.03
3                        3.0           2497                  17.86   123.85
4                        4.0            340                  10.59   130.57
5                        5.0             40                   5.00   127.75

### Process Log

In [ ]:
log_step("Pipeline Complete", "ELT pipeline completed", PIPELINE_START_TIME)
show_process_log()

,timestamp,step,status,detail,rows,columns,execution_seconds
0,2026-06-14 11:47:22,Extract,SUCCESS,Source 1 - Hotel Bookings Raw loaded from /content/hotel_pipeline_data/hotel_bookings.csv,119390.0,32.0,1.1321
1,2026-06-14 11:47:42,Extract,SUCCESS,Source 2 - Hotel Reviews Raw loaded from /content/hotel_pipeline_data/hotel_reviews.ndjson,515738.0,17.0,19.2671
2,2026-06-14 11:47:47,Overview Report,SUCCESS,Source 1 - Hotel Bookings Raw,119390.0,32.0,5.3454
3,2026-06-14 11:48:15,Overview Report,SUCCESS,Source 2 - Hotel Reviews Raw,515738.0,17.0,27.2769
4,2026-06-14 11:48:15,Memory Report,SUCCESS,Source 1 - Hotel Bookings Raw,119390.0,32.0,0.3297
5,2026-06-14 11:48:16,Memory Report,SUCCESS,Source 2 - Hotel Reviews Raw,515738.0,17.0,1.3306
6,2026-06-14 11:48:17,Frequency Display,SUCCESS,Source 1 - Hotel Bookings Raw: 12 categorical columns shown,119390.0,32.0,0.4971
7,2026-06-14 11:48:20,Frequency Display,SUCCESS,Source 2 - Hotel Reviews Raw: 8 categorical columns shown,515738.0,17.0,3.3700
8,2026-06-14 11:48:21,Unusual Values Report,SUCCESS,Source 1 - Hotel Bookings Raw,119390.0,32.0,0.4563
9,2026-06-14 11:48:25,Unusual Values Report,SUCCESS,Source 2 - Hotel Reviews Raw,515738.0,17.0,3.9962
10,2026-06-14 11:48:25,Datatype Consistency Report,SUCCESS,Source 1 - Hotel Bookings Raw,119390.0,32.0,0.1572
11,2026-06-14 11:48:26,Datatype Consistency Report,SUCCESS,Source 2 - Hotel Reviews Raw,515738.0,17.0,0.7630
12,2026-06-14 11:48:26,Distribution Report,SUCCESS,Source 1 - Hotel Bookings Raw,119390.0,32.0,0.0917
13,2026-06-14 11:48:26,Distribution Report,SUCCESS,Source 2 - Hotel Reviews Raw,515738.0,17.0,0.2100
14,2026-06-14 11:48:44,ELT Load Raw to Lake,SUCCESS,Loaded raw standardized datasets into lake_raw_hotel_bookings and lake_raw_hotel_reviews,635128.0,49.0,17.9492
15,2026-06-14 11:48:44,Quality Assessment Plan,SUCCESS,Source 1 - Hotel Bookings using ELT SQL transform after lake load,119390.0,32.0,0.0391
16,2026-06-14 11:48:44,Quality Assessment Plan,SUCCESS,Source 2 - Hotel Reviews using ELT SQL transform after lake load,515738.0,17.0,0.2187
17,2026-06-14 11:48:46,Range Check Report,SUCCESS,Source 1 - Hotel Bookings Raw,119390.0,32.0,0.0302
18,2026-06-14 11:48:46,Range Check Report,SUCCESS,Source 2 - Hotel Reviews Raw,515738.0,17.0,0.0336
19,2026-06-14 11:49:26,ELT SQL Transform,SUCCESS,"Built SQL-cleaned tables, snowflake schema, foreign keys, and metric analytics in lake",NaN,NaN,40.2118
20,2026-06-14 11:49:48,Overview Report,SUCCESS,Source 1 - Hotel Bookings SQL Clean,119390.0,49.0,8.1393
21,2026-06-14 11:50:09,Overview Report,SUCCESS,Source 2 - Hotel Reviews SQL Clean,515738.0,30.0,20.6191
22,2026-06-14 11:50:10,Memory Report,SUCCESS,Source 1 - Hotel Bookings SQL Clean,119390.0,49.0,0.8672
23,2026-06-14 11:50:11,Memory Report,SUCCESS,Source 2 - Hotel Reviews SQL Clean,515738.0,30.0,1.0184
24,2026-06-14 11:50:11,Frequency Display,SUCCESS,Source 1 - Hotel Bookings SQL Clean: 12 categorical columns shown,119390.0,49.0,0.8362
25,2026-06-14 11:50:14,Frequency Display,SUCCESS,Source 2 - Hotel Reviews SQL Clean: 7 categorical columns shown,515738.0,30.0,2.6682
26,2026-06-14 11:50:15,Unusual Values Report,SUCCESS,Source 1 - Hotel Bookings SQL Clean,119390.0,49.0,1.1614
27,2026-06-14 11:50:17,Unusual Values Report,SUCCESS,Source 2 - Hotel Reviews SQL Clean,515738.0,30.0,2.0902
28,2026-06-14 11:50:18,Datatype Consistency Report,SUCCESS,Source 1 - Hotel Bookings SQL Clean,119390.0,49.0,0.3502
29,2026-06-14 11:50:18,Datatype Consistency Report,SUCCESS,Source 2 - Hotel Reviews SQL Clean,515738.0,30.0,0.6505
30,2026-06-14 11:50:18,Distribution Report,SUCCESS,Source 1 - Hotel Bookings SQL Clean,119390.0,49.0,0.0966
31,2026-06-14 11:50:19,Distribution Report,SUCCESS,Source 2 - Hotel Reviews SQL Clean,515738.0,30.0,0.2445
32,2026-06-14 11:50:31,Validation Suite,SUCCESS,elt warehouse validation complete,NaN,NaN,1.0446
33,2026-06-14 11:50:31,Distribution Report,SUCCESS,ELT Fact Bookings,119390.0,44.0,0.1255
34,2026-06-14 11:50:31,Distribution Report,SUCCESS,ELT Fact Reviews,515738.0,24.0,0.3545
35,2026-06-14 11:50:31,Distribution Report,SUCCESS,ELT Fact Hotel Monthly Performance,26.0,12.0,0.0486
36,2026-06-14 11:50:33,Warehouse DDL,SUCCESS,drop elt_metric_monthly_kpi if exists,NaN,NaN,NaN
37,2026-06-14 11:50:33,Warehouse DDL,SUCCESS,drop elt_metric_review_by_hotel if exists,NaN,NaN,NaN
38,2026-06-14 11:50:33,Warehouse DDL,SUCCESS,drop elt_metric_booking_by_segment if exists,NaN,NaN,NaN
39,2026-06-14 11:50:33,Warehouse DDL,SUCCESS,drop elt_fact_hotel_monthly_performance if exists,NaN,NaN,NaN
40,2026-06-14 11:50:33,Warehouse DDL,SUCCESS,drop elt_fact_reviews if exists,NaN,NaN,NaN
41,2026-06-14 11:50:34,Warehouse DDL,SUCCESS,drop elt_fact_bookings if exists,NaN,NaN,NaN
42,2026-06-14 11:50:34,Warehouse DDL,SUCCESS,drop elt_dim_review_hotel if exists,NaN,NaN,NaN
43,2026-06-14 11:50:34,Warehouse DDL,SUCCESS,drop elt_dim_room_type if exists,NaN,NaN,NaN
44,2026-06-14 11:50:34,Warehouse DDL,SUCCESS,drop elt_dim_deposit_type if exists,NaN,NaN,NaN
45,2026-06-14 11:50:34,Warehouse DDL,SUCCESS,drop elt_dim_customer_type if exists,NaN,NaN,NaN
46,2026-06-14 11:50:34,Warehouse DDL,SUCCESS,drop elt_dim_distribution_channel if exists,NaN,NaN,NaN
47,2026-06-14 11:50:34,Warehouse DDL,SUCCESS,drop elt_dim_market_segment if exists,NaN,NaN,NaN
48,2026-06-14 11:50:34,Warehouse DDL,SUCCESS,drop elt_dim_meal if exists,NaN,NaN,NaN
49,2026-06-14 11:50:34,Warehouse DDL,SUCCESS,drop elt_dim_country if exists,NaN,NaN,NaN
50,2026-06-14 11:50:35,Warehouse DDL,SUCCESS,drop elt_dim_booking_hotel_type if exists,NaN,NaN,NaN
51,2026-06-14 11:50:35,Warehouse DDL,SUCCESS,drop elt_dim_date if exists,NaN,NaN,NaN
52,2026-06-14 11:52:47,Warehouse DDL,SUCCESS,set elt_dim_date.date_id NOT NULL,NaN,NaN,NaN
53,2026-06-14 11:52:47,Warehouse DDL,SUCCESS,primary key for elt_dim_date.date_id,NaN,NaN,NaN
54,2026-06-14 11:52:48,Warehouse DDL,SUCCESS,set elt_dim_booking_hotel_type.booking_hotel_type_id NOT NULL,NaN,NaN,NaN
55,2026-06-14 11:52:48,Warehouse DDL,SUCCESS,primary key for elt_dim_booking_hotel_type.booking_hotel_type_id,NaN,NaN,NaN
56,2026-06-14 11:52:48,Warehouse DDL,SUCCESS,set elt_dim_country.country_id NOT NULL,NaN,NaN,NaN
57,2026-06-14 11:52:48,Warehouse DDL,SUCCESS,primary key for elt_dim_country.country_id,NaN,NaN,NaN
58,2026-06-14 11:52:48,Warehouse DDL,SUCCESS,set elt_dim_meal.meal_id NOT NULL,NaN,NaN,NaN
59,2026-06-14 11:52:48,Warehouse DDL,SUCCESS,primary key for elt_dim_meal.meal_id,NaN,NaN,NaN
60,2026-06-14 11:52:48,Warehouse DDL,SUCCESS,set elt_dim_market_segment.market_segment_id NOT NULL,NaN,NaN,NaN
61,2026-06-14 11:52:48,Warehouse DDL,SUCCESS,primary key for elt_dim_market_segment.market_segment_id,NaN,NaN,NaN
62,2026-06-14 11:52:48,Warehouse DDL,SUCCESS,set elt_dim_distribution_channel.distribution_channel_id NOT NULL,NaN,NaN,NaN
63,2026-06-14 11:52:49,Warehouse DDL,SUCCESS,primary key for elt_dim_distribution_channel.distribution_channel_id,NaN,NaN,NaN
64,2026-06-14 11:52:49,Warehouse DDL,SUCCESS,set elt_dim_customer_type.customer_type_id NOT NULL,NaN,NaN,NaN
65,2026-06-14 11:52:49,Warehouse DDL,SUCCESS,primary key for elt_dim_customer_type.customer_type_id,NaN,NaN,NaN
66,2026-06-14 11:52:49,Warehouse DDL,SUCCESS,set elt_dim_deposit_type.deposit_type_id NOT NULL,NaN,NaN,NaN
67,2026-06-14 11:52:49,Warehouse DDL,SUCCESS,primary key for elt_dim_deposit_type.deposit_type_id,NaN,NaN,NaN
68,2026-06-14 11:52:49,Warehouse DDL,SUCCESS,set elt_dim_room_type.room_type_id NOT NULL,NaN,NaN,NaN
69,2026-06-14 11:52:49,Warehouse DDL,SUCCESS,primary key for elt_dim_room_type.room_type_id,NaN,NaN,NaN
70,2026-06-14 11:52:49,Warehouse DDL,SUCCESS,set elt_dim_review_hotel.review_hotel_id NOT NULL,NaN,NaN,NaN
71,2026-06-14 11:52:50,Warehouse DDL,SUCCESS,primary key for elt_dim_review_hotel.review_hotel_id,NaN,NaN,NaN
72,2026-06-14 11:52:50,Warehouse DDL,SUCCESS,set elt_fact_bookings.booking_id NOT NULL,NaN,NaN,NaN
73,2026-06-14 11:52:50,Warehouse DDL,SUCCESS,primary key for elt_fact_bookings.booking_id,NaN,NaN,NaN
74,2026-06-14 11:52:50,Warehouse DDL,SUCCESS,set elt_fact_reviews.review_id NOT NULL,NaN,NaN,NaN
75,2026-06-14 11:52:50,Warehouse DDL,SUCCESS,primary key for elt_fact_reviews.review_id,NaN,NaN,NaN
76,2026-06-14 11:52:50,Warehouse DDL,SUCCESS,set elt_fact_hotel_monthly_performance.performance_id NOT NULL,NaN,NaN,NaN
77,2026-06-14 11:52:51,Warehouse DDL,SUCCESS,primary key for elt_fact_hotel_monthly_performance.performance_id,NaN,NaN,NaN
78,2026-06-14 11:52:51,Warehouse DDL,SUCCESS,index idx_elt_fact_bookings_arrival_date_id,NaN,NaN,NaN
79,2026-06-14 11:52:51,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_bookings_arrival_date_id,NaN,NaN,NaN
80,2026-06-14 11:52:51,Warehouse DDL,SUCCESS,index idx_elt_fact_bookings_reservation_status_date_id,NaN,NaN,NaN
81,2026-06-14 11:52:51,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_bookings_reservation_status_date_id,NaN,NaN,NaN
82,2026-06-14 11:52:51,Warehouse DDL,SUCCESS,index idx_elt_fact_bookings_country_id,NaN,NaN,NaN
83,2026-06-14 11:52:52,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_bookings_country_id,NaN,NaN,NaN
84,2026-06-14 11:52:52,Warehouse DDL,SUCCESS,index idx_elt_fact_bookings_booking_hotel_type_id,NaN,NaN,NaN
85,2026-06-14 11:52:52,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_bookings_booking_hotel_type_id,NaN,NaN,NaN
86,2026-06-14 11:52:52,Warehouse DDL,SUCCESS,index idx_elt_fact_bookings_meal_id,NaN,NaN,NaN
87,2026-06-14 11:52:52,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_bookings_meal_id,NaN,NaN,NaN
88,2026-06-14 11:52:52,Warehouse DDL,SUCCESS,index idx_elt_fact_bookings_market_segment_id,NaN,NaN,NaN
89,2026-06-14 11:52:52,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_bookings_market_segment_id,NaN,NaN,NaN
90,2026-06-14 11:52:53,Warehouse DDL,SUCCESS,index idx_elt_fact_bookings_distribution_channel_id,NaN,NaN,NaN
91,2026-06-14 11:52:53,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_bookings_distribution_channel_id,NaN,NaN,NaN
92,2026-06-14 11:52:53,Warehouse DDL,SUCCESS,index idx_elt_fact_bookings_customer_type_id,NaN,NaN,NaN
93,2026-06-14 11:52:53,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_bookings_customer_type_id,NaN,NaN,NaN
94,2026-06-14 11:52:53,Warehouse DDL,SUCCESS,index idx_elt_fact_bookings_deposit_type_id,NaN,NaN,NaN
95,2026-06-14 11:52:53,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_bookings_deposit_type_id,NaN,NaN,NaN
96,2026-06-14 11:52:54,Warehouse DDL,SUCCESS,index idx_elt_fact_bookings_reserved_room_type_id,NaN,NaN,NaN
97,2026-06-14 11:52:54,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_bookings_reserved_room_type_id,NaN,NaN,NaN
98,2026-06-14 11:52:54,Warehouse DDL,SUCCESS,index idx_elt_fact_bookings_assigned_room_type_id,NaN,NaN,NaN
99,2026-06-14 11:52:54,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_bookings_assigned_room_type_id,NaN,NaN,NaN
100,2026-06-14 11:52:54,Warehouse DDL,SUCCESS,index idx_elt_fact_reviews_review_date_id,NaN,NaN,NaN
101,2026-06-14 11:52:55,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_reviews_review_date_id,NaN,NaN,NaN
102,2026-06-14 11:52:55,Warehouse DDL,SUCCESS,index idx_elt_fact_reviews_reviewer_country_id,NaN,NaN,NaN
103,2026-06-14 11:52:55,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_reviews_reviewer_country_id,NaN,NaN,NaN
104,2026-06-14 11:52:56,Warehouse DDL,SUCCESS,index idx_elt_fact_reviews_review_hotel_id,NaN,NaN,NaN
105,2026-06-14 11:52:56,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_reviews_review_hotel_id,NaN,NaN,NaN
106,2026-06-14 11:52:56,Warehouse DDL,SUCCESS,index idx_elt_fact_hotel_monthly_performance_month_start_date_id,NaN,NaN,NaN
107,2026-06-14 11:52:56,Warehouse DDL,SUCCESS,foreign key fk_elt_fact_hotel_monthly_performance_month_start_date_id,NaN,NaN,NaN
108,2026-06-14 11:52:56,Load Warehouse,SUCCESS,Loaded 16 tables with prefix elt into postgresql,NaN,NaN,144.3137
109,2026-06-14 11:52:58,Analytic SQL Queries,SUCCESS,Executed 10 analytic SQL queries for prefix elt,NaN,NaN,2.2334
110,2026-06-14 11:52:58,Pipeline Complete,SUCCESS,ELT pipeline completed,NaN,NaN,346.1151